### ISSUE TITLE
Search Results: Less information on larger screens?

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#100]
When I search on the iPhone, it gives me snippets as a result, so I can see the occurence of the search term in the text.

When I search on the iPad, it gives me only the page titles. Why do I get less information when I have more room on my screen?

**Comment by martin8032** [comment]
BTW: But I like the recent search feature, and the performance of the search is very good!

**Comment by automactic** [comment]
Were you perhaps not using a zim file with embedded index on your iPad?

**Comment by martin8032** [comment]
Looks like. The ZIM files on the iPhone were older, the were indexed – the ZIM files on the iPad are newer, they are not index. And as far as I can see, I can only download ZIM files without index at the moment. Why is that?

**Comment by automactic** [comment]
There is a bug causing zim files not showing that they have index even when online library indicates they have. It is fixed in the next upcoming beta version (which has not beed released yet)

**Comment by kelson42** [comment]
@automactic Not aware at all about that problem with the library, we have a ticket somewhere?

**Comment by automactic** [comment]
No, but it should have been fixed in 1.9 build 4

**Comment by martin8032** [comment]
I don't think it's fixed in v1.9 (4). Of course I did not check every package, but very package that I did check said: Indexed = No.

**Comment by automactic** [comment]
Oh, you need to reinstall the app.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martin8032** [comment]
Even with v1.9 (5) I cannot find a package with «Indexed = Yes» in the cloud.

And the behaviour with the packages I've downloaded with v1.8.1 is not consistent. For example, I have the following packages installed:
– Wikinews (embedded index)
– Wikiquote (not indexed)
– Wikisource (not indexed)
– Wikivoyage (embedded index)

When I enter one single character in the search field, the results appear as expexted (title only for packages WITHOUT index, text snippet for packages WITH embedded index):

![2018-02-11 20 30 04](https://user-images.githubusercontent.com/7620141/36077460-8b80829e-0f6b-11e8-9107-6e807ffd96b8.png)

But once I enter a second character, all text snippets disappear:

![2018-02-11 20 30 28](https://user-images.githubusercontent.com/7620141/36077466-96b79dc8-0f6b-11e8-8f77-ed60a25a428c.png)

**Comment by martin8032** [comment]
OK, thank you for this information.
