### ISSUE TITLE
iOS library sidebar "shivers" up and down

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#101]
With version 1.9 (3), start a download and try to go to sidebar bottom.https://expirebox.com/download/2dd36c01f3eedeb61a650e69c80d2bf1.html (link only valid 2 days)

**Comment by automactic** [comment]
I can confirm this. It happens when download section is partly within the bounds of `UITableView` and only one cell is in the download section. 

I suspect it is because of some `contentOffset` calculation error internally in `UITableView` when `tableView.endUpdates()` is called.

**Comment by automactic** [comment]
This is likely a SDK error or something I do not yet know how to solve. There is nothing more to be done at this point, will reopen this in the future if a solution come up.
