### ISSUE TITLE
Picture indicator for ZIM packages missing

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#102]
Problem: When I select ZIM packages for download, I can only tell by their file size if they come with or without images (or I have to open the details view).

Suggestion: It would be helpful to have the picture indicator back.

![2018-02-09 07 03 21](https://user-images.githubusercontent.com/7620141/36013973-adfc1776-0d67-11e8-9ee2-04f6975e86e1.png)

**Comment by automactic** [comment]
I agree this is an issue and I have heard this from other testers. The problem with the picture indicator is a lot of users do not know that means picture or not have picture. And we also have index / no index and video / no video. 

It is actually not hard to tell by looking at size and article count. If two book are made at the same time of the same article count, the bigger one has media. 

I had a design prototype with colored dots on the top right corner of the row and legend at the bottom of the screen. This feature might come at a future update.

**Comment by martin8032** [comment]
Of course you can tell by the size, but you have to know that, and even then it's not intuitive.

To remove the picture indicator because not everybody understands it makes things worse for those who do and not better for those who don't understand the difference.

Some indicator is mandatory in my eyes. But it could also be a text, for example:

**Wikiversity**
137 MB, 27.07.2017, 42.0K articles, incl. images

**Wikiversity**
63.7 MB, 27.07.2017, 42.0K articles, excl. images

My preference would be icons (not just colored dots).

**Comment by automactic** [comment]
Icon is a Great idea. No need for legends this way. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by automactic** [comment]
@kelson42 I am not planning to do anything for this in the moment. Would you object if I close this as won't do?

The ultimate problem is space is limited, what info to display and how to do it. We already show file size, created date and article count. I don't think adding additional info would make things significantly better. The tradeoff is: more info, saved one tap; but also more verbose.

I will certainly take this into consideration when the time comes for another redesign, but I don't think I will do anything right now

**Comment by rgaudin** [comment]
I think you can close as this won't be implemented but I also think we should organize issues better as we do have valid requests that can't be implemented in the short term because of manpower but would be helpful to design future releases roadmaps.

On this particular issue, @martin8032 knows that we now have flavours for zims files and that should be the base for such an information. I'm in favor of informing the user as I don't think size is meaningful to newcomers but I also don't want to clutter the UI.
If we can find icons for flavours, that'd be great but I think the color-code would already be a great improvement.

**Comment by automactic** [comment]
Closing this as no plan to do anything at the moment

**Comment by kelson42** [comment]
@automactic Sorry for my lack of reactiveness here. I do believe that the request is legitimiate and do not believe our current proposal is sufficient enough. But I understand the the problem is quite complex. To me this is important to keep track on that but we should definitly improve the primitive at libkiwix level.

**Comment by automactic** [comment]
> libkiwix level

I don't see how any work on libkiwix level can improve anything this issue is trying to address, please elaborate

**Comment by kelson42** [comment]
One time the libkiwix is able to deliver properly the information about the flavours then it shoudl be properly displayed here as well. Which means the different flavours of a same content should be somehow first visible together and then each should be proposed in a fully understandable manner.

**Comment by automactic** [comment]
> One time the libkiwix is able to deliver properly the information about the flavours then it shoudl be properly displayed here as well.

I am assuming you are referring to some info that does not exist right now? Can you give me some examples?

> somehow first visible together and then each should be proposed in a fully understandable manner.

When the time comes, could you please be as clear as possible about what you would like the info to be organized and presented? I am honestly pretty happy with the status quo, so I likely won't be able to come up with anything better

**Comment by rgaudin** [comment]
I think he’s referring to the flavours (mini, no pic, maxi) which are just file names now but will eventually be properties.
From what I understand, the user would first see only one entry per multi-flavour zim and then be able to choose the flavour.
Idea being it’s just one zim available in multiple flavors and not 3 zims.

there a several ways to render this and I don’t think it matters now how, as the underlying data isn’t there.

**Comment by automactic** [comment]
@kelson42 Hey, what are we planning to do with this one?

**Comment by kelson42** [comment]
The request is legit, but it is hard for you to do all the job. There we need to implement https://github.com/kiwix/kiwix-lib/issues/421 first. Resources are allocated to get that done in the next months.

**Comment by kelson42** [comment]
@automactic has implemented a "no pic" which show if there is no picture.
