### ISSUE TITLE
App crashes when you enter a search term

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#103]
Here's what I did:

1. I reinstalled 1.8.1 from the app store.
2. I installed v1.9 (4).
3. I downloaded some packages.
4. When I enter the first character in the search field, the app crashes.

**Comment by automactic** [comment]
Please use build 5 instead 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martin8032** [comment]
I can confirm that the problem does not occur in build 5.
