### ISSUE TITLE
Download UX issue persisting with v3.6.0

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#1052]
User reported still having issues with the newly released 3.6.0
Device: iPhone 16 Pro Max running iOS 18.1

Downloaded Wikipedia en_maxi, and the app froze when 100% is reached.

**Comment by kelson42** [comment]
@Popolechien user should open issue, you would be of no help to test new version.

**Comment by Popolechien** [comment]
@kelson42 User has no Github account so I'll have to play the middleman.

**Comment by Popolechien** [comment]
Well problem solved, user uninstalled and reinstalled the app and it works now.
