### ISSUE TITLE
New strange crash scenario

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#108]
1 - Download https://download.kiwix.org/zim/wikipedia/wikipedia_en_wp1-0.8_novid_2018-01.zim
2 - Open main page
3 - Click on link "John R. Bolton - Leonid Brezhnev"

... Then app crash systematicaly on my iPhone

**Comment by kelson42** [comment]
I'm not able to reproduce the problem on my iPad. I suspect that somehow the file is corrupted on my iPhone... but how is that really possible, we should detect that earlier.

**Comment by automactic** [comment]
It could also be a arch issue. Your phone is using armv7 build whereas your iPad is using arm64 build.

**Comment by kelson42** [comment]
@automactic I will try to redownload the file.

**Comment by automactic** [comment]
@kelson42 Are you able to reproduce the error on your phone with a redownloaded zim file?

**Comment by kelson42** [comment]
@automactic yes, I definitly can not read properly all articles in that files with my iPhone.

**Comment by automactic** [comment]
I cannot reproduce this problem on my device (11.2.5, 64bit) or on a simulator (10.3.3, 64bit). I do not have a 32 bit deice / simulator to test. Maybe the issue is specific to a device or arch.

**Comment by kelson42** [comment]
@automactic Do I have way to share with you a tracelog or similar?

**Comment by kelson42** [comment]
This might be maybe a lack of memory... but I know now way to confirm that.

**Comment by automactic** [comment]
There is no reliable ways to reproduce this issue. The file linked is also gone.

And I am assuming this is not happening anymore? Please reopen if this is still an issue and you would like it fixed
