### ISSUE TITLE
osx app update?

### ISSUE THREAD

**Issue by Dispositiv** [kiwix/apple#110]
- do you plan to also update the osx-app (like the latest ios)?

- is it possible to have at least some hints on the file where to change window-size of the osx-app etc. - if not the last settings could be saved?

- search capability inside articles in the osx-app would be great

**Comment by kelson42** [comment]
We plan to publish Kiwix for MacOS 2.0 during Spring/Summer.

**Comment by automactic** [comment]
The Mac app is published to the App Store. Please download it here: https://itunes.apple.com/us/app/kiwix-desktop/id1275066656?mt=12
