### ISSUE TITLE
Suggestions for organizing bookmarks

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#113]
Currently, I see all my bookmarks of all packages in the sidebar. If I am a heavy user of the Kiwix app, this can become a long list of very diverse topics quickly.

Suggestion 1: Provide an option «Show only bookmarks of current package».

Suggestion 2: Provide an option «Group bookmarks by package».

Suggestion 3 (long term): Implement a bookmark organizer as you know it from a web browser (with a folder structure)

**Comment by automactic** [comment]
A proper bookmark manager is planned and will come at a later version. But in 1.9 release, there is only gonna be a simple list of added bookmarks.

**Comment by automactic** [comment]
No action is planned to be taken from this ticket. Thanks for the suggestions
