### ISSUE TITLE
With 1.9 (8), on my iPhone5, the TOC seems to be always empty

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#114]
What ever the page or the ZIM, I always have an empty TOC "Table of content not available". This even for a page which has a proper page on my iPad. I do not know if this is a regression with #93...

I test for example with the article "Create Commons license" of the ZIM file "Wikipedia 0.8" (english) from 11/01/2018.

**Comment by automactic** [comment]
Are you using wikipedia_en_wp1-0.8_novid_2018-01-1.zim? I loaded the "Create Commons license" article and the toc works.

**Comment by automactic** [comment]
Ooops, I forgot to inject the extract toc js before I get the toc on iOS 10. Will be fixed in the next beta

**Comment by automactic** [comment]
Fixed in 1.9 (9), please test

**Comment by kelson42** [comment]
@automactic fixed :)
