### ISSUE TITLE
Sporadic top-bar overlapping button/searchbar with 1.9

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#115]
I do not have really a reprocase, it happens with all kind of ZIM files randomly... often at the beginning after clicking on "open main page" in the library.
 
![f8321d08-e633-41c0-945a-46fddbf0939b](https://user-images.githubusercontent.com/1029718/36350547-2388570a-149a-11e8-8ac0-0b2a0e0e7e2c.png)

**Comment by automactic** [comment]
Mmm, this is because of a bug in iOS 11 (which is very frustrating). Buttons overlap with search bar!! 

I have a workaround in the current beta, but apparently that does not always work on your iPad.

**Comment by kelson42** [comment]
The bar comes to the normal position, one time I start to type in the bar (by getting the focus?)

**Comment by automactic** [comment]
> The bar comes to the normal position 

What do you mean? The top bar you mean? Isn't the top bar always on the top of the screen?

> one time I start to type in the bar

Do you mean it only happened one time when you started typing? Or does it always happen when you start typing?

I am very confused.

**Comment by automactic** [comment]
@kelson42, please see if you can find out a way to reproduce the issue, otherwise I cannot fix it

**Comment by kelson42** [comment]
@automactic I have been impacted many times but do not have been able to find a clear reprocase. I got an update of iOS this morning on my iPad, maybe it has fixed the pb. Please keep this ticket a bit more time open.

**Comment by automactic** [comment]
That update, if it is iOS 11.2.6, is not likely to have fixed the problem, since it was released to address problem where a Telugu char causing text related apps (like chat, and likely kiwix) to crash.

**Comment by kelson42** [comment]
I don't have seen it recently. Therefore, I close the ticket.
