### ISSUE TITLE
Library top spider displayed often, long, ... and I do not know why

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#118]
On my iPhone, the library top spider is displayed often, long, ... and I do not know why. I just have to scroll down (so to see the top) and the spider is displayed for many seconds... but this does not change anything in what is displayed and I do not see exactly what kind of long asynchronous process should be triggered by scrolling down!

**Comment by automactic** [comment]
Spider?!?!🕷

What in the world are you talking about??

**Comment by kelson42** [comment]
Something like this http://www.xavdrone.com/wp-content/uploads/2014/10/maj-200qx-2.0-15-300x126.jpg... An image telling you something is running, you should wait.

**Comment by automactic** [comment]
This is called [Refresh Content Controls](https://developer.apple.com/ios/human-interface-guidelines/controls/refresh-content-controls/)

**Comment by automactic** [comment]
@kelson42, do you have anymore feedback regarding this issue? If not please close the ticket

**Comment by kelson42** [comment]
@automactic Looks like this is a feature... was quite unclear to the user what exactly happens in background.

**Comment by kelson42** [comment]
@automactic I do not remember much the details, but I would say the left side bar.

**Comment by automactic** [comment]
Yeah, if it was on the top left section of the screen then it is the network activity indicator. Kiwix was either refreshing the library (might be in the background) or download a file.
