### ISSUE TITLE
Kiwix failed to open when zim file is deleted 

### ISSUE THREAD

**Issue by davideuler** [kiwix/apple#123]
After I deleted a zim file which was loaded by Kiwix, I could not open Kiwix anymore. It crashed and says it could not open the zim file. Hope it could be optimized.

**Comment by automactic** [comment]
@davideuler Mac or iOS? Which version of the app are you using? What is the name of the zim file in question?

**Comment by davideuler** [comment]
On Mac, with kiwiz 0.7.
I checked the latest version, and found that my version of kiwix is too old... Thanks
