### ISSUE TITLE
Erroneous downloads stays in "Downloads" List

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#126]
`Kiwix 1.9 iOS`

While downloading a ZIM, a *cancel* button is present to cancel the download but when the download fails, the button is not there anymore (there's nothing to cancel obviously).

Problem is there is no *retry* nor *remove* button and the erroneous ZIM stays in the *Downloads* list forever.

To reproduce, try `ICD-10` (french) from the *Other* Category. It's a permanent error.

![img_0181](https://user-images.githubusercontent.com/57929/39749588-a363d1b6-52a2-11e8-922c-974a10649f68.PNG)

**Comment by kelson42** [comment]
I confirm, I had the same issue.

**Comment by automactic** [comment]
lemme see

**Comment by hachi8833** [comment]
I got the same issue.

**Comment by kelson42** [comment]
Duplicate of #126
