### ISSUE TITLE
Add Wiktionary to the categories

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#127]
What is strange is that these Wiktionary files are even not available in the "Other" category!

**Comment by kelson42** [comment]
Might be possible to put all the ones which are not in categories... in the "others" ?

**Comment by automactic** [comment]
No no, the Wiktionary, Wikiquote and Wikisource categories are there. I forgot to add them to the library interface. This issue will be fixed in the next release

**Comment by kelson42** [comment]
@automactic Thx, I confirm the bug is properly fixed
