### ISSUE TITLE
Rough Design Feedback

### ISSUE THREAD

**Issue by schoenbaechler** [kiwix/apple#129]
Hi there! I’m currently working on the Kiwix Desktop 2 designs. @kelson42 mentioned the new version of the Kiwix iOS app in a recent call. Congrats for the release! I’ve checked it out and thought I’ll leave some rough/minor feedback here to either ignore or consider.

1. Optimize start screen design based on the [Kiwix brand guidelines draft (by Nirzar from WMF)](https://www.dropbox.com/s/441ge9ttvpe0ogg/kiwix-brand-guidelines.pdf?dl=0), which could look like this:

![kiwix-ios-feedback-01](https://user-images.githubusercontent.com/5031003/40925656-836f4f6a-681a-11e8-913a-023e430745b0.png)

2. Show current article title in search and minimize top bar when scrolling down in article view to optimize reading experience:

![kiwix-ios-feedback-02](https://user-images.githubusercontent.com/5031003/40925666-8a944fde-681a-11e8-8f4a-6f5b042afe3a.png)

3. Add support for basic in-page search. It could work similar to Safari on iOS. A tap on the search bar reveals the global search. Below the global Kiwix search results, a basic in-page search could be added:

![kiwix-ios-feedback-03](https://user-images.githubusercontent.com/5031003/40925688-958dc60e-681a-11e8-892c-8144d6a38568.png)

4. Add possibility to search the library content (search field below "Library" title):

![kiwix-ios-feedback-04](https://user-images.githubusercontent.com/5031003/40925764-bab10dba-681a-11e8-9901-fb16d7702078.png)

I assume that the current version is a minimum viable product, which is btw. pretty easy and straightforward to use. Congrats on that as well! I’d also have some ideas for the navigation concept since the current one could have its limits when adding features in the future. But let’s save that for another time... 

Thanks,  
Robin

**Comment by kelson42** [comment]
Point 4 depends on libkiwix implementation of https://github.com/kiwix/kiwix-lib/issues/106

**Comment by automactic** [comment]
@schoenbaechler, thanks for the feedback.

1. I would like to use the KIWIX text from guideline. (I have tried it before) But I think the weight is too bold. Also minor thing, the font is not iOS default font.

2. It is not possible unless we make our own top bar. iOS gets really angry when someone try to modify the UINavigationBar height. iOS safari use private API which is not open to devs. 

3. In page search will be added, but I want to do it better than safari. I think it should be another function like table of content, bookmark, etc.

4. @kelson42, I think what Robin means is to search through title and maybe description of the database already on the device. 

I have been dying for the opportunity to talk with a design guru. One of the reason I have not added in page search, geo search, etc. is that I cannot fit them all on the bottom bar. And I do not want to use a hamburger button. I have a pretty good idea how I am gonna do it on iPhone, but not on iPad yet.

**Comment by schoenbaechler** [comment]
Hey @automactic, nice to meet you here on this sad day 👇:

![image](https://user-images.githubusercontent.com/5031003/41035104-e5961aa8-698b-11e8-9498-330d5cc47fd2.png)

Replies below:

> 1. I would like to use the KIWIX text from the guideline. (I have tried it before) But I think the weight is too bold. Also minor thing, the font is not iOS default font, which the rest of the app do use.

The Kiwix logo combination mark (logomark and logotype) can be used as a complete, path based, SVG. You wouldn’t need to embed custom fonts for this. The only exception would be if there are multiple Kiwix logotypes around for different languages, which I’m not aware of. From a Kiwix brand perspective, it would make sense to use the official Kiwix combination mark. 

> 3. In page search will be added, but I want to do it better than safari. I think it should be another function like table of content, bookmark, etc.

Makes sense and agree that Safari’s way is not ideal. Having an obvious button for it definitely makes sense. The official Wikipedia iOS app handles it that way: Main navigation and content agnostic elements such as TOC and in-page search are separated. I could imagine a similar information architecture could work for Kiwix. Also, as food for thought: I came to the conclusion in Kiwix Desktop 2 that the best way to start the Kiwix app experience is to present users the core the app, its content. The intermediate step ("Open Library") feels like an unneeded step. [Here’s how it’s currently foreseen in Kiwix Desktop 2](https://wikimedia.invisionapp.com/share/7UIVNGPS9CA#/screens/300338417). 

> One of the reason I have not added in page search, geo search, etc. is that I cannot fit them all on the bottom bar. And I do not want to use a hamburger button. I have a pretty good idea how I am gonna do it on iPhone, but not on iPad yet. We can talk about it in another issue.

+1 on not using the hamburger button, it’s mostly an excuse for bad information architecture. I think a tab bar would suit better in this case (if a navigation is needed at all, sth to explore I guess). Happy to talk about ways to optimize the app’s structure in another issue, feel free to tag me if you need an additional opinion.

CC @kelson42

**Comment by automactic** [comment]
This is a discussion ticket and no action is pending at the moment. Thanks @schoenbaechler for your suggestions and opinions. Also, I am working on a new version with different design on iPad, lemme know if you would be interested to give it a try.
