### ISSUE TITLE
Search became slow with 1.9.1

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#130]
From a user email:
"I have some problem with KIWIX iOS new app  v1.9.1  - when I search, searching is wery slow comparible old app and version v1.9.  it search me obout 50 second (for example i typed : "New York City" i Have actually iPhone 6+  and ipad Air 2  but new version v1.9.1 is for searching very slow".

**Comment by automactic** [comment]
This issue is confirmed and is tracked on https://github.com/kiwix/kiwix-lib/issues/146.

The main reason is get snippet takes a lot of time. In 1.9.2 beta there will be an option to disable snippet as a test as in whether this feature makes sense

**Comment by automactic** [comment]
An option is added in the app to give the choice of disable snippets. This problem is considered fixed until more updates are coming from the libkiwix side.
