### ISSUE TITLE
Release notes for macOS 2.0

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#136]
Hello, I've posted on the release of macOS 2.0, but do we have release notes somewhere to indicate the difference with 1.9? (not in details, but at least broad strokes)

**Comment by automactic** [comment]
@kelson42 We only have one changelog.md file but two apps in this repo. How would you like to proceed with this issue? 

Combined the change log for both app in one file? or have two separate change logs?

**Comment by automactic** [comment]
Since I did not get a feedback how we should resolve this issue. I have decided we are going to create a file `CHANGELOG_macOS.md` for macOS app change log for now.

**Comment by kelson42** [comment]
@automactic Sorry, I made one but somehow this is not here. I’m fine with your move.

**Comment by automactic** [comment]
Release note is added inside `CHANGELOG_macOS.md` in the root of this repo
