### ISSUE TITLE
download broken.

### ISSUE THREAD

**Issue by Dispositiv** [kiwix/apple#138]
macos 'direct download' is broken (dropbox: 404).

**Comment by Dispositiv** [comment]
link: readme.md

would you please also supply a dmg here for those who have some concerns about the 'politics' of itunes or the appstore, esp. in the libre community.

**Comment by kelson42** [comment]
@Dispositiv I have uploaed a DMG here https://download.kiwix.org/release/kiwix-desktop-macos/

**Comment by jberkel** [comment]
Why was this issue closed? the download link is still broken.

**Comment by kelson42** [comment]
@jberkel You are right, I just have updated the README. Thx.
