### ISSUE TITLE
Create a CHANGELOG file

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#14]
This CHANGELOG file should be put a the root en list the releases with there respective bug fixes and new improvments. This is necessary to follow the dev over time.

**Comment by automactic** [comment]
CHANGELOG.md added to branch 1.6

**Comment by kelson42** [comment]
@automactic Sorry, but I don't see it anymore :(

**Comment by automactic** [comment]
CHANGELOG.md was added
