### ISSUE TITLE
Get Kiwix Desktop notarized by Apple

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#140]
To provide ever more confidence in the software, see here:
https://developer.apple.com/developer-id/

Here was the original email we got:
```
>     macOS Mojave is here. Give Mac users even more confidence in your
>     software distributed outside the Mac App Store by submitting it to
>     Apple to be notarized. When users on macOS Mojave first open a
>     notarized app, installer package, or disk image, they’ll see a more
>     streamlined Gatekeeper dialog and have confidence that it is not
>     known malware.
> 
>     Download Xcode 10 and submit your software today. In an upcoming
>     release of macOS, Gatekeeper will require Developer ID–signed
>     software to be notarized by Apple.
> 
>     Learn about getting your software notarized
>     <https://developer.apple.com/developer-id/>
> 
>     If you have any questions, contact us
>     <https://developer.apple.com/contact/>.
```

**Comment by Popolechien** [comment]
@kelson42 Looks like a coding-side issue, but anything to do on my end?

**Comment by automactic** [comment]
@Popolechien Nothing to do on your end. 

> In an upcoming release of macOS, Gatekeeper will require Developer ID–signed software to be notarized by Apple.

I need to submit app to apple.

**Comment by kelson42** [comment]
@automactic thx, would be great if you could do it.

**Comment by kelson42** [comment]
@automactic Seems mandatory now https://developer.apple.com/news/?id=09032019a

**Comment by automactic** [comment]
The latest version of the Mac app(version 2.1) I uploaded for testing are already notarized. I think I can close this ticket now
