### ISSUE TITLE
iOS showing much older version than website

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#142]
From a user:
"My iPhone 7+ is running "On Device" "Wikipedia 82.93 GB, July 2, 1018, 5.7M articles". Under "Categories" it shows under "Wikipedia" exactly the same entry.
However, your web site at http://wiki.kiwix.org/wiki/Content shows what I assume is the updated file "wikipedia (English)	en	79G	2018-10	all novid"

**Comment by Popolechien** [comment]
_Update from user:_
I’ve loaded the October 2018 version with photos onto my iMac. Then I copied it to my iPhone using iTunes. It initially showed a lot of strange things, but after ‘digesting’ the 86 GB file, the iOS “iPhone Storage” showed Kiwix as having the 86.1 GB I expected (I have a few other small Kiwix files on the iPhone).

However, the iOS Kiwix app itself shows the file as having only 2.25 GB and zero articles, even though every search I have done turns up a hit and it seems to work perfectly.

I have two screen shots below:
![1](https://user-images.githubusercontent.com/21675885/49273583-c055ce80-f475-11e8-9372-ace85423cffb.jpeg)

![2](https://user-images.githubusercontent.com/21675885/49273581-bfbd3800-f475-11e8-963d-62518f713619.jpeg)

**Comment by kelson42** [comment]
@automactic Any clue what happens here?

**Comment by automactic** [comment]
The database on iOS devices will use info in library.xml if the zim file added using iTunes is already inside the xml file. I believe in this case library.xml is wrong (or was wrong) and the error got persisted.

**Comment by kelson42** [comment]
@automactic Would you have a workaround to somehow force a refresh?

**Comment by kelson42** [comment]
I strongly suspect this was a problem with the library. We had a few ones. Now all of this should have been fixed now and we don't have heard any problem recently.
