### ISSUE TITLE
Massively huge font size on iPhone 5s

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#143]
Reported on IRC:

> <jfcaron> I cannot read any pages using Kiwix on my iPhone 5s.  The font size is apparently massively huge, and I cannot seem to change it.
<jfcaron> The font size settings screen looks like this: https://imgur.com/a/qJqQRiG
<jfcaron> There are scroll bars in e.g. wikipedia main page, but they are so long I cannot meaningfully scroll down.  On wiktionary if I scroll 
![zncqif3](https://user-images.githubusercontent.com/1029718/49325805-9a4d2e80-f548-11e8-911b-f5407adfdf97.jpg)

**Comment by goops17** [comment]
Can I work on it?

**Comment by kelson42** [comment]
@goops17 Yes please :) @automactic Hope this is OK for you.
