### ISSUE TITLE
Unable to build iOS Project.

### ISSUE THREAD

**Issue by yugantarjain** [kiwix/apple#145]
I'm running into a few problems while building the Kiwix project for iOS.

1. After cloning the project and adding ProcedureKit to it, when I run “pod install” in terminal I get this message at last.
I tried to do the changes but they reappear again and again.

`[!] The `iOS [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-iOS/Pods-iOS.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `iOS [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-iOS/Pods-iOS.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
`

2. The compiler isn’t able to find the “entry.h” header file in ‘ZimMultiReader.mm’.

**Comment by kelson42** [comment]
@automactic Would be good to have in the README, the step by step procedure to follow to compile both MacOS and iOS apps.

**Comment by codnee** [comment]
@yugantarjain building this project requires some artifacts generated by following the build instructions in https://github.com/kiwix/kiwix-build

**Comment by kelson42** [comment]
@yugantarjain Yes, the libkiwix is needed, or do you have something else which needs kiwix-build?

**Comment by kelson42** [comment]
The build instructions have been added the !3th of September by @rgaudin. I think we can close the ticket. If anything else is needed please open a new ticket.
