### ISSUE TITLE
MacOS search problem

### ISSUE THREAD

**Issue by rubelito** [kiwix/apple#146]
Guys, I recently downloaded the Kiwix 2.0.9 for mac and stackoverflow zim, I think the zim is around 55GB, I noticed that the search result/suggestion wasn't accurate or satisfying enough. It seems that it only search for title only and not the entire page. It's almost unusable because I cannot find the article that I'm looking for.

Now, I wasn't sure if this is an issue but It will be great if the search can also look for the entire pages.

Thanks,

**Comment by kanupriyaa** [comment]
I am using Kiwix v2.0.9 for MacOS and did not encounter this problem. The search bar is searching not only the titles but the entire pages as well. 

Please see screenshot attached for reference. 
![Screenshot 2019-06-18 at 1 41 20 PM](https://user-images.githubusercontent.com/44517226/59664503-cc656b80-91ce-11e9-8dcd-ddab3fa012a7.png)

**Comment by kanupriyaa** [comment]
@kelson42 this issue can be closed, kindly look into it.

**Comment by kelson42** [comment]
@kanupriyaa What do you mean exactly? The problem is not fixed AFAIK.

**Comment by kelson42** [comment]
@automactic If you could just confirm is searches in the whole articles, I think we could close this ticket.

**Comment by automactic** [comment]
We are indeed performing search based on index of article content. What is worth noting is in iOS and macOS version of the app, if there is a strong match between title and search text, that will be added in search as well.
