### ISSUE TITLE
Cannot unfold article subsections in iOS v1.9.6

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#150]
Did not have the issue on macOS 2.0 or Kiwix-JS 2.5.0, so I'm flagging this here anyway: a gentleman from Russia said he was not able to unfold the section titles in the last version of Wikivoyage.
![image1](https://user-images.githubusercontent.com/21675885/58097903-b9b04480-7bd8-11e9-814e-a4ff6f2ee395.png)
(just so you know this is a screenshot of the [Gatchina article](https://ru.wikivoyage.org/wiki/%D0%93%D0%B0%D1%82%D1%87%D0%B8%D0%BD%D0%B0))
@ISNIT0 I can't find the ticket where this new feature was discussed.

**Comment by kelson42** [comment]
I strongly believe this is a problem with the ZIM file itself.

**Comment by Popolechien** [comment]
That's what I thought initially but then why / how would it work on macOS, -JS and Android?

**Comment by ISNIT0** [comment]
@kelson42 I can't be certain, but this looks like a ZIM file from before the recent changes. I believe that whatever caused this has been removed/changed since 👍

**Comment by Popolechien** [comment]
Ok thanks @ISNIT0 - I'll double check with user.

**Comment by ISNIT0** [comment]
Also, this is the original ticket: https://github.com/openzim/mwoffliner/issues/677

**Comment by kelson42** [comment]
My strategy: just wait mwoffliner 1.9 release and new wikivoyage and test again.

**Comment by kelson42** [comment]
@Popolechien I guess you talk from the Wikivoyage RU created the 8 May 2019. I have tried myself and it works fine on my iPads. Have you tried yourself?

**Comment by kelson42** [comment]
@Popolechien I can not reproduce the problem either on my iPad or iPhone. I close the problem has it is not reproducable or maybe already fixed?!

**Comment by Popolechien** [comment]
@kelson42 Yep, tried it here as well and it all went fine.
