### ISSUE TITLE
Downloaded file will not leave download window

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#151]
Feedback from user - the title says is all (iPhone XS (iOS 12.3, 128GB)). The file cannot be read and is not seen anywhere on the phone.
Here's a screenshot:

![OveNU6gZ-MvRx93QhGHZdU9g1ez5lnuQog](https://user-images.githubusercontent.com/21675885/58318437-05046600-7e18-11e9-926f-d21516d2293e.png)

**Comment by Popolechien** [comment]
Further comment from user : downloaded three other random zim files without any problem, but a second download of enwp (novid / 78Gb) led to the same result.

**Comment by kelson42** [comment]
@automactic We had already similar bug reports about that, see #121 or #126. It seems that at the end of the download we have a kind of error prone behaviour and one time an error has occured (which seems to be transparent) then there is no second chance! Probably the whole logic around this should be reviewed and strongly tested.

**Comment by kelson42** [comment]
@automactic Just got [an other feedback on our forum from someone who has downloaded 3 times the same 80GB content and is always stuck at the end](https://sourceforge.net/p/kiwix/discussion/604122/thread/dbf833adf3)!

**Comment by Popolechien** [comment]
I'm just piling up for the sake of it but a very nice lady wrote today for the exact same issue (iPhone XR, 256 Gb storage available, other downloads worked ok).

**Comment by kelson42** [comment]
@Popolechien Nothing has been done to fix the bug, but would be nice to know if you have experienced or got recently new feedbacks about that bug?

**Comment by Popolechien** [comment]
No new feedback, no.

**Comment by automactic** [comment]
If no new similar bug has been reported, I am closing this issue

**Comment by Maxus79** [comment]
Hello. I am experiencing the same issue for several days. I was able to download any content in Kiwix iOS except Wikipedia itself - each time it starts normally but then stucks on or around 100%. iOS 15.5, iPhone 13 mini, 512GB

**Comment by kelson42** [comment]
@Maxus79 This ticket is pretty old and closed. Would you be able please to open a new ticket?
