### ISSUE TITLE
Library language list should be sorted alphabetically (per default)

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#153]
The "Hiding" part proposes hundreds of languages... but they are not sorted alphabetically, so this is really complicated to find the one you search. The button "A-Z" is selected so it should. Unclicking and clicking on it solve the problem... so looks like at the start of the context menu, the sort is not applied.

**Comment by automactic** [comment]
@kelson42 I think in the latest version, the default sort method in language selector is "by count" and the list is also indeed sorted by count. 

@kelson42 Could you check if actions are still needed in the latest version?

**Comment by kelson42** [comment]
@automactic I tested again with last testflight version. I had still the bug... but after testing further and reinstalling again, it seems to have vanished. So looks good :) Thx.
