### ISSUE TITLE
[Enhancement] [UI] Support multiple tabs on Kiwix for MacOS

### ISSUE THREAD

**Issue by kanupriyaa** [kiwix/apple#154]
The only info displayed on Tab Bar currently is "Kiwix". 
This can be removed, and instead have options of multiple pages/tabs.

**Comment by kelson42** [comment]
@kanupriyaa Are you talking of Kiwix for iOS? or Kiwix for MacOS? What is the exact version? If you talk about iOS, the tab does not display "Kiwix" like you can see on the iTunes screenshots... or maybe you could provide a screenshot of what you see to better explain what you mean?

**Comment by kanupriyaa** [comment]
I am talking about Kiwix for MacOS, Version 2.0 (2.0.9)
Please see the screenshot attached. 

![Screenshot 2019-06-17 at 2 18 10 PM](https://user-images.githubusercontent.com/44517226/59591028-e473b700-910a-11e9-9f14-c03fd90736e5.png)

**Comment by kelson42** [comment]
@kanupriyaa Thx, so your request is about supporting multiple tabs on Kiwix for MacOS? Do I get it right?

**Comment by kanupriyaa** [comment]
Yes, I believe this space can be better utilised. 
Also, I want to start contributing to open-source, and I am interested in Kiwix. Any guidance?

**Comment by kelson42** [comment]
@kanupriyaa Thx for the clarification. We recommend to start by reading https://www.kiwix.org/en/support-us/code/

**Comment by automactic** [comment]
we are gathering feature requests into one central place. marking this as closed

**Comment by kelson42** [comment]
@automactic Please keep one ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects. Rule about how to deal with tickets are give at https://github.com/kiwix/overview/blob/master/REPORT_BUG.md

**Comment by automactic** [comment]
We have added multi tab since macOS app version 2.1

<img width="1063" alt="Screen Shot 2020-07-08 at 9 02 40 PM" src="https://user-images.githubusercontent.com/8294252/86985105-5e377200-c15e-11ea-9141-13933c3f8fd9.png">
