### ISSUE TITLE
Support command+f feature to find a word/phrase on a page for MacOS

### ISSUE THREAD

**Issue by kanupriyaa** [kiwix/apple#155]
Kiwix for MacOS v2.09 does not have any option to locally search for a word or a phrase on a given page.

**Comment by automactic** [comment]
merged this issue into the central place to track feature requests

**Comment by RALEx147** [comment]
Is there any update on this issue? Is there a work around to this?

**Comment by kelson42** [comment]
@automactic Please keep on ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects.

**Comment by automactic** [comment]
consolidating this with #79
