### ISSUE TITLE
Support USB storage

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#156]
In case this is already in the works feel free to close this ticket, but here's a bit of user feedback: 
"As iOS 13 on the iPad (iPadOS) will be getting support for USB drives, i think being able to open Zim archives directly from external drives is a nice feature to have, as storage on the iPad is sometimes a scarce resource.

Also, your application is amazing."

**Comment by kelson42** [comment]
@automactic With the introduction of file loadin, is that feature request not already implemented?

**Comment by kelson42** [comment]
@automactic Can we close this ticket?

**Comment by automactic** [comment]
We already support loading zim files form the iOS Files app, so technically speaking user can load a file from anything the Files app supports, which includes a USB drive if user have a new enough iPad or a dongle

I have no dongle and my iPad is not new enough to support direct USB thumb drive. So I have no way to test.

Let's close this for now and reopen it should anyone report they were unable to do so.

**Comment by automactic** [comment]
also duplicate of #186
