### ISSUE TITLE
Feature Requests Mega Thread

### ISSUE THREAD

**Issue by automactic** [kiwix/apple#166]
This is the place gathering all feature requests for the Kiwix for iOS and macOS app. If you have feature requests please open a new issue and we will update it here. This thread is locked to keep it clean prevent it from getting off-topic.

## Feature Requests

**Dark Mode**
Flip the interface and the article dark, easier on the eyes at night. [#82]

**Tabs**
Switching between multiple browsing sessions. [#75][#154]

**Random Articles**
A button that will show user a random article when being pressed [#78]

**Search in Page**
Find a string in the current article. [#79][#155]

**Comment by kelson42** [comment]
@automactic Please keep one ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects.
