### ISSUE TITLE
Main Page Bookmark name blank

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/apple#167]
In case we bookmark the main page of a zim file, The bookmark name is not visible on both the bookmark screen as well as on long press of the app icon.

|.|.|
|:-:|:-:|
|![IMG_3239](https://user-images.githubusercontent.com/32238400/63165942-26e34280-c02d-11e9-9d11-2d3d0f0e3c5d.jpeg)|![IMG_3239](https://user-images.githubusercontent.com/32238400/63166257-29926780-c02e-11e9-95d0-2e2f92c17750.PNG)|

Also, I am not quite sure why the exact zim file icon is not being shown in the bookmarks screen.

**Comment by siddharth2010** [comment]
update: looks like bookmarking the main page does work on most zim files. However it does not work for some.

**Comment by automactic** [comment]
Thanks for reporting! I have updated the bookmark title logic to use the zim files title as a fallback for when the article doesn't have a title or has empty string as title. #299 

![IMG_11A569FC1E2E-1](https://user-images.githubusercontent.com/8294252/89742887-e796d880-da6b-11ea-9e7a-fe616645e050.jpeg)
