### ISSUE TITLE
Expand Section not working on some Zim Files

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/apple#168]
I am unable to expand sections of the wikipedia articles in some of the zim files.

![image](https://user-images.githubusercontent.com/32238400/63212219-3d5ace00-c101-11e9-9785-988f88135520.png)

**Comment by kelson42** [comment]
@siddharth2010 Are we talking about that file? https://download.kiwix.org/zim/wikipedia/wikipedia_en_ray_charles_maxi_2019-08.zim

**Comment by siddharth2010** [comment]
No. I am talking about the 5.2 mb one.

**Comment by kelson42** [comment]
The problem is in the ZIM file, I will remove it from the mirror/library. Thx.
