### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#169]
In order to support the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your reader:

* is feeding itself from the OPDS stream (using a local cache/copy or not)
* is using the lastest libkiwix (not released ATM). It supports new options and includes the backward-ompatibility bits you'd need.
* is using the [centralized Categories List](https://github.com/kiwix/kiwix-tools/issues/317)
* is using the new tags only for flavours and full-text index.

**NOTE**: This issue for planning purposes, OPDS and libkiwix **does not support** those features at the moment.

**Comment by automactic** [comment]
@kelson42 Here is what I propose to do for this issue

1. Wwitch the source of truth for "all zim files available" from `https://download.kiwix.org/library/library_zim.xml` to `http://library.kiwix.org/catalog/root.xml`
2. The favicon of zim files will be dynamically loaded when they first time appear on screen, then cached. A default zim file icon will be displayed before the favicon is fetched from online.
3. Update the list of categories to the list linked above (it is still going to be hardcoded)
4. Use private tags to determine if a zim file has pic, index, etc.

Nothing else will be changed! 

Please let me know if this is OK with you

**Comment by rgaudin** [comment]
Looks good. We shall maybe open a separate issue once kiwix/kiwix-tools/issues/317 is implemented.

I also think a non-immediate feature would be to query the OPDS properly instead of using this file directly (I'm assuming that's what you're doing but don't really know).

**Comment by automactic** [comment]
@rgaudin Hey thanks for the feedback.

I think the library in the app needs to be either complete online or complete offline. Combining  these two options can be somewhat confusing. If we want the app to always query the online OPDS, then I won't continue spending time on the offline library.

@kelson42 do you have any opinion on this matter?

**Comment by kelson42** [comment]
@automactic Yes, looks like a good step forward!

**Comment by automactic** [comment]
@kelson42 No, I mean do you have an opinion on if the app should have a totally online based library or a totally offline based library?

**Comment by rgaudin** [comment]
What I would do would be to download the remote library _once_ and use it as source for the libkiwix's internal library and then query it.

This way it's offline (IMO, users should be able to browse the library offline) but I think it's important to use libkiwix as most as possible to make sure it fits all readers' needs.

**Comment by kelson42** [comment]
@automactic I think the libkiwix should provide a certain level of cache... But I can hardly say more for the moment. I don’t really see the value of having the online catalogue if disconnected... but I can not say that this is a bad idea.

**Comment by automactic** [comment]
OPDS integration was implemented in #238
