### ISSUE TITLE
Support article export to PDF

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#171]
I'm not even sure that is possible but an iOS user made the request via OTRS, so I'm following up. Feel free to close if unapplicable.

**Comment by kelson42** [comment]
Not convinced at all about that feature request. What is exactly the problem to solve?

**Comment by Popolechien** [comment]
Probably printing, if I were to guess.

**Comment by automactic** [comment]
@Popolechien is this a one-off request from one single user? Or has many users raised this?

If there is only one user then perhaps we should close it as `Won't Do`. We got bigger fish to fry.

**Comment by kelson42** [comment]
@Popolechien I tend to agree with @automactic. I don't really see here the use case. This is a kind of feature request I would agree to tag with "Won't fix".

**Comment by Popolechien** [comment]
Haven't seen it come back ever since. Closing ticket.
