### ISSUE TITLE
iOS: Bug when click on „save Image“ 

### ISSUE THREAD

**Issue by BeniCydia** [kiwix/apple#177]
System Info:
OS: iOS 12.4
Device: iPadAir (2019) (WIFI)
AppVersion: 1.10

-when press and holding a image and click on „Save Image“
the screen gets black and Crashes

**Comment by jayson528** [comment]
hey do you mind if i try and fix this bug?

**Comment by kelson42** [comment]
@jetownfeve21 No, that would be nice. Thank you for your proposal.

**Comment by MikeBenton2** [comment]
@kelson42 Confused on these last comments. If this is still an issue, I'd love to take a shot at it!

**Comment by kelson42** [comment]
@MikeBenton2 The bug is still there. A PR from you would be really welcome :)

**Comment by BeniCydia** [comment]
This is still an Issue. I've tested it 2 weeks ago (and checked if my Kiwix is up to date). Would be very helpful if you would fix that, or the best option: add anything that allows to export whole artivles. This could be done by: 
-adding an "open in safari" option
-adding an "save as pdf/html/webarchieve" option
-adding Kiwix-Server abillities to the App

**Comment by automactic** [comment]
fixed in https://github.com/kiwix/apple/commit/9167289e05f29464d97795aa13dca63938e8c7e7
