### ISSUE TITLE
Add local backend url sheme

### ISSUE THREAD

**Issue by BeniCydia** [kiwix/apple#178]
I know it‘s difficult but it would fix a lot of missing features: 
add a local url sheme to open pages in  other apps

Feature wanted:
-add a „copy URL“ to share button which contains the original Wikipedia url 
this would be nice for offline working on presentation to write down the sources

**Comment by kelson42** [comment]
@BeniCydia Is that a request for Kiwix iOS or macOS?

**Comment by BeniCydia** [comment]
iOS. Also tried with pythonista and ZIMply but it uses Cython so it didn't work.

**Comment by kelson42** [comment]
@BeniCydia I have moved your request about html export in #180

**Comment by kelson42** [comment]
@BeniCydia I don't understand why you need this. What would be exactly the use case?

**Comment by kelson42** [comment]
@BeniCydia You need to have an HTTP server running or a PDF export because this would allow you to display on the video project (from a computer) a full article? Do I understand properly? If "yes" why not connecting your iPad directly to the video projector? I just try to fully understand.

**Comment by BeniCydia** [comment]
It just would be a very nice feature.

**Comment by kelson42** [comment]
I have created #182 for the hotspot mode, but for the rest I don't understand the reason behinf this ticket. Closing it.
