### ISSUE TITLE
Port Kiwix for iOS on Macos

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#184]
* Same code base
* Full featured reader on MacOS
* Less maintenance

**Comment by kelson42** [comment]
@automactic What is your opinion on this? Is this doable? How much work would be needed?

**Comment by kelson42** [comment]
@automactic You told me last year it sounds feasible meanwhile. You confirm?

**Comment by rgaudin** [comment]
At least regular ios version should work on M1 computer now

**Comment by kelson42** [comment]
@rgaudin @automactic I hope we are talking about the same thing: https://developer.apple.com/mac-catalyst/

**Comment by rgaudin** [comment]
catalyst is to support it in all macs. I'm just saying that M1 (new) computers now already support regular ios apps.

**Comment by kelson42** [comment]
Done with version `3.0.0` currently on Testfligh
