### ISSUE TITLE
VIdeo don't play properly on macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#189]
Even recent one which play properly everywhere else https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2019-09.zim

**Comment by kelson42** [comment]
@automactic To me, maybe most important problem to fix on macOS

**Comment by rgaudin** [comment]
See openzim/youtube/issues/40

**Comment by kelson42** [comment]
@automactic Does that problem has been tackle with your last revamp?

**Comment by rgaudin** [comment]
Fixed see [youtube compat](https://github.com/openzim/youtube/wiki/Compatibility)
