### ISSUE TITLE
Fully support ATS (use https across app)

### ISSUE THREAD

**Issue by automactic** [kiwix/apple#19]

**Comment by automactic** [comment]
When downloading, I encountered this error:
```
Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSErrorFailingURLStringKey=http://mirror3.kiwix.org/zim/vikidia/vikidia_en_all_2016-06.zim, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLKey=http://mirror3.kiwix.org/zim/vikidia/vikidia_en_all_2016-06.zim}
```

While I did use https://download.kiwix.ord/... as the file url, it redirect to a http url, cause download to be blocked by ATS.
@kelson42 Request that all sub domain under kiwix.org support https!

**Comment by automactic** [comment]
As of build 926, ATS is enabled with the exception of kiwix.org and its subdomains.

**Comment by automactic** [comment]
In build, ATS was turned off, because some of the download was redirected to http://ftpmirror.your.org. In order for download to work smoothly. ATS will be turned off for now.

@kelson42 Please switch all downloads & library.xml to https ASAP. Starting Jan 1st 2017, all apps will be required to use HTTPS only. [source](https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/)

**Comment by kelson42** [comment]
@automactic 
I have switched on https://download.kiwix.org/ but I can not control the mirrors. www.kiwix.org will be swtiched to https during the summer.

**Comment by automactic** [comment]
@kelson42 Thanks for the effort!

**Comment by kelson42** [comment]
@automactic We still have a few HTTP mirrors and this is not something I really want to fully remove. What is the current status on this? Can we at least have an exception for http://mirror.download.kiwix.org/ ?

**Comment by automactic** [comment]
The current status on this topic is the whole `kiwix.org` and subdomains are added as ATS exception. And there are no plan to make changes to this.

**Comment by kelson42** [comment]
@automactic The full list of current mirrors is available here:
https://download.kiwix.org/mirrors.html

I had a check again to see if we had other mirrors in HTTP and we do. I see:
* http://mirror.isoc.org.il/pub/kiwix/
* http://wiki.mirror.tn/

@automactic Could you please add them to the white list?
