### ISSUE TITLE
entry.h file not found

### ISSUE THREAD

**Issue by MikeBenton2** [kiwix/apple#191]
Hey y'all,

So I recently forked this project to work on an issue, but I was unable to build the project due to a file not being found, entry.h. Any ideas on a fix? I couldn't find this file in the project at all. 

![Screen Shot 2019-10-27 at 10 07 23 AM](https://user-images.githubusercontent.com/49599249/67636851-b2d1e000-f8a2-11e9-88d2-0f26d3a90569.png)

**Comment by kelson42** [comment]
@rgaudin @automactic I guess this is the `entry.h` of the Kiwix library... but maybe the `README.md` is not really clear about that?

**Comment by rgaudin** [comment]
Yes, please follow the *Building kiwix-lib* steps from [the README](https://github.com/kiwix/apple/blob/master/README.md#building-kiwix-lib) and you'll end-up with that file at `Shared/Dependencies/include/kiwix/entry.h`
