### ISSUE TITLE
Unable to download EPUBs in Gutenberg ZIM file

### ISSUE THREAD

**Issue by ghost** [kiwix/apple#193]
*@mikejab commented on Nov 5, 2019, 4:21 PM UTC:*

Hi

I am running IOS 13.2 and kiwix 1.1 on XR 256gb

Downloaded Project Gutenberg 57.32 gb zim.

When I try to download (red down arrow above cpu looking box) nothing happens. If I copy I get something like
kiwix://b85a521d-ac99-2d25-1282-aa7456ecf9dd/I/Pride%20and%20Prejudice.1342.epub
But this is not openable.

This is likely a substantial bug for the iOS version as I have done the following without change

Reinstalled IOS clean
Redownload zim multiple times
Tried on my wife’s XR phone.
Installed most book reader apps

I have reached out in the past but did not get assistance.

Can you assist?

Mike
5123061509

Sent from my iPhone

*This issue was moved by [kelson42](https://github.com/kelson42) from [openzim/gutenberg#92](https://github.com/openzim/gutenberg/issues/92).*

**Comment by kelson42** [comment]
@mikejab This is a bug in the Kiwix iOS app. This needs to be fixed and a new release done.

**Comment by mikejab** [comment]
Any progress on this?

**Comment by mikejab** [comment]
No update and no response to my prompt for progress 9 days ago? Ok. I’ll reach out to PG leadership about this important issue.

**Comment by mikejab** [comment]
Have reached out to Ann Wingate (PG coordinator) who will help me get my concerns to the PG board

**Comment by kelson42** [comment]
@mikejab I hope that this bug can be fixed in next version by @automactic, but this is up to him. I also guess that this specific problem will disappear in a further version of the Gutenberg ZIM file as we will probably provide a javascript based EPUB reader within the ZIM file itself.

**Comment by mikejab** [comment]
Well never mind.

**Comment by mcardigan** [comment]
Is it possible to request some activity?

**Comment by kelson42** [comment]
@mcardigan You do request... but that does not help to fix anything :)

**Comment by automactic** [comment]
@kelson42 What is your opinion on this? This seems like a very rare use case. I mostly use wikipedia zim files and I have not seen any zim file advertise user the ability to export data.

Should user be able to save destination of urls to the files app? What kind of urls are expected to be save-able?

**Comment by kelson42** [comment]
We have more and more ZIM files with PDF, EPUB or DOCS. The appropriate behaviour is that if someone clicks on one of these items and Kiwix can not read it directly, then it proposes to open with adequate app or save the file on the fs.

**Comment by automactic** [comment]
OK, yeah. I think this should be implemented with the system level "quick look" UI

**Comment by kelson42** [comment]
@automactic Thank you. You have many small Gutenberg ZIM files at https://download.kiwix.org/zim/gutenberg/

**Comment by kelson42** [comment]
We have the same problem with PDF and this other kind od zim file (which has epub as well BTW) http://download.kiwix.org/zim/other/lesbelleshistoires_fr_2020-05.zim

**Comment by kelson42** [comment]
Newly testing this, it seems PDF is rendered within Kiwix itself now (seems good to me) but the problem with epub (and other file types) is still here.

**Comment by kelson42** [comment]
@BPerlakiH Could you please have a look at some point to this issue?

**Comment by kelson42** [comment]
Actually the code should probably be generic: it goes here of the handling of any mimetypes which can not be displayed properly in Kiwix.

**Comment by BPerlakiH** [comment]
Please see it implemented here:
https://github.com/kiwix/kiwix-apple/pull/727
