### ISSUE TITLE
Kiwix for macOS DMG is not installable anymore

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#199]
kiwix-desktop-macos_2.0.dmg from https://download.kiwix.org/release/kiwix-desktop-macos/kiwix-desktop-macos_2.0.dmg can neither be installed on High Sierra or Catalina. It looks like the certificate is not valid anymore or something similar.

**Comment by automactic** [comment]
@kelson42 I think you have verified that the new version (2.1) I have uploaded for testing can be installed without a problem, correct?

**Comment by kelson42** [comment]
@automactic Yes it was working. Waiting to the official release and you giving me the DMG to close the issue. Similar thing for the ticket about notarizing.

**Comment by kelson42** [comment]
To be tested again with 2.1 dmg.
