### ISSUE TITLE
wikipedia_en_all_nopic_2019-12.zim erroneously reported as having images

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#211]
See screenshot:
![apple library](https://user-images.githubusercontent.com/21675885/71804858-feec8e00-3064-11ea-8471-409ef6cba77c.jpg)

**Comment by rgaudin** [comment]
Looking at http://library.kiwix.org/wikipedia_en_all_nopic/M/Tags, it says `_pictures:no` so I guess this is related to https://github.com/kiwix/apple/issues/169 not being implemented.

**Comment by automactic** [comment]
With the integration of new OPDS APIs, this issue should already have been resolved, please open new ticket if any zim file property was found to be wrong
