### ISSUE TITLE
Online library seems to be stuck with older versions of zim files

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#216]
From user:
Last version of ``wikipedia_zh_top_maxi`` is indicated as June 2019 whereas the last available version on download.kiwix.org is from January 13, 2020:

![attachment](https://user-images.githubusercontent.com/21675885/73527133-d01ec900-4412-11ea-9c16-30fb94e5ab59.jpg)

Likewise, ``wikipedia_zh_all_maxi`` and ``_nopic`` are shown from 2018 whereas the most recent updates are from October 2019/January 2020

![attachment-1](https://user-images.githubusercontent.com/21675885/73527137-d14ff600-4412-11ea-8a9b-0153dbc15fe8.jpg)

**Comment by kelson42** [comment]
@Popolechien I see the right version on my iPad. You have probably forgotten to refresh it (swap down).
