### ISSUE TITLE
Share ZIM files with Airdrop

### ISSUE THREAD

**Issue by diamondsea** [kiwix/apple#224]
Sharing installed ZIM files with other iOS devices over Airdrop would save a lot of time and allow files to be distributed in the event of Internet outages.

**Comment by automactic** [comment]
You can already do this with the files app. Go to "On My iPad" -> "Kiwix", choose a file and share it with others.

It is true that it would be great if one could share in the app directly. But given there is already a way to do this, adding a share button in app is not very high on my to do list at the moment.
