### ISSUE TITLE
Bookmark side pane is always visible

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#225]
At the start of the app this is shown, it should be shown only if we explicitly ask to show it.

**Comment by rgaudin** [comment]
Please specify whether macOS or iOS…

**Comment by automactic** [comment]
The behavior in iOS app v 1.11 is: 

1. When launching the app in full screen,
- if landscape, the bookmark / outline side panel is displayed side-by-side with the welcome view
- if portrait, the bookmark / outline side panel is hidden, only the welcome view is visible
Note: rotating also have kinda similar behavior

2. When side panel's display mode is also different,
- if landscape, the side panel is side-by-side with the welcome / article view
- if portrait, the side panel is overlaying on top of the welcome / article view

I don't find this behavior annoying, but I can certainly tweak it if you if you do.

So the new behavior is going to be:

- When app launch, side panel is going to be not visible.
- When toggling the side bar, the side bar is still going to be overlap in portrait and side-by-side in landscape (I do want to make this customizable at some point)
- When rotating the screen, if the side bar is visible, it is still going to be visible

**Comment by kelson42** [comment]
@automactic tx, sounds good to me. please put in the merge comment “fixes #xyz” to automatically xlose related ticket at merge time.

**Comment by automactic** [comment]
@kelson42 remember this? I have to make the side panel visible on iPad when app was launching in landscape due to what I believe is a system bug. This is the only way I can get layout to work correctly with what UIKit provides.

On iOS 13, user will still see side panel closed no matter in which device orientation they launch the app. Hope this is ok with you!

**Comment by kelson42** [comment]
With last testfligh this side pane always reapared after resuming the app.

**Comment by automactic** [comment]
yeah I know. I am seeing this as well. Those splitview APIs are a really pain to work with...

**Comment by automactic** [comment]
I have created a fix, tested on my device and it works. It is going to be in the next beta. Please check when it comes out

**Comment by kelson42** [comment]
Works fine now. Thank you.
