### ISSUE TITLE
Version 1.11 iOS Dark Mode Issue

### ISSUE THREAD

**Issue by PsamatheM** [kiwix/apple#229]
Search page display using downloaded WikiVoyage is mostly unreadable (dark txt on a dark background). See attached screenshot
![IMG_1623](https://user-images.githubusercontent.com/56350868/77158179-af7e0180-6a9a-11ea-9cfa-98cb5cd94503.PNG)

**Comment by Pesh4ng** [comment]
Have they responded yet? The comment section is not showing.

**Comment by automactic** [comment]
Hey, thanks for reporting. I have updated my code to fix this issue. It will go out to users in the next release
