### ISSUE TITLE
Update application logo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#230]
There is a new, slightly remodeled logo for Kiwix 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.png
The app's icon needs to be updated accordingly

**Comment by automactic** [comment]
Hi, can you give me at least 1024x1024px image? Or better, a vector image?

**Comment by kelson42** [comment]
@automactic yes, here is the corresonding SVG https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg

**Comment by kelson42** [comment]
I tested again with last testflight version. I had still the bug... but after testing further and reinstalling again, it seems to have vanished. So looks good :) Thx.

**Comment by automactic** [comment]
The macOS logo is using the version with the glowing white outline. Do you wish it to be updated as well?

**Comment by Popolechien** [comment]
Yup.

**Comment by automactic** [comment]
Could you provide a vector version of the icon with glowing outline?

**Comment by automactic** [comment]
I haven't got a vector version of the macOS app icon with glowing outline yet. If we don't have one, we could go with either a) not change the macOS app icon b) use the same rounded rect icon as the iOS version

I am going to choose one of these approach and call this done if I didn't hear any objections / feedback by end of this week

**Comment by Popolechien** [comment]
Yeah go ahead, I totally skipped it, sorry. It'll be there for the next next release :-)

**Comment by automactic** [comment]
> It'll be there for the next next release

Do you mean we still want to use the glowing outline icon on macOS, but we don't have a new version now and it will be available in the future?

**Comment by Popolechien** [comment]
Well let us see how the "normal" icon looks, and then if it's not that great we'll replace it with an updated glowing one in due time.

**Comment by Popolechien** [comment]
@automactic @kelson42 @rgaudin Any preference?
[Icon-Kiwix-MacOS-test1.pdf](https://github.com/kiwix/apple/files/4757143/Icon-Kiwix-MacOS-test1.pdf)

**Comment by rgaudin** [comment]
I prefer 1. and 2. and I like 4. as well but maybe there are guidelines or design principles that should guide the decision beyond just personal preferences?

**Comment by siemsie** [comment]
I've looked through here... https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by siemsie** [comment]
[Kiwix-Icon-MacOS X.zip](https://github.com/kiwix/apple/files/4791250/Kiwix-Icon-MacOS.X.zip)
Morning! Here is the MacOS icon in png (2 larger sizes as per developer link above) and svg. Let me know if ok/if you need anything else from me. Thanks :)

**Comment by automactic** [comment]
updated app icon in #286
