### ISSUE TITLE
Kiwix’s dark mode feature is not working properly in the latest version ( kiwix version 1.11v) (IOS 13.3)

### ISSUE THREAD

**Issue by Peshang0x** [kiwix/apple#231]
Hello kiwix team! 
I just updated kiwix and saw the new dark mode feature and i think it isn’t working properly: 
-the text below the main search results are black which makes it illegible on a dark background.
-the actual pages still have a white background which makes the feature pretty useless i guess... 
I hope you fix them soon!

[here are the details with screenshots](https://imgur.com/a/4Fa3HkW)

**Comment by automactic** [comment]
I have fixed the search snippet issue in #237. Thanks for reporting, it will be included in the next release.

About the content -- the kiwix app is a viewer of zim files, it rely on the zim files to provide text, image and styling (how the text are positioned, color, etc.) So to display the articles in dark background with white text, the content provider need to support iOS 13 dark mode and they need to update their zim files. 

A simple analogy is when many desktop OS support dark mode, websites on the internet didn't suddenly gain the ability to switch to dark mode in day one. Many (Github for one) still don't have dark mode today. Each site needs to rework their styling to gain the ability to respect system dark mode setting and it takes time.

**Comment by kelson42** [comment]
First part has been fixed and second part is a duplicate of #516
