### ISSUE TITLE
Kiwix’s dark mode feature is not working properly (1.11v)

### ISSUE THREAD

**Issue by Pesh4ng** [kiwix/apple#232]
Hello kiwix team! 
I just updated kiwix and saw the new dark mode feature and i think it isn’t working properly: 
-the text below the main search results are black which makes it illegible on a dark background.
-the actual pages still have a white background which makes the feature pretty useless i guess... 
I hope you fix them soon!
[here are the details with screenshots](https://imgur.com/a/4Fa3HkW)

**Comment by automactic** [comment]
Closed, because it is a duplication of #231
