### ISSUE TITLE
Font size cannot be memorized

### ISSUE THREAD

**Issue by Saknralin** [kiwix/apple#233]
I updated the Kiwix app on my iPhone and found the font size can ONLY be applied to the page I was currently reading. Each time I searched or clicked another item, the font size would go back to 100% for the new pages. This APP used to memorize the font size for all the pages, and now it is getting really frustrated since I need to constantly adjusting the font size to 150% when reading a new page. Could you fix this problem in the next version?

Here is the detailed information of my user environment:

Device: iPhone 8 plus
System: iOS 13.3.1
Kiwix version: v1.11
Library: Wikipedia (with pictures, English version)

**Comment by automactic** [comment]
Thanks for reporting. I have submitted a fix and it will be deployed in the next release.
