### ISSUE TITLE
Version 1.11 crashes on startup on iOS 11.4.1

### ISSUE THREAD

**Issue by yellowcrash10** [kiwix/apple#235]
Greetings! I just updated the Kiwix app to version 1.11 on my iPhone SE running iOS 11.4.1, and the app now crashes immediately upon opening it. Reinstalling the app produces the same result.

**Comment by anonblahacco** [comment]
Just wanted to pitch in that I'm having the exact same issue on an iPhone 6 running iOS 12.4.6.

**Comment by kelson42** [comment]
@automactic Do you believe this could be fixed with 1.11.1?

**Comment by automactic** [comment]
No it needs investigation.

**Comment by Erve1309** [comment]
Hi,
Would it be possible, as a temporary solution, to modify the AppStore so that IOS 11 and IOS 12 users download v1.7.1 instead of v1.11 ?

**Comment by automactic** [comment]
AFIAK App Store does not allow us to use separate versions for different OS. (I wish it did tho)
