### ISSUE TITLE
iOS No sound crashcourse videos

### ISSUE THREAD

**Issue by CyberGoat** [kiwix/apple#236]
No Sound from videos while using crash course zim on ios ver 13.4.1 - can play music 

Hardware: iphone SE 2020

Thank you for all your efforts

**Comment by kelson42** [comment]
@CyberGoat Thank you for your bug report. This is a duplicate of #144. The fix is in the ZIM. Crashcrouse is one of the last one we don't have renewed so far, but a new version is currently computed. Will be published in the next weeks.

**Comment by CyberGoat** [comment]
> @CyberGoat Thank you for your bug report. This is a duplicate of #144. The fix is in the ZIM. Crashcrouse is one of the last one we don't have renewed so far, but a new version is currently computed. Will be published in the next weeks.

Thank you for all your work love the app!
