### ISSUE TITLE
App Localization

### ISSUE THREAD

**Issue by automactic** [kiwix/apple#24]
We need to translate our app to other languages! 🌏🌍🌎
1. create localization files
2. put it on translatewiki.net to translate
3. import translated localizations to app (this works automatically via PR)

<s>4. Make app store versions and screenshot for newly translated apps</s> Moved to dedicated issue #535

**Comment by martin8032** [comment]
I support this request and could provide the German translation.

**Comment by rgaudin** [comment]
Just setup an iPadAir 5th using French and got Kiwix all in English. Wasn't sure if Kiwix iOS is localized or not and this 6yo+ ticket is not really helping 😉

Bump-up if it's not yet l18n'd

**Comment by kelson42** [comment]
@automactic With version 3.0.0, do we have all string in one dedicated json/xml/... file, so it is then easy to translate? This sounds like a priority now.

**Comment by kelson42** [comment]
We have done that many times for other software piece, guidance can be provided.

**Comment by kelson42** [comment]
First task here is to implementation proper support in the app, see https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions. "lproj" files seems to be supported.
