### ISSUE TITLE
ZIM favicon lost after library update

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#243]
Started downloading a ZIM file (basketball_fr) from the library and while the download continues, I updated the library.

ZIM favicon was then replaced with generic ZIM icon instead of the basketball icon.

![IMG_B842A643FAF5-1](https://user-images.githubusercontent.com/57929/80813803-3f46bd80-8bba-11ea-88a3-6d613f916edf.jpeg)

**Comment by kelson42** [comment]
I have this behaviour as well and it even crash for me.

**Comment by kelson42** [comment]
Hmmm, I can not reproduce the crashes now.

**Comment by automactic** [comment]
good catch, gonna take a look over the weekend

**Comment by automactic** [comment]
The root cause is the OPDS xml doesn't have favicon data, and I programmed for user triggered updates to overwrite existing property (like a forced refresh).

I changed to only update optional properties if there is a new value.

**Comment by automactic** [comment]
The fix will be deployed in the next patch release

**Comment by kelson42** [comment]
> The root cause is the OPDS xml doesn't have favicon data, and I programmed for user triggered updates to overwrite existing property (like a forced refresh).

Kiwix Desktop for Linux/Windows displays the icon, so I guess somehow there is a way with OPDS.
