### ISSUE TITLE
Links between zim files

### ISSUE THREAD

**Issue by cannyboy** [kiwix/apple#249]
I downloaded the latest version of Kiwix (2.1.3) for macOS and also the latest full Wikipedia and Wiktionary zim files.

I was expecting them to work together - for instance clicking a Wikipedia link in Wiktionary page would just open the Wikipedia page in Kiwix. (..and the reverse)

But instead it opens the actual webpage (if the internet connection is active), or nothing (if no internet connection). So how do I get links between zim files working? Is this not currently a feature, or is there a setting somewhere?

**Comment by automactic** [comment]
We don't support this at the moment, however I have raised similar points earlier inside #27. cc @kelson42 as a feature request.

I personally think this would be nice to have, but not an easy problem to solve technically

**Comment by automactic** [comment]
While what this issue is advocating for is a very cool idea, it remains largely inspirational at this moment. It would also require a lot of work and technical challenge to be overcome.

Thanks for your suggestion, but I have to close it as won't do in the foreseeable future.

**Comment by cannyboy** [comment]
What are the technical challenges involved? I haven’t looked at the code, but wouldn’t it be a case of registering a url scheme with each zim file ( en.wikipedia.org for the English wiki, for instance ) and then if that url scheme is linked from another zim (wiktionary for instance), then redirecting to the Wikipedia zim instead of the actual site.
