### ISSUE TITLE
Add ZIM description in details view

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#254]
The library is very comfortable to use and pick a content but I see no reason for not displaying the ZIM description in the details view.
Given some ZIM files are dozens of GB large, the title might not be enough to make a decision.

**Comment by automactic** [comment]
I have thought about this. The thing is -- it is hard to fit an arbitrary long text into the single zim file detail view, which consists either actions or key-value like properties. A new UI component might need to be invented for displaying the description. 

I personally don't think the description provides much more useful info than what we already display. For example, the chemistry focused Wikipedia, the description "A selection of Wikipedia articles on chemistry" is basically saying the same thing as title "Chemistry by Wikipedia"; the description "From Wikinews, the free news source you can write!" provides little additional insight than "Wikinews" (it is more like a tagline or a promo text). 

It would certainly be nice to show descriptions, but given above, it is unlikely to be my priority right now. I am certainly curious to learn how other might find descriptions useful

**Comment by rgaudin** [comment]
I know that many descriptions are meaningless right now, especially for the wikis, because those were sorta-automatically added in batch for the zimfarm.

Some ZIMs do include meaningful ones and that's definitely where we want to go. Keep in mind that Wikis are so broad that even a real author would have difficulties writing a meaningful couple-sentences for it. 

By not displaying them, you're saying descriptions are useless and there's no need to write proper ones because nobody will ever see them while showing them would create an incentive to improve them :)

I'm in favor of keeping this ticket open although not a priority. @kelson42 ?

**Comment by kelson42** [comment]
Yes,description are important. They shoul be visibleto users in away or an other.

**Comment by automactic** [comment]
@rgaudin From a UI/UX perspective, how would you propose the description to be displayed?

**Comment by rgaudin** [comment]
That I don't know !

I think it's important to have it when considering a download, so a *block of text* after the first important-info metadata seems to make sense.

As you mentioned, it would be arbitrarily long so that's something to consider. Maybe a max-height like box with an inner scroll? No sure what the guidelines are…

![IMG_0B76F377F67E-1](https://user-images.githubusercontent.com/57929/82309077-2dcf2500-99b2-11ea-91a4-5b71cdac45a8.jpeg)

**Comment by automactic** [comment]
Description is added in iOS version 1.14.3, currently in review and to be released soon

![image](https://user-images.githubusercontent.com/8294252/132999912-f7b53d45-e538-421d-b9f9-31f2547c7360.png)

**Comment by kelson42** [comment]
Nice!
