### ISSUE TITLE
Language filtering by A-Z is odd

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#256]
Not sure if it's a bug or just an unexpected behavior but looking at Wikipedia entries in the library, the languages list by count works as expected but the alphabetical one doesn't.

* The list of languages, sorted alphabetically, isn't always the same. Looking at the list, exiting this view and coming back brings a different list/ordering. Toggling between *byCount* and *A-Z* restores a *somewhat proper* ordering.
* Looking for language `Bambara` (`bam`) and it's not in the Bs… It seems like there are several A-Zs list appended together.

![IMG_4368](https://user-images.githubusercontent.com/57929/82045980-8b582e80-969f-11ea-9b4a-509d3516bc41.PNG)

**Comment by automactic** [comment]
Hmm, yeah there does seem to be something not totally right. lemme take a look

**Comment by automactic** [comment]
Fixed, please test it out when the next build is released, which should be soon
