### ISSUE TITLE
Logos are mixed up in search results view

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#263]
![DDD59205-A612-413D-91B7-758BB9C8053F](https://user-images.githubusercontent.com/1029718/82883105-4c996280-9f42-11ea-9a55-649f38e0467f.png)

You see for example the basketball logo for a lot of results which are not basketball related.

**Comment by automactic** [comment]
Hmm can you consistently reproduce this, or does it seems random? Could you also go into the library to check if on device zim file icons are displayed correctly?

I downloaded these exact zim files (or as similar as I could find), and cannot reproduce the problem. 
<img width="1112" alt="Screenshot 2020-05-31 at 6 13 48 PM" src="https://user-images.githubusercontent.com/8294252/83363857-c7131980-a36a-11ea-930e-08bd14bfe62b.png">

**Comment by kelson42** [comment]
I was able to reproduce the bug but not sice I have removed all the files and get last version in Testflight. I strongly suspect here, the code was wrong at some time in the testflight... and then the pictures were simply cached wrongly.
