### ISSUE TITLE
Search context/highlight not showing 

### ISSUE THREAD

**Issue by baaaaaaaaaaaaaam** [kiwix/apple#264]
On latest public build, the search context/highlight is not showing on MacOS (see attached for how it should look).  The full text search does work, so the ZIM files have FTS indexes, but all that shows up is the icon and title result (see attached).  Have tried with multiple ZIMs.

Is there a reason for this?
![82883105-4c996280-9f42-11ea-9a55-649f38e0467f](https://user-images.githubusercontent.com/1443666/82910529-bad92780-9f38-11ea-8993-bc4ae7ba211a.png)
![Screen Shot 2020-05-26 at 10 10 02 AM](https://user-images.githubusercontent.com/1443666/82910721-f8d64b80-9f38-11ea-8fea-4fb269b483b9.png)

**Comment by automactic** [comment]
Nope there isn't a particular reason.

I know the Mac version isn't showing snippets when it should. It will be updated when the next version comes out

**Comment by automactic** [comment]
I added search result snippet in #303. It will be included in the next version of the macOS app
<img width="1348" alt="Screen Shot 2020-08-14 at 8 40 20 PM" src="https://user-images.githubusercontent.com/8294252/90301639-2e6f3e80-de6f-11ea-859d-7230400651ee.png">
