### ISSUE TITLE
Some wikipedia articles are not shown by Kiwis for iOS v. 1.12

### ISSUE THREAD

**Issue by manfred512** [kiwix/apple#265]
I did some research on issues with Kiwix 1.12 for Wikipedia.
We do use 2 iPods  (7. Generation).
Both are on iOS 13.5.
Both use German Wikipedia 39.27 GB from 11. May 2020
One runs Kiwix for iOS v. 1.11.1.
I have not detected any issue.
The other runs Kiwix for iOS v. 1.12.
Articles about states such as Germany, France, Italy, USA are not found.
Articles about states such as Hawai, Iceland, Tahiti work properly.
The difference between the 2 groups ist he length oft he article in Byte!
It only works properly if it is smaller than 100 000 Bytes.

**Comment by automactic** [comment]
Hey, could you provide me with the zim files you are using (like `wikipedia_en_all_nopic_2020-04.zim`) and the search term you used to help me reproduce the issue?

**Comment by manfred512** [comment]
Hello,

 

I would like to provide You with all the information possibly needed:

 

The device I use is an iPod touch 7. Generation running with iOS13.5.

I run Kiwix for iOS v 1.12, snippets disabled.

The zim-file I use is wikipedia_de_all_maxi_2020_05.zim.

When for example I search for „Deutschland“ the result is like shown on pictures IMG_0111.PNG and IMG_0112.PNG.

When I search for „Frankreich“ the result ist like shown on pictures IMG_0113.PNG and IMG_0114.PNG.

 

On our other iPod touch 7. Generation with iOS 13.5 and the same zim-file but as a difference with Kiwix for iOS v 1.11.1 everything works correctly.

 

On our desktop Computer with Windows 10 and kiwix-desktop_windows_x64_2.0.1-1  with the same zim-file everything works correctly too.

 

That is the reason why I think there should be an issue in Kiwix v. 1.12.

 

Best regards

Manfred

 

Von: ChrisLi <notifications@github.com> 
Gesendet: Montag, 1. Juni 2020 00:26
An: kiwix/apple <apple@noreply.github.com>
Cc: manfred512 <dmbiol@online.de>; Author <author@noreply.github.com>
Betreff: Re: [kiwix/apple] Some wikipedia articles are not shown by Kiwis for iOS v. 1.12 (#265)

 

Hey, could you provide me with the zim files you are using (like wikipedia_en_all_nopic_2020-04.zim) and the search term you used to help me reproduce the issue?

**Comment by automactic** [comment]
@manfred512 Hey, I have added back the old title + indexed search logic. It will be included in the next release. Make sure to upgrade your app when it comes out!

I have downloaded `wikipedia_de_all_maxi_2020_05.zim` and tried out some of the example search text you provided on the upcoming version of the app. (Also sorry I cannot see images you uploaded in your email reply) Please see results below:

![Screenshot 2020-06-09 at 9 51 05 AM](https://user-images.githubusercontent.com/8294252/84155818-cb0ffd00-aa36-11ea-8b91-0a69442f6ae8.png)
![Screenshot 2020-06-09 at 9 50 42 AM](https://user-images.githubusercontent.com/8294252/84155822-cba89380-aa36-11ea-9b13-9c6ea61d7e5f.png)
![Screenshot 2020-06-09 at 9 50 06 AM](https://user-images.githubusercontent.com/8294252/84155825-cc412a00-aa36-11ea-802c-d49acbc99c4d.png)

**Comment by manfred512** [comment]
Hi Chris,

 

I’m looking forward this new version and will update asap.

 

Thank You.

Manfred

 

Von: ChrisLi <notifications@github.com> 
Gesendet: Dienstag, 9. Juni 2020 15:52
An: kiwix/apple <apple@noreply.github.com>
Cc: manfred512 <dmbiol@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [kiwix/apple] Some wikipedia articles are not shown by Kiwis for iOS v. 1.12 (#265)

 

@manfred512 <https://github.com/manfred512>  Hey, I have added back the old title + indexed search logic. It will be included in the next release. Make sure to upgrade your app when it comes out!

I have downloaded wikipedia_de_all_maxi_2020_05.zim and tried out some of the example search text you provided on the upcoming version of the app. (Also sorry I cannot see images you uploaded in your email reply) Please see results below:

 <https://user-images.githubusercontent.com/8294252/84155818-cb0ffd00-aa36-11ea-8b91-0a69442f6ae8.png> 
 <https://user-images.githubusercontent.com/8294252/84155822-cba89380-aa36-11ea-9b13-9c6ea61d7e5f.png> 
 <https://user-images.githubusercontent.com/8294252/84155825-cc412a00-aa36-11ea-802c-d49acbc99c4d.png>

**Comment by automactic** [comment]
@manfred512 Have you tried version 1.13 of the iOS app?

**Comment by Popolechien** [comment]
@automactic He sent an email saying that everything was back in order, with one caveat: 

Searching for „Bundesrepublik Deutschland“ [presumably on de_all_maxi] leads to the correct article „Deutschland“.
Searching for „Deutschland“ leads to the result below.
![ie5-FWvaeCpBf_sn6vRJLhq59DPGxZ2mxw](https://user-images.githubusercontent.com/21675885/85101005-b6372480-b201-11ea-8353-b78bbb745318.jpg)
![30b9hja6sAD2smM4NqypLRuq_tFOdxx23w](https://user-images.githubusercontent.com/21675885/85101007-b6372480-b201-11ea-8bc3-9d04f76e577a.jpg)

**Comment by automactic** [comment]
> Searching for „Bundesrepublik Deutschland“ [presumably on de_all_maxi] leads to the correct article „Deutschland“.
Searching for „Deutschland“ leads to the result below.

Is this saying if there is an article whose title match 100% with search query but article does not show up?

**Comment by Popolechien** [comment]
Looks very much like it.

**Comment by automactic** [comment]
Well, there are not too much else I can do about it. One thing that might help is if @kelson42 could restore old `searchSuggestionSmart` by matching case insensitive prefix instead of using xapian title search (if it is indeed changed)

**Comment by kelson42** [comment]
> Well, there are not too much else I can do about it. One thing that might help is if @kelson42 could restore old `searchSuggestionSmart` by matching case insensitive prefix instead of using xapian title search (if it is indeed changed)

No, the xapian title index should be used.
