### ISSUE TITLE
app should be able to use local zim first when loading external resource

### ISSUE THREAD

**Issue by automactic** [kiwix/apple#27]
When opening external link in an article, if user have zim file containing the offline version of the external link. App should know to open the locally stored resource, instead of loading from Internet.

**An Example:**
Say user is browsing the Montesquieu article in **WikiQuote** zim file, there happens to be a external link, linking to Montesquieu's **Wikipedia** page.
- how it is handled now: App open the external link using SFSafariViewController.
- it would be great if app could do this:
  - see if user has zim file that offline the domain of the external link (en.wikipedia.org)
  - see if zim file has that article (check against the relative URL)
  - load article from zim file or fall back to loading from Internet

**Comment by kelson42** [comment]
Yes, I agree on the feature request. On my side I do not know how to resolve agnosticaly that problem.

**Comment by automactic** [comment]
A proposed approach: add `associatedDomains` array to zim files.

Example:

**Comment by automactic** [comment]
This ticket is a discussion / proposal (that hasn't had any actions or updates for a long period of time). Closing it as nothing needs to be fixed or done.
