### ISSUE TITLE
Kiwix macOS 2.0.9 crashes when search is initiated on maxi but not on nopic

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#270]
Typing any letter in the search bar to look for a word immediately causes Kiwix to crash and close. Same issue appears with wiktionary_en_simple_all_maxi_2020_05, wiktionary_de_all_maxi_2020_05 and wiktionary_es_all_maxi_2020_05

But doing the same thing with nopic zim files (e.g. wiktionary_en_all_nopic_2020_05 or wikivoyage_fr_all_nopic_2020_05) causes no issue whatsoever.

**Comment by automactic** [comment]
Could you try version 2.1? Issue on a older version won't be fixed.

**Comment by Popolechien** [comment]
Looks fixed \o/ 

Wrong logo though, but that's a ticket for another day.
