### ISSUE TITLE
There needs to be a more recent snapshot of regular Wikipedia WITH pictures

### ISSUE THREAD

**Issue by PessiPanto** [kiwix/apple#272]
I really need the latest (like March at least) regular Wikipedia with everything, including all the pictures. I don’t care if it’s over 100gb, I really, _really_ _**need**_ it. 

But in the downloads place there isn't a regular Wikipedia with pictures that’s recent, the most recent one with pictures is from all the way back in 2018. 400,000,000 new articles have been created since then, many which are very important. We need a snapshot with pictures from March at the very least.

**Comment by automactic** [comment]
> I really, really need it.

Yeah we all do. Please read [this](https://www.kiwix.org/en/whats-wrong-with-the-english-wikipedia/) on a more detailed explanation.

If you know, you can help us out by resolving some issues in https://github.com/openzim/mwoffliner/issues
