### ISSUE TITLE
macOS: Allow file downloads

### ISSUE THREAD

**Issue by adrian-fro** [kiwix/apple#274]
I have already seen a similar issue for the iOS Kiwix, but no mention there about the same problem in macOS Kiwix version 2.1.3 running under macOS 10.14.6

So I had to open a new issue about the macOS Kiwix. 
If I click on the download icon (see the screenshot attached), then no file (EPUB or in any other format) is downloaded. 
I would also like to decide myself, into which folder such a downloaded file should go, but this is rather cosmetic.

I do not know, if I should be very optimistic, as the parallel problem for iOS has dragged on for quite a while, and then *it died out* instead of *being solved*. 
Still, I hope that some pople at least will try to help with the present issue. 
Thank you
<img width="668" alt="Screenshot 2020-06-09 at 17 30 13" src="https://user-images.githubusercontent.com/51302224/84178475-611a4680-aa7c-11ea-8605-2049b8d5b420.png">

**Comment by rgaudin** [comment]
Renamed it as it is not specific to gutenberg: current version just has no download support. We have the problem with other ZIM serving files that can't be read inside the Kiwix app.

**Comment by kelson42** [comment]
Similar to https://github.com/kiwix/apple/issues/193 on iOS.

**Comment by kelson42** [comment]
Now that we have merged the codebase between iOS and macOS, this ticket is basically a duplicate of #193
