### ISSUE TITLE
iOS Search Results sent to wrong destination

### ISSUE THREAD

**Issue by CyberGoat** [kiwix/apple#277]
When I search on my phone the results and snippets are provided though the icon is for another database. When I click on it I get a white blank page. I believe it is confusing the source with another database. When I remove the database the icon relates to the app crashes. Then when I search again it is another database not related to the actual search result. Delete that icon’ed database and crash then it moves to another unrelated database. 

Sure wish there was a reindex search function/button.

**Comment by automactic** [comment]
@CyberGoat Does this happen consistently? Or randomly? What version of the app and what version of iOS are you using?

**Comment by kelson42** [comment]
@CyberGoat We struggle to reproduce the problem. Would you be able to give us more information please? Otherwise, we we will have to close the ticket.

**Comment by automactic** [comment]
Closing the issue due to inactivity
