### ISSUE TITLE
Major display issues with Russian wiktionary

### ISSUE THREAD

**Issue by ErinPo** [kiwix/apple#280]
All search result pages are 90% overlapped with a Creative Commons disclaimer which cannot be dismissed. Only opening the main page works without overlays, but then it fetches the desktop version which causes lots of horizontal scrolling. It seems the offline browser is not properly sending the mobile user agent.

[Screenshot](https://i.imgur.com/vNzRpKY.jpg)

**Comment by automactic** [comment]
@kelson42 I think this should be moved to https://github.com/openzim/mwoffliner
