### ISSUE TITLE
May 25 2020 Wikipedia download in iOS hangs in unrecoverable state after long enough

### ISSUE THREAD

**Issue by jonathanyhsu** [kiwix/apple#281]
When downloading the large May 25, 2020 Wikipedia image with kiwix on iOS, the download appears to stop or hang after a certain amount of time. If caught fast enough, Pause'ing and Resume'ing the download can cause it to continue. If not, the download enters a frozen unrecoverable state, where tapping on the Pause button appears to do nothing (the UI does not change it to Resume). This has happened around a dozen times for me now, and in various states of progress. Some as low as 10-15% complete, once it happened to me while it showed 100% download.

- I tried setting device screen lock time to Never and this phenomenon still occurs.
- I have also tried closing Kiwix by swiping up from the App selection interface, but this still occurs.
- I have tried downloading the file both via WiFi only and Wifi+Cellular.
- I have tried uninstalling and reinstalling Kiwix, but this still persists.
- This issue has also persisted over the course of several days.

My device and download info are:
Downloaded file: Wikipedia (39.85GB, May 25, 2020, 6.1M articles)
Downloaded file ID: f6aa1506
Device mode:  iPhone 11 Pro
Device OS: iOS 13.5.1
Kiwix version: 1.13

I would be happy to provide additional information if helpful.

**Comment by automactic** [comment]
When the app finish download a zim file, it moves it to the document dir. Then the file discovery mechanism takes over and mark the file as "on device". The issue here is the May 25 zim file is corrupted and cannot be opened. (The file itself is problematic and should not have been released) 

While the app could definitely do a better job and let user know there is a file, fully downloaded, but cannot be opened. It is so rare that we release a bad file, so the improvement of UX for "there is a bad file" will likely not happen anytime soon.

@jonathanyhsu Thanks for your very detailed report. I am fully aware of it and I have tried the May 26 file days after it is released. At this time, please use the Apr 10 file (that is what I did anyway).
@kelson42 I think I have communicated with you before the May 25 English Wikipedia file is broken. As a matter of fact, I just downloaded this file again on a windows machine and it cannot be opened by Kiwix for window either. Could you look into this?

**Comment by jonathanyhsu** [comment]
Thanks, I'll download the previous full version and see how that goes!

**Comment by automactic** [comment]
@Popolechien I am wondering if you could confirm the May 25, 2020, 39.85GB, Wikipedia zim file does not work on Android? I have confirmed it does not work on iOS and Windows

**Comment by Popolechien** [comment]
@automactic Well there is a 2020-06 version that got released yesterday. Should I check that one instead?

**Comment by automactic** [comment]
Oh, in that case, perhaps we should all try the new file instead. Downloading it now myself

**Comment by automactic** [comment]
No there isn't a 2020-06 version yet. I am talking about the around 39GB big file -- Wikipedia Engligh full text with no pictures. I am still seeing the May 25 file

**Comment by Popolechien** [comment]
@automactic Yeah Kiwix-serve does not update - see [#119](https://github.com/kiwix/web/issues/119)

**Comment by kelson42** [comment]
@automactic I can look but which file exactly are we talking about? Do you have an URL?

**Comment by mmcnl** [comment]
I had the same issue as @jonathanyhsu described, with the May 25th file. However I am also experiencing very similar behavior with the June 17, 2020 (40GB) zim file. It nearly finished but then got stuck. The Pause button is in the frozen state described above where pressing it appears to do nothing. I also tried twice to install the new (July 2020) 11G version of wikipedia and that also got stuck at 100%.

<img width="443" alt="Screen Shot 2020-07-05 at 3 25 23 PM" src="https://user-images.githubusercontent.com/1498727/86543483-e5bd8080-bed3-11ea-8483-d8ce320c550e.png"><img width="383" alt="Screen Shot 2020-07-05 at 3 26 00 PM" src="https://user-images.githubusercontent.com/1498727/86543485-e8b87100-bed3-11ea-8d88-62dee411dc88.png">

**Comment by jonathanyhsu** [comment]
I tried downloading the June 26 2020 image (95.08 GB, 6.1M articles, id=370bba84) using the iOS 1.13.1 Kiwix application, but the download froze at 73% completion. As before, hitting the Pause button in the UI doesn't seem to do anything, and I cannot resume the download either.

**Comment by jonathanyhsu** [comment]
I updated my iOS app to version 1.13.2 and the issue appears to be resolved. After the update, I somehow got the May 25 2020 image showing up in my Library and I can browse it for differences between it and my prior image. I also was able to successfully download the June 26 2020 image for three different images to browse. Deleting the extra copies didn't have any issues and I can still use the June 26 2020 image as a primary reference.

**Comment by automactic** [comment]
Thanks for the confirmation. Please use the June version and not the May version. AFIAK, there might be additional issue in the May version

**Comment by mmcnl** [comment]
@automactic I continue to experience what seems like the same issue. Using 1.13.2 of the Kiwis iOS app, my download of the June 17, 2020 40.07GB Wikipedia file stalled for hours at 87% and wouldn't continue, and the "Pause" button wouldn't do anything went pressed.

![IMG_2092](https://user-images.githubusercontent.com/1498727/87448326-8be24800-c5b0-11ea-9676-11401fb9a759.PNG)

![IMG_2093](https://user-images.githubusercontent.com/1498727/87448339-8f75cf00-c5b0-11ea-84a8-171c8d76cfec.PNG)

![IMG_2094](https://user-images.githubusercontent.com/1498727/87448345-90a6fc00-c5b0-11ea-82a5-4109e2d45bfd.PNG)
