### ISSUE TITLE
Kiwix does not recognize latest (2020-06) enwp zim file if it has simply been copied rather than downloaded

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#284]
From a user:

"When I copy (not re-download, just copy, so it is the exact same file) `wikipedia_en_all_maxi_2020-06.zim` to my iPad Air 3º Generation and to my iPhone XR, it does not show up in the list of “On Device” files, though other files such as Wikivoyage and Wiktionary do show up. Both are running the latest iOS and iPad OS versions."

**Comment by davythefatboy** [comment]
I have the same problem, Preferences...general...iPad storage shows the correct file space is being used by Kiwix, but Kiwix doesn't show the actual zim. When I try to download the sim directly to the iOS device (both iPad and iPhone with latest iOS) it always hangs, usually with about one GB left to download. When that happens, the pause button no longer has any effect, only the cancel button works.

**Comment by kelson42** [comment]
We should really release the version @automactic has put in Testflight ASAP IMO. I believe this might fix this pb.

**Comment by davythefatboy** [comment]
Happy to try the beta in Testflight if you like.

**Comment by automactic** [comment]
@davythefatboy Hey we have just released version 1.13.2, which should fix the issue you are facing. Could you please update the app and give it a try?

**Comment by davythefatboy** [comment]
Thanks, I installed that update and the wikipedia_en_all_maxi_2020-06.zim that I had previously transferred from my computer is now visible and functional. Searches are quick. I am about to transfer the same file to my iPad, will report back only if I have issues. Thanks so much!

**Comment by automactic** [comment]
Cool, I am glad it worked!
