### ISSUE TITLE
Kiwix MacOS crashes while typing in the search bar

### ISSUE THREAD

**Issue by apaeffgen** [kiwix/apple#285]
Kiwix Version 2.0 (2.0.9), MacOS 10.14.6

I have testet with different zim-Files in the language DE. Only one zim-file is used locally at a a time.
All files opened and everything works, except the search funktion.

If i type in one letter, the application closes / crashes.

Below are the only Console entrys with the searchterm "kiwix"
standard	08:40:56.113715 +0200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Kiwix
standard	08:40:56.113741 +0200	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Kiwix
standard	08:40:56.113786 +0200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Kiwix

**Comment by kelson42** [comment]
@apaeffgen Thank you for your bug report.
@automactic I'm pretty sure that this is the impact of https://github.com/openzim/libzim/issues/353. Would we be able to make a new release based on the lastest libzim soon?

**Comment by kelson42** [comment]
@apaeffgen We just have released version 2.1.1. Would you be able to test it please?

**Comment by apaeffgen** [comment]
Works
