### ISSUE TITLE
Kiwix iOS crashes upon handling wikivoyage en_all_maxi_2020-06

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#287]
From user (feel free to close if incomplete / not actionable; user is pretty responsive so we can ask more questions if need be)

"Downloaded new Kiwix version 1.13.2 last night on my 256 GB iPhone XR. Copied wikipedia_en_all_maxi_2020-06.zim to iPhone overnight from my iMac. This morning I was able to ‘see’ the file on my iPhone, open the file, and do a fast search. Worked great. Then I copied over the latest wikivoyage & wiktionary files, Kiwix would not open, it just ‘flashed’ as if it were opening and immediately shut down again. Did a restart on the iPhone, same issue. Removed last two smaller files, without a restart Kiwix worked fine. Restored Wikivoyage, same ‘flash’ behaviour returned. I have an idea it may be crashing because there is more than one file.

Playing on my iPad with the new Kiwix iPad OS release, it seems:

wikivoyage_en_all_maxi_2020-06

is the file causing the ‘flashing’ problem.

I returned to my iPhone and was able to use Kiwix fine with the latest versions of both Wikipedia and Wiktionary, as long as WikiVoyage was not installed."

**Comment by kelson42** [comment]
`wikivoyage_en_all_maxi_2020-06.zim` is corrupted, wikivoyage_en_all_maxi_2020-07.zim should be downloaded.
