### ISSUE TITLE
Library download progress / status 

### ISSUE THREAD

**Issue by joryanick** [kiwix/apple#288]
Nice app! Please add the ability to view download progress for library items as there's no way to know what's happening aside from the iOS status header. I'm resorting to download on desktop for now. TIA.

#enhancement

**Comment by automactic** [comment]
You can already see progress inside the library

![Screenshot 2020-07-09 at 5 27 28 PM](https://user-images.githubusercontent.com/8294252/87092540-9cd63680-c209-11ea-92ec-ff260926fdd1.png)

**Comment by joryanick** [comment]
Thanks for the reply. It seems I never get beyond "Queued" as status, unsure why.

**Comment by automactic** [comment]
Do you have power saving mode on and is low on battery?

**Comment by joryanick** [comment]
No to both.

**Comment by automactic** [comment]
Hmm, then I am not sure what's going on...

The app will keep the task in queued status until the first batch of data is received from the server side. So two possibilities here: some connectivity issue or iOS decide it would like to defer the download task for whatever reason.

**Comment by automactic** [comment]
@joryanick were you able to successfully download the file?

**Comment by joryanick** [comment]
Yes I tried a download yesterday with the new version and it works perfectly. Thanks for your help!

**Comment by automactic** [comment]
You are welcome!
