### ISSUE TITLE
App status persist between sessions

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#29]
Remember open article over app restarts
and article in position, so next time you open the app with the same article and position in article.

**Comment by automactic** [comment]
This is in plan. But I would give people choices (directly start search, restore history, both, do nothing). But this will be part of the remake the history tracking system.

**Comment by kelson42** [comment]
Great, yes this is important to give choice.

**Comment by automactic** [comment]
@kelson42 This is not possible right now, because `WkWebView` does not support state restoration at the moment. We can certainly implement it ourselves, but that means implement ways to persist the whole navigation stack, which I don't think is really worth the trouble

**Comment by kelson42** [comment]
@automactic This is worth it from thuser perspective. We always have done a custom implementation.

**Comment by automactic** [comment]
Is the status persist only restricted to re-open the last read article? Or do you think it is necessary to preserve the whole navigation stack?

**Comment by kelson42** [comment]
I close this ticket as most of feature has been implemented. Not clear if the whole history should be kept at this stage. One thing which would have been cool ist to have a settings for that behaviour…. But maybe the good way is ti implement a provacy mode….
