### ISSUE TITLE
Suggestions missing

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#293]
Using [wiktionary_fr_app_nopic_2020-07.zim](https://download.kiwix.org/zim/wiktionary/wiktionary_fr_app_nopic_2020-07.zim), I noticed that using very last macOS build (with updated icon `2.1.1 (2.1.4)`), I get less suggestions than expected.

See the following screenshots comapring macOS and kiwix-serve on same ZIM and same query:

![macOS](https://user-images.githubusercontent.com/57929/87571916-43af4c80-c6ba-11ea-8e84-76c2446022e0.png)

![kiwix-serve](https://user-images.githubusercontent.com/57929/87571869-3003e600-c6ba-11ea-8ae0-a3d72a9f5cd6.png)

**Comment by kelson42** [comment]
Would be nice to refresh this ticket with version `3.0.0`

**Comment by kelson42** [comment]
As far as I can judge this works fine with 3.2.0. See:
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/a5235198-1619-472e-ae5b-05673f9d3f73">
