### ISSUE TITLE
Having issue building in xcode

### ISSUE THREAD

**Issue by DanielMK01** [kiwix/apple#296]
No issue when cloning the repo or viewing the source code, but when I try to build, I get this error: "There is no XCFramework found at '/Users/~/kiwix/apple/Model/libkiwix.xcframework'."

**Comment by thesenatorO5-2** [comment]
> No issue when cloning the repo or viewing the source code, but when I try to build, I get this error: "There is no XCFramework found at '/Users/danielkim/kiwix/apple/Model/libkiwix.xcframework'."

Please, remove your username and replace with ~/ for the sake of your privacy. I have encountered the same problem, and also I am installing iOS 13.6 simulator.

**Comment by thesenatorO5-2** [comment]
That is because of the Git Ignore file ignoring that framework.

**Comment by thesenatorO5-2** [comment]
Merging [this](https://github.com/kiwix/apple/pull/310) will  _**Definintely**_ fix this.

**Comment by DanielMK01** [comment]
@thesenatorO5-2 Thanks for the advice. I guess this just means I didn't install the dependencies correctly.

**Comment by rgaudin** [comment]
See updated [README](https://github.com/kiwix/apple/blob/master/README.md)
