### ISSUE TITLE
Add functionality for home page on app start

### ISSUE THREAD

**Issue by metacryst** [kiwix/apple#300]
it's a little strange to have to open the library and open a certain file every time, especially considering that a lot of people probably just have one - wikipedia! it would be very convenient if there was a feature in the settings to set a file to automatically open so that i could just open wikipedia with no extra steps.

thanks!

**Comment by automactic** [comment]
I am indeed planning for a redesign for the welcome page / home page. Components to directly open the zim files main page will definitely be part of it

**Comment by automactic** [comment]
I have added shortcut on the toolbar to allow user to quickly open home page of a specific zim file without open the library, which I will consider to largely be able to address user's feedback.

A new design of the welcome screen is planned, but it is not good enough to be released yet

<img width="511" alt="PNG image" src="https://user-images.githubusercontent.com/8294252/104520216-ba28fa80-55c8-11eb-97f3-8b6136ffabe4.png">

**Comment by kelson42** [comment]
@automactic I appreciate that feature as well
