### ISSUE TITLE
Question: SwiftUI Support

### ISSUE THREAD

**Issue by thesenatorO5-2** [kiwix/apple#309]
I have found that this software used Cocoa as its UI lib, and I want to make a preference view with SwiftUI, is that possible?

- [ ] Possible

- [ ] Impossible

**Comment by automactic** [comment]
No, right now I am not ready to adopt SwiftUI yet. 

Don't get me wrong, I have learned SwiftUI and I like it. However the brittleness of it right now makes me think I should wait one or two years longer.
