### ISSUE TITLE
Bookmark sidebar gesture competes with video player (disable sidebar reveal gesture)

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#324]
The bookmark sidebar display is linked with the swipe left-right gesture. On ipad this happen even if the swipe is done at the really right of the screen (but the side ar appears in the left).

This compete with the video player progression bar used to seek and therefore pretty annoying.

I propose that this gesture applies only on the really left of the screen.

**Comment by automactic** [comment]
> I propose that this gesture applies only on the really left of the screen.

Sorry, this is not possible. The really left part of the screen is reserved for swipe to navigate

> This compete with the video player progression bar used to seek and therefore pretty annoying.

Again, this would not have been an issue if we used a video format the OS can play

One solution is to disable sidebar reveal gesture.

**Comment by kelson42** [comment]
> One solution is to disable sidebar reveal gesture.

Yes, probably the best we can do. Thank you in advance for this gesture removal.
