### ISSUE TITLE
Systematic crash by unlinking content

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#329]

**Comment by automactic** [comment]
Hi did you add the file? What is the iOS version?

I cannot reproduce by tapping the "plus" button inside the library, select a file and select "open in place". Also I am on iOS 14.2

**Comment by kelson42** [comment]
I add files with the plus button. I use ipados 14.2. I have uploaded many crash reports, do you see them?

**Comment by kelson42** [comment]
@automactic The bug is not visible anymore in 1.13.7, but I guess you want to have a proper fix?

**Comment by automactic** [comment]
@kelson42 Yes, I do want a proper fix for this
