### ISSUE TITLE
Proposed UI changes

### ISSUE THREAD

**Issue by bettergraphics** [kiwix/apple#347]
Hi there! Are there any plans to work on the front end look of Kiwix? The performance improvements have been fantastic, and now I'd like to see the visuals as nice as they can be on iOS.

Would it be possible to add a sepia option for reading (much like the Wikipedia app does) along with a handful of font choices? Apple's own San Francisco and New York fonts are brilliant.

**Comment by automactic** [comment]
In the next major Kiwix for iOS release (v1.14), there are some UI improvements with some new features. But they are not related to what you are looking for.

Unfortunately, unlike the wikipedia app, kiwix is not (at least no longer) a dedicated wikipedia offline reader, so the app cannot make assumptions on the content and cannot apply custom logic on how things should be rendered. We rely on content provider (i.e. the zim file) to know how their content should be rendered in say dark mode.

There has been some proposal on standard javascript API to change how article is rendered (e.g. background color), @kelson42  is the best person to ask regarding the current status.

**Comment by automactic** [comment]
There has been over 7 days since I posted a response and there hasn't been any followup from issue reporter. Closing this as no action is planned / needed
