### ISSUE TITLE
Add "clear" button to content sector

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#355]
From a user:
"It will be amazing to have a “clear” button in Search Filter besides the “all” button. So you don’t have to manually deselected them all. 
 
Btw thank you all for the amazing effort put into Kiwix, it really help me a lot when studying without decent internet connections. I promise will make more donations once I graduated from high school."
![Image](https://user-images.githubusercontent.com/21675885/104159498-b2622e00-53ef-11eb-95ed-e800d0fb4ab2.jpeg)

**Comment by automactic** [comment]
Sure, It will be added in a next version.

**Comment by automactic** [comment]
The button to deselect all zim files has been added in 1.14.2. Note the feature itself does require iOS 13.0 and above

![image](https://user-images.githubusercontent.com/8294252/128618680-20e1b0a0-a371-436a-8aed-3c42b611e426.png)
