### ISSUE TITLE
Add libzim or libkiwix version in About panel

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#359]
Given the App Store release process, we have no easy way to know which version of the libzim (or libkiwix) is used in a particular version of the iOS app.

The most reliable/simple/non-invasive way I can think of is to add this information to the About panel which list the dependencies. We don't need versions for all. Just libkiwix's one would allow deducing the others.

**Comment by automactic** [comment]
If kiwix-build can print out versions of libzim and libkiwix at the end of a build, I am happy to add the version info
cc @kelson42

**Comment by automactic** [comment]
@rgaudin Hey, this is done!

![IMG_2653](https://user-images.githubusercontent.com/8294252/145682712-2c3bff9d-347e-415b-96c3-c5cc64299f10.PNG)

**Comment by kelson42** [comment]
> If kiwix-build can print out versions of libzim and libkiwix at the end of a build, I am happy to add the version info

Sorry for my lack of response on this, the versions are in the respective libzim/libkiwix headers I guess & hope you take them from this and don't handle this manually.

**Comment by automactic** [comment]
I do handle it manually right now. How do I get version string from headers? Sorry I couldn't figure it out. Can you give me an example?

**Comment by kelson42** [comment]
@mgautierfr  an you answer that question please?

**Comment by mgautierfr** [comment]
On the libzim compiled (and installed) there is a `zim_config.h`  (which is already included in `zim.h`) file.
It contains `#define LIBZIM_VERSION "7.0.0"` (or any other version)

On libkiwix this is almost the same but a less well implemented. There is `kiwix_config.h` which contains `#define VERSION "10.0.0"`. We should rename `VERSION` to `LIBKIWIX_VERSION` to avoid conflict but you have access to the version anyway.
