### ISSUE TITLE
Provide an ARM build

### ISSUE THREAD

**Issue by iMonZ** [kiwix/apple#361]
Hey,

please provide us an arm64(arm64e) build for the new Apple Silicon Macs with updating the compiler to support universal builds.

regards

**Comment by kelson42** [comment]
Supported with next relase `3.0.0` (but via emulation AFAIK)

**Comment by rgaudin** [comment]
Shame we have an arm64 libkiwix for macOS yet we don't even have a libzim release for it 😉

**Comment by kelson42** [comment]
@rgaudin Yes, we should really fix this ASAP, for both GNU/Linux and macOS and iOS
