### ISSUE TITLE
[URGENT] Hide all ZIM using tag "_sw:yes"

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#362]
As long as #342 is not implemented. Otherwise users might download content that they won't be able to read.

Official publishing of such files starts literally tomorrow.

**Comment by automactic** [comment]
The Mac app does not have a library concept, so I think there is nothing to do here

**Comment by kelson42** [comment]
Maybe, at file opening, print something informing that this is "normal" that they won't be able to enjoy the ZIM! Same as on iOS.

**Comment by kelson42** [comment]
@automactic Have you been able to implement this?

**Comment by kelson42** [comment]
Avcording @rgaudin, this has been implemented.
