### ISSUE TITLE
Some images are not displayed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#364]
User downloaded [the German Wikipedia, 12 March release](http://download.kiwix.org/zim/wikipedia/wikipedia_de_all_maxi_2021-03.zim). Some (but not all) images in the [Frankreich](http://library.kiwix.org/wikipedia_de_all_maxi_2021-03/A/Frankreich) or [Klima in Deutschland](http://library.kiwix.org/wikipedia_de_all_maxi_2021-03/A/Klima_in_Deutschland) articles are not displayed. I cannot really call them missing, as they are available on the zim file itself (see links pointing to the corresponding library.kiwix.org entries).

![7C35ECB5](https://user-images.githubusercontent.com/21675885/111136837-6c0b8580-857e-11eb-86bb-0d9427577693.png)
![D45D0684](https://user-images.githubusercontent.com/21675885/111136840-6d3cb280-857e-11eb-8c63-0721effa2c44.png)
![E8BA2332](https://user-images.githubusercontent.com/21675885/111136842-6dd54900-857e-11eb-8f46-ed71372440ca.png)

**Comment by kelson42** [comment]
Webp polyfill not working?

**Comment by automactic** [comment]
Add the iOS version you are using please.

**Comment by Popolechien** [comment]
The user indicated that after the last release the issue disappeared!
BUT it's still there on macOS (Kiwix 2.1.2): I downloaded https://mirror.download.kiwix.org/zim/.hidden/dev/Wikipedia_en_for_schools_maxi_2021-03.zim and images are also missing (I checked and they're fine on other platforms). Original page is [here](https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome).

![Capture d’écran 2021-04-08 à 17 12 29](https://user-images.githubusercontent.com/21675885/114052710-90f9cc80-988e-11eb-9405-0304c790218f.png)

**Comment by kelson42** [comment]
I still believe that at the root the problem is related to webp polyfill. The problem will slowly disappear from iOS/macOS with the latest updates which add webp support. I will move the ticket to repository openzim/mwoffliner.
