### ISSUE TITLE
adding previous / next page shortcut on macOS

### ISSUE THREAD

**Issue by dw61** [kiwix/apple#377]
It would be great if you could implement a shortcut to switch between pages within the same tab. For example, in safari, you can go to menubar -> History -> Back, or `command [` to visit the previous page. This could be easily implemented by simply adding a menubar function and a corresponding shortcut. If the function is implemented, users could alternatively custom their shortcut [this way](https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/mac).

**Comment by kelson42** [comment]
Actually this is done in `3.0.0`
