### ISSUE TITLE
No sound on videos

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#379]
From user on iOS 1.14.1 running iOS 14.4.2 : no sound can be heard while playing TED videos. Not sure if duplicate of #144 (which is allegedly solved).

**Comment by kelson42** [comment]
Might be the same as mine bug, i have no sound as well on my iPad. So far I was the only one reporting this problem.

**Comment by automactic** [comment]
I tried "A day trip to Antarctica" and there are sound. Tested on both iPhone and iPad running iOS 14.7.1.

You could tell me which file you were testing with, but even if I could reproduce this issue, there is likely nothing I could do, since it is all javascript that's coming with the zim files

**Comment by kelson42** [comment]
In #144, the file was clear. The rootcause of the problem is 100% unclear as this stage.

**Comment by automactic** [comment]
In #144, you mentioned new TEDMED zim file is released and the problem is fixed. Is this issue about TEDMED or is it a completely different zim file?

**Comment by Popolechien** [comment]
@automactic I've tried on [these Youtube playlists](https://farm.openzim.org/pipeline/a903755adb3abd9940155116) and had no sound.

**Comment by automactic** [comment]
@Popolechien I downloaded the file for the 3rd class, and I got sound on my iPhone. 

But even if I can reproduce, there's nothing I can do about it. @kelson42 I am suggesting to either close this or move this upstream to the offliner

**Comment by Popolechien** [comment]
@automactic I was on macOS (big sur).

**Comment by kelson42** [comment]
@Popolechien please open a new ticket then, this is a bug for ios.

**Comment by kelson42** [comment]
@automactic There is nothing we can do on mwoffliner if there is no technical analysis on ios.

**Comment by automactic** [comment]
What technical analysis do you want me to produce?

**Comment by kelson42** [comment]
Anything leading to the conclusion this is a problem in the js/html which is in the ZIM.

**Comment by automactic** [comment]
> I would start by checking if the Javascript engine does not complain about anything.

@kelson42 since you have said you got no sound on your iPad, why don't you try to check this out. Connect your iPad to your MacBook (if you still have it), then follow steps in, for example, this [blog post](https://www.busbud.com/blog/debug-ios-safari-mac/)

You should see something like this 
<img width="947" alt="Screen Shot 2021-08-20 at 4 39 56 PM" src="https://user-images.githubusercontent.com/8294252/130291075-40a89092-31c9-4dd3-b7fb-482ccab280ca.png">

**Comment by automactic** [comment]
FWIW, here is what I see when I load `dse-ladak_hi_class-3rd_2021-08.zim`

<img width="1237" alt="Screen Shot 2021-08-20 at 4 41 02 PM" src="https://user-images.githubusercontent.com/8294252/130291187-24cd83d5-50c3-41e9-9338-3d78a6448966.png">
<img width="1237" alt="Screen Shot 2021-08-20 at 4 41 13 PM" src="https://user-images.githubusercontent.com/8294252/130291198-6cdeb486-b09c-44bc-a0ce-c1d2ed6452c3.png">

**Comment by automactic** [comment]
@kelson42 what are we gonna do about this?

**Comment by kelson42** [comment]
Find someone to investigate the bug. Will try to follow your instruction as well.

**Comment by kelson42** [comment]
I think the root cause of this problem is this ticket https://github.com/brion/ogv.js/issues/600 in the javascipt based audio decoder. I have tested it and this explains at least why I can no have proper audio on my tablet. This is not a bug in Kiwix but in the ZIM file itself,

**Comment by kelson42** [comment]
Basically a duplicate of https://github.com/openzim/ted/issues/133
