### ISSUE TITLE
Implement Text-to-Speech

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#38]
iOS SDK provide a TTS (Text-to-Speech) framework which should allow relatively easily to provide a way to read articles. This is useful for many users, in particular the ones suffering from impairments (inability to read). This feature has been implemented on Android and we know that this is really appreciated by users.

**Comment by automactic** [comment]
Kiwix for iOS is mostly accessibility ready. If you want your device to read contents on screen to you, go to Setting -> General -> Accessibility -> VoiceOver. It even tell you this is a button or search bar when you tap on them.

**Comment by kelson42** [comment]
This does not really behave like it should:
* It changes - really seriously - the behaviour of the whole OS
* I can not read continusly an article
* It does not read in an other language than the language of the OS

**Comment by kelson42** [comment]
> It does not read in an other language than the language of the OS

This seems to work fine now.

**Comment by kelson42** [comment]
Second point seems to be not true (anymore?) either and first poing of my comment is not valid either as the activation of all of this is well done: you can use it whenever you want.

**Comment by siddharth2010** [comment]
> Kiwix for iOS is mostly accessibility ready. If you want your device to read contents on screen to you, go to Setting -> General -> Accessibility -> VoiceOver. It even tell you this is a button or search bar when you tap on them.

There also seems the "Speak Screen" option is much better suited for this. 

We should probably add a tutorial though to show the user on how to enable it and how to use it.

|.|.|.|
|:-:|:-:|:-:|
|![IMG_3359](https://user-images.githubusercontent.com/32238400/63212081-d7ba1200-c0ff-11e9-9bde-f3a8655f47ff.PNG)|![IMG_3360](https://user-images.githubusercontent.com/32238400/63212085-dbe62f80-c0ff-11e9-8099-77581fec2b45.PNG)|![IMG_3361](https://user-images.githubusercontent.com/32238400/63212088-e0aae380-c0ff-11e9-99f5-c34875dd8cb6.PNG)|
