### ISSUE TITLE
kiwix 2.1.2 macos 10.13.6 crash when searching 

### ISSUE THREAD

**Issue by markNZed** [kiwix/apple#382]
Hi, I have the 20 March 2021 Wikipedia .zim file and searching for the letter 'a' or 'b' or 'c' works but searching for the letter 'd' crashes the kiwix app, most other search terms I tried also crashed. Is this a known problem? Thanks.

**Comment by kelson42** [comment]
It is new to me at least.

**Comment by markNZed** [comment]
How can I help? Is there some logging?

**Comment by kelson42** [comment]
What is your exact model of computer? And version of macos?

**Comment by markNZed** [comment]
macOS High Sierra Version 10.13.6

**Comment by kelson42** [comment]
@markNZed I mean the computer, not the OS.

**Comment by markNZed** [comment]
A 2011 iMac

**Comment by kelson42** [comment]
@automactic Would be good to clarify it this hardware had a 32bits architecture... and secure Kiwix macOS is compiled in 64 bits. If we have 32 bits somewhere this is probably fixed with https://github.com/openzim/libzim/pull/569. You might consider redo a release of libzim 6.3.2 which fixes this issue.

**Comment by rgaudin** [comment]
@kelson42 Kiwix macOS is 64b. I am affected by this also but though it was #285. Didn't realize this was closed.

**Comment by rgaudin** [comment]
To me, typing any letter in the search bar crashes the App immediately

**Comment by kelson42** [comment]
We should really make a new release ASAP based on libkiwix10 to see if this bug still occurs.

**Comment by tjcampanella** [comment]
I am having this same issue. I have a M1 Macbook Pro and whenever I go to search it crashes immediately.

**Comment by tjcampanella** [comment]
I have confirmed this happens when trying to search the kiwix wikipedia 93g en all maxi file. This happens on mobile and desktop versions.

**Comment by kelson42** [comment]
Duplicate of #450 IMO
