### ISSUE TITLE
macos, ui is matched dark as it should be, is making the zims dark possible?

### ISSUE THREAD

**Issue by greeneryAO** [kiwix/apple#387]
I don't really see the point in having a nice dark ui which matches system color and then bright white wikipedia zim, any workarounds? There are no options that I can change it's barebones.

Can I do this is js version, if so I'll try that, I have light sensitivity so I hate reading on white backgrounds.

**Comment by kelson42** [comment]
No workaround AFAIK

**Comment by greeneryAO** [comment]
ok thanks for the prompt reply, will look into the js version.

**Comment by automactic** [comment]
There is no way to magically make the content dark mode aware. 

Kiwix is a generalized reader of zim files, the zim file provider needs to update their content to support dark theme (specifically [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)). This is the same as even when most browser UI support dark theme, each website has to opt-in to support dark theme.

 If you are using wikipedia, it likely mean wikipedia website has to support dark theme first.

**Comment by greeneryAO** [comment]
Yea I get it, I mostly want wikipedia and wiktionary, which really both should be dark themed by now since most major sites are.

**Comment by automactic** [comment]
Yep, it is really sad and long overdue. However, I could understand the challenge on their side (math formula as images, transparent images, and the astronomical  amount of images / pages, etc)

I am closing this for now, since there is nothing I could do

**Comment by kelson42** [comment]
Like said by @automactic, this is an open and old topic. This will be fixed at some point, but not timeline for the moment.
