### ISSUE TITLE
Erratic behaviour on iPad mini with latest 1.15.1 release

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#421]
From a user:

Since the update, pages are not loading correctly reliably—or the internal browser is hanging. Hard to tell. Links will not work between pages, the “home” or “random” buttons don’t respond. Pages will load but without full formatting. Text is present but not in standard Wikipedia format. It’s random when this happens. Some pages load fine. After repeated attempts, a page may load. I’ve had to do a mix of repeating searches and clicking on the results, going to different random pages, forward and back buttons to get the page I’m after to load. It was distinct and sudden, and I went to check update history in the App Store to see if there had been an update… so whatever the last bug fix did, it added at least one more bug. It happens about 10-25% of the times I change pages.

This is all while using an “all maxi” version of Wikipedia downloaded several months ago. It’s the only file I have used with Kiwix so far, but I use it often so the change is noticeable. Device is a 5th generation iPad mini.

iOS version is 15.1, Kiwix version is 1.15.1 and the zim file is wikipedia_en_all_maxi_2020-12.zim

**Comment by automactic** [comment]
There was a libkiwix (and its dependency) update that I included with 1.15 or 1.15.1. But unfortunately with vague description like this, it is almost impossible for me to do any kind of testing or triaging. 

I think the next step would be resubmit a model once a new stable libkiwix version is released and ask user to try again

**Comment by automactic** [comment]
Version 1.15.3 will be reverting to the last known stable version of libkiwix and libzim. It is currently waiting for review. So I will consider this matter closed

**Comment by Popolechien** [comment]
The user came back with a more extensive testing on 1.15.3 (iPadOS version 15.1 (19B74))
Testing these files:
- 3dprinting.stackexchange.com_en_all_2021-03.zim
- wikipedia_en_all_maxi_2021-03.zim
- wiktionary_en_all_maxi_2021-10.zim

Here is their feedback:
"A stack exchange zim [has the same issue]. I haven’t noticed a wiktionary one doing it (yet). All of this is after a complete reinstall of the app and zim files. Zim files downloaded from inside the app. 

I can tell which entries will load or not from a search based on if it shows just a title, or part of the entry as well. I haven’t figured out what the “tell” is if I’m just viewing a page if a link will work or not. I’ve attached a picture of this. 

![image](https://user-images.githubusercontent.com/21675885/146214215-dbdc1bec-486a-4e99-be3f-e2b8c1851230.png)
In an earlier search of “derp” the page for von derp had no secondary test and wouldn’t load. After doing other things in the app, a search showed secondary text and I was able to load it. It gave me a partially loaded page, as shown in screenshot. 
![image](https://user-images.githubusercontent.com/21675885/146214254-99611407-ef03-4971-b548-be938633dfb4.png)

After further going to random pages and redoing the search yet again, it gave me the fully loaded page. "

![image](https://user-images.githubusercontent.com/21675885/146214289-d6b06fb0-35c0-41f2-a8e0-333efcb89868.png)

**Comment by automactic** [comment]
I cannot reproduce this on my iPad. These three article seems to load normal on my iPad. I guess I am curious if things become normal after some articles cannot be loaded initially (the user seems to suggest thing become normal)? 

@kelson42 Do you have any suggestion here?

https://user-images.githubusercontent.com/8294252/146290206-8100df18-6432-4a16-8fbe-8f5a763b2feb.mp4

**Comment by kelson42** [comment]
I should really give a try myself to see if I can reproduce the problem.

**Comment by Popolechien** [comment]
Response from the user:
"I can confirm it is intermittent on any given page. Doing a search for “derp” again, the von derp page showed only the title and refused to load. After going through and loading other pages randomly (and tryin to get von derp to load again) several times, I eventually got the von derp page to load. Now it, and several other pages on the search for “derp” load normally (for the moment).

Would a video of this whole process help? (Not sure how to transfer but can try.) It’s unreliable enough I don’t know how many pages/how much I’ll have to “wiggle” to get a bad one and make it work, but reliable enough I know it’ll happen in a reasonable time.

This seems to have gotten worse in the last few days (possibly related to me reinstalling the app and redownloading/adding zim files?) so if there’s anything I can do to help, let me know. I really like Kiwix and use it daily. "

**Comment by kelson42** [comment]
Tested with 1.15.3 and 3D printing ZIM. All seems to work fine to me.

**Comment by automactic** [comment]
@Popolechien @kelson42 I cannot think of any additional way to help the user. Given we cannot reproduce the issue, I suggest we close this issue

**Comment by Popolechien** [comment]
@automactic So be it.
