### ISSUE TITLE
"When building for iOS, no library for this platform was found" error when building for iOS device

### ISSUE THREAD

**Issue by imustbebored** [kiwix/apple#433]
Hi there,

I have successfully compiled Kiwix iOS on the simulator, but for some reason when I go to build the app for generic iOS devices in xcode, it gives me the following error: 

"While building for iOS, no library for this platform was found in..."

I'm confused because when generating libkiwix.framework, I used iOS_multi and then further generated for both iOS_x86_64 and
iOS_arm64 following the github's directions. So why then is the build failing for actual ios devices? If anyone could please give me some insight into how to resolve this issue and be able to build for physical ios devices, it'd be much appreciated. Thanks.

**Comment by kelson42** [comment]
@imustbebored I'm really sorry for the lack of feedback on this. The problem is that the current compilation process is far too complex. In a way we will simplify the process to have only the macOS specific stuff to be done... and strongly suspect that once this is done then it will just work.

**Comment by kelson42** [comment]
@imustbebored Finaly, we are just about to fix this problem. Should be reqdy next week.

**Comment by kelson42** [comment]
All done, shoukd be straight now to compile Kiwix.
