### ISSUE TITLE
Zim files requiring Service Workers should be hidden from the library if SW are not available

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#435]
Following up on [Libkiwix#696](../../libkiwix/issues/696)

Currently zimit-generated files can only be read on Kiwix-Android and Kiwix-serve (K-Desktop has a workaround but it's not main stuff). 

macOS and IOS cannot read these files, yet it is likely that at least some users will invest data transfers (and costs) into downloading files they ultimately cannot access.

Since zimit-generated files are tagged as such, it would make sense that they be hidden from the app's internal library if we know it cannot be read.

**Comment by kelson42** [comment]
duplicate of #362
