### ISSUE TITLE
App becomes unresponsive after several searches (ipad

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#437]
From a user (ticket n°28205), feel free to ask any questions that I might forward.

"I'm using an iPad mini 4 with latest iOS 15.3 installed. Kiwix iOS 1.15.4

Finding that after a few searches, screen won't engage new search term or open links in pages. The list of search term 'hits' appears, but pressing them doesn't engage anything.

If I delete the app from background and try again, all is good for a while.

Notice it especially happens when in slide over mode. I have iOS Shortcut to open it. Not sure if that effects anything. Either way, if I clear app from background and restart, it overcomes the dead screen.
"

**Comment by new001jv** [comment]
Same, unresponsive after a few searches. I am on a iPad mini 5th gen. Just updated to iOS 15.3, still having issues. iOS 14 worked perfectly. Every version of iOS 15 has been troublesome.

**Comment by kelson42** [comment]
How many? 5, 10, 20?

**Comment by new001jv** [comment]
1 to 5 times so far. [Video for reference ](https://youtu.be/pg5kUMzvJy8)

**Comment by kelson42** [comment]
@new001jv @Popolechien Release 1.15.5 has been made and use now a cutting edge libkiwix. Do you still suffer of this problem?

**Comment by kelson42** [comment]
We should verify if this still happen with future version (here testfligh link https://testflight.apple.com/join/pKozwnSU)

**Comment by kelson42** [comment]
Closing this ticket as the problem seems to be fix in 3.0.
