### ISSUE TITLE
Languages list should be sorted alphabeticaly (but escape button is not always displayed).

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#44]
In the content manager it is pretty difficult to find a language between the hundreds available because there is no search and the languages are sorted by number of content... which is here not really helpful. That's why I propose to sort them alphabetically or make the list searchable (create a searchbox).

**Comment by automactic** [comment]
it is added in 1.8, to be tested

**Comment by martin8032** [comment]
Languages are still sorted by the number of items, not alphabetically (v1.8, iOS 10.2.1 de_CH, iPad Pro)

**Comment by kelson42** [comment]
@automactic Status on this?

**Comment by automactic** [comment]
Fixed on version 1.9.4. @kelson42, can you verify this issue is fixed and close it?

**Comment by kelson42** [comment]
Works. Thx.

**Comment by kelson42** [comment]
Hmmm.. but now I have no clue how to leave that language selection view!

**Comment by kelson42** [comment]
In 1.9.5, I see the "done" button again :) @automactic well done.
