### ISSUE TITLE
iOS: crashes on search in wikiHow

### ISSUE THREAD

**Issue by sorrge** [kiwix/apple#440]
The iOS app crashes a split second after I type a letter in the search box. This happens in multiple libraries, big and small. Device is iPhone 13.

**Comment by sorrge** [comment]
I take that back: I had all libraries enabled in the search when it was crashing. After trying them one by one, it seems the offending library is wikiHow with pictures and videos. When it is selected in the search, it crashes. Other libraries that I tried work correctly.

**Comment by kelson42** [comment]
With TestFlight, WikiHow still fails to load at all.

**Comment by kelson42** [comment]
@sorrge Works fine now with 1.15.5. Does this new version has fixed the problem for you as well?

**Comment by kelson42** [comment]
No feedback, highly probably been fixed.
