### ISSUE TITLE
Crashing on searching large file IOS and MacOS

### ISSUE THREAD

**Issue by tjcampanella** [kiwix/apple#441]
When trying to search through the wikipedia_en_all_maxi file which is around 90gb the app crashes every time. This happens on mobile and the desktop version. I am unsure if something is wrong with the file or if it is a bug with the app. I got the file from the kiwix website. Thanks for any insights.

**Comment by yili001** [comment]
happens on me too, when tying words on search bar, the app sometimes will just crash and return to desktop, my OS version is ios15.4.1

**Comment by kelson42** [comment]
Pretty much certain, this is fixed in next release `3.0.0`

**Comment by kelson42** [comment]
@tjcampanella @yili001 Please reopne if you still have the problem with version 3.0
