### ISSUE TITLE
Do not search when ZIM file has no fulltext index

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#443]
Otherwise it crashes. Check with this one https://sourceforge.net/projects/telugu-dictionary-zim-file/files/

Same problem as https://github.com/kiwix/kiwix-desktop/pull/830

**Comment by automactic** [comment]
Fixed in https://github.com/kiwix/apple/commit/ff218ebf6788e7f306c26734f2f1df1a0495e1aa
