### ISSUE TITLE
App immediately and consistently crashes when typing anything in the Search box.

### ISSUE THREAD

**Issue by FellowTraveler** [kiwix/apple#444]
App immediately and consistently crashes when typing anything in the Search box.
Kiwix 2.1.2 on MacOS Monterry 12.2.1 (with WikiHow zimfile open).
Installed via the App Store, but then also downloaded kiwix-desktop-macos_2.1.2.dmg and tested that version as well. Same result every time with both.

Crash log:
[kiwix_crash.txt](https://github.com/kiwix/kiwix-desktop/files/8498918/kiwix_crash.txt)

**Comment by Ben-tahar** [comment]
Same problem here. 
It doesnt matter how big the files are,  even witout a file open, every time I type something in the search box the app crashes.
Im on a macbook pro 15inch mid 2015 with Catalina 10.15.7

**Comment by pettyalex** [comment]
This is disappointing, I ran into this immediately upon trying to use Kiwix. Immediate crashes on trying to search:

```
Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
```

I'm on an M1 Air. I wonder if this still happens if I compile it locally, I'll try that.
