### ISSUE TITLE
Stop using deprecated libkiwix methods

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#445]
libkiwix `10.x.y` have deprecated many methods and function which I guess are still in used in Kiwix iOS and macOS. This has two consequences:
* Many warning at Kiwix compilation time
* Stop us to removed these old/deprecated primitives in future libkiwix releases.

Would be beneficial to remove the usage of these deprecated methods and use modern/new API of libkiwix.

The effort has already been made in Kiwix Tools, see https://github.com/kiwix/kiwix-tools/pull/535 and this PR might help to know what to do with Kiwix For iOS and macOS.

**Comment by automactic** [comment]
Are the classes mentioned in https://github.com/kiwix/libkiwix/issues/430 all that needs to be updated. If it is all, then I have already finished migrating to the new classes

**Comment by kelson42** [comment]
@automactic The list is not complete IMO, just make a compilation run and see if you have deprecation warnings. If not, then this is Ok.

**Comment by automactic** [comment]
There are no deprecation warnings right now. Looks like I can close this
