### ISSUE TITLE
Unable to build (Libraries folder issue)

### ISSUE THREAD

**Issue by ghost** [kiwix/apple#449]
When building, there is no libraries folder.  I tried moving the libkiwix.xcframework from the Model folder (this is where libkiwix builds to per the README) and that still does not work.  Here is the error I am receiving and some screenshots.  How do I properly build the Libraries folder (missing realm and libkiwix, though I have libkiwix properly built on the system and as the screenshot shows built for iOS_x86_64 and iOS_arm64)

I receive the following error when trying to build:

Showing Recent Messages

/Users/ /app/apple/Libraries/libkiwix.xcframework:1:1: **While building for iOS Simulator, no library for this platform was found in '/Users/ /Downloads/app/apple/Libraries/libkiwix.xcframework'.**  

There is no XCFramework found at '/Users/~/app/apple/Libraries/Realm.xcframework'.

There is no XCFramework found at '/Users/~/app/apple/Libraries/RealmSwift.xcframework'.

There is no XCFramework found at '/Users/~/app/apple/Libraries/Realm.xcframework'.

There is no XCFramework found at '/Users/~/app/apple/Libraries/RealmSwift.xcframework'.

Thanks for any advice.  Screenshots below:

<img width="1440" alt="Screen Shot 2022-06-21 at 1 08 14 PM" src="https://user-images.githubusercontent.com/1443666/174859274-d6328d0f-0a26-4d74-a7ba-315681c4604b.png">
<img width="1440" alt="Screen Shot 2022-06-21 at 1 09 49 PM" src="https://user-images.githubusercontent.com/1443666/174859276-cc606fe4-6b16-4174-91d1-91c79e0d7bd5.png">

**Comment by kelson42** [comment]
@jchawla785 I'm really sorry for the lack of feedback on this. The problem is that the current compilation process is far too complex. In a way we will simplify the process to have only the macOS/iOS specific stuff to be done... and strongly suspect that once this is done then it will just work.

**Comment by kelson42** [comment]
This is finally goign to be fixed next week!

**Comment by kelson42** [comment]
Done, all should be striaght and easy now.
