### ISSUE TITLE
Ability to hide/move "random article" button

### ISSUE THREAD

**Issue by lxgr** [kiwix/apple#474]
On my iPhone (13 Pro), the "random article" button takes up valuable space in the action bar, making "Settings" and "Library" collapse into the overflow menu (sorry, not sure if these are the correct UI terms).

This is purely anecdotal/personal, but I use either option much more frequently than opening a random article, and it's annoying having to do the extra tap/step every time.

**Comment by kelson42** [comment]
Agree
