### ISSUE TITLE
Introduce Continous Deployment

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#492]
For the moment, Kiwix for macOS/iOS is built on a developer machine and then published.

This has a number of disadvantages:
* It is really unsecure (what about is something fishy runs/happens on this computer)
* No separation of duty between development and publishing duties (as well a security issue)
* The process as a consequence is not really optimised/documented/scripted/reproducable/tracable
* Not real pressure to simplify the process of publishing
* No nightly (or similar)
* A SPOC at the developer in charge
* ...

This is a recognized bad practice of the software industry anyway and should be avoided if possible. Kiwix for macOS/iOS is almost 10 years old, had a major and great revamping last years which makes it easier to maintain. The audience is growing as well, so the impact in case of problem. Actually this repository is one of the last without CD and it's time IMO to fix this weakness.

Blocked by #159

**Comment by Bmkbbb222** [comment]
](https://www.icloud.com/shortcuts/ebf488e1ac8a4c11bcb2b5cada86e4a9)**

**Comment by kelson42** [comment]
This CD should be able to build like the CI and:
* Once a night publish nightlies of the Universal DMS at http://download.kiwix.org. Guidance will be provided to deal with the upload at download.kiwix.org
* Each time a release is done at Github, new packages should be published on both http://download.kiwix.org/ and iTunes.

**Comment by rgaudin** [comment]
Here are the instructions for Upload:

- There is an `SSH_KEY` secret in the repo that's a private key allowed to upload to our server
- Store it on the filesystem during the workflow [as in kiwix-build](https://github.com/kiwix/kiwix-build/blob/44a8963c5025b54c2ae3a19374c6a08d36c0daa3/.github/workflows/releaseNigthly.yml#L92)
- Upload using scp [as in kiwix-build](https://github.com/kiwix/kiwix-build/blob/44a8963c5025b54c2ae3a19374c6a08d36c0daa3/.github/scripts/common.py#L177)
  - create any required folder using sftp
  - user is `ci`
  - server is `master.download.kiwix.org` on port `30022`
  - target folder for releases is `/data/download/release/kiwix-desktop-macos/` and `/data/download/release/kiwix-ios/` -- ⚠️ @kelson42 must confirm
  - target folder for nightlies is `/data/download/nightly/YYYY-MM-DD/` where `YYYY-MM-DD` is the build date in said format
  - Nightly filename must include the date.
  - Release filemame must include the version

Please let me know if I can be of any assistance
