### ISSUE TITLE
With 3.1 none of the videos can be played up to the end.

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#499]
Was working with 3.0.0, but since 3.1, wither:
* the video stopps after a while
* The video restarts after a while

**Comment by rgaudin** [comment]
I can reproduce with `3.1` build `116` installed from the App Store.
This is not recoverable using Video UI. Have to change page and come back.

Don't know what trigger the stop but it's consistent for the same video. Might be related to filesize/duration. I've had 15s, 30s, etc. VideoJS UI displays decreasing duration while playing and once it hits the _limit,_ it stops and the remaining duration is 0.

Haven't checked whether this happens at end of _loading_

**Comment by DaiZ4** [comment]
I'm having the same issue and new to Github.  Does anyone know if this is being attended to?

Just not sure whether its worth keeping the app for now?

**Comment by rgaudin** [comment]
It's been fixed and the new app is in test phase (testflight) since yesterday

**Comment by DaiZ4** [comment]
Thanks for the quick response.  Guess I must have just lucked out coming across this program today 😉

**Comment by kelson42** [comment]
Works again
