### ISSUE TITLE
Search field select-all after search on iOS

### ISSUE THREAD

**Issue by guanix** [kiwix/apple#500]
I’m in the process of reading some books in a second language, and frequently need to look up words in Wiktionary in Kiwix. I often do this in a popover on my iPad. I might search for word “foo”, tap the definition and read it. Then a few minutes later return to search for “bar”. After tapping the search field, “foo” is still entered, and the cursor is at the end of the word. I now have to tap the fairly small X tap target to clear “foo”, slowing down my reading process.

I believe the default should be that the search field is cleared entirely, or that the contents of the search field is selected, so I can immediately type in “bar”. This is how the search field in Safari works: if you search for something, then later go back to search for something else, the contents are all selected. I believe this is what most iOS users would expect.

(If my suggestion is adopted, on the rare occasions when I do want to keep to keep typing after “foo”, there would be a much larger tap target to accomplish that because I can tap to the right of “foo” and to the left of the X.)

Steps to reproduce:

1. Search for something, by entering a search term and tapping the keyboard button “search”.
2. Tap one of the results.
3. Tap the search field to search for something else.

Result:

Nothing is selected and the cursor is at the end of the previous search term.

Expected result:

The contents of the search field are selected, so if I start typing something else, the previous search term is cleared.

I am trying to fix this myself, but having issues with #449, and also the fact that kiwix-build doesn't seem to support the iOS emulator on ARM (Apple Silicon, M1/M2) Macs. I'll keep working on building so I can do this myself.

**Comment by guanix** [comment]
Ok, the solution turned out to be quite simple. This is also how the macOS app already behaves. https://github.com/guanix/kiwix-apple/commit/e459908145dafb137468a5502a8620c64c8e2f48

**Comment by kelson42** [comment]
@guanix Thx for your issue. Might that be this has been fixed in version 3.2? I can not reproduce the issue anymore. Once I have clicked on an item and open the corresponding article, the searchbox is cleared.

**Comment by guanix** [comment]
@kelson42 It is fixed now, thank you.
