### ISSUE TITLE
Introduce a way to create easily custom apps for iOS and macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#501]
Similar to the one we do on Android

**Comment by kelson42** [comment]
@automactic What is the status of the Wikimed iOS app https://apps.apple.com/ch/app/wikimed/id1281693200?l=fr :
* does it has been updated recently!
* Does it use the 3.0 code base?
* Do we have the procedure documented somewhere to create such an app?

**Comment by rgaudin** [comment]
Store says it's still `1.0` from October 2017

**Comment by kelson42** [comment]
Confirmed my guessed based on the dataset.

**Comment by kelson42** [comment]
I have proposed a more detailed version of this request at #520. Sorry for the mess
