### ISSUE TITLE
Handling of lack of storage space is weak

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#507]
My iPad storage is full, but I achieve to start a download of a book, without any warning and the download of the book get stuck in the middle without any error message displayed.

![IMG_2572](https://github.com/kiwix/apple/assets/1029718/44fb5f22-7148-45dd-b149-f2379aebc87e)

We should:
* grey and disable (to the download) books which are too big
* Computation of the free space shoukd be correct
* If for some reason the download can not be completed (because of lack of space) a proper error/handling should occur

**Comment by anthony-bernardo** [comment]
I think the error is already fixed, I tried with my ipad, mocking the size of storage remaining, and I was getting an alert message

**Comment by kelson42** [comment]
Seems that this bug has been fixed. Works fine now.
