### ISSUE TITLE
Clearly document the iOS/macOS supported (supporting strategy)

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#508]
For the users, we should clearly document (in the `README.md`?) what are the version of iOS/macOS supported by the latest version. It might be interesting to keep track of what older version support (as these version are downloadable via iTunes and available via DMG).

For the developer, we should document (in the `README.md`) the strategy to follow in term of support to avoid building new features/fixes relying on primitives which are only available on very recent version of the OS/SDK.

**Comment by NXPY123** [comment]
Hello, @kelson42. I'm new to Kiwix and want to learn more about and contribute to the project. Can I take up this issue?
