### ISSUE TITLE
Preferences: Add line height adjustment

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#51]
I really aprecciate the possibility to change the font size in the settings. But there should be a second option to adjust the line height as well, because in higher font sizes the default line height is too big, wasting a lot of screen space.

**Comment by kelson42** [comment]
Many people require this kind of features. To me, the main reason is that the ZIM file is not proper and the problem should be fixed there first. And implementing many "zoom" feature will only make the whole app more complicated.

Then we have the problem of people not seeing well or simply liking to see things big. And for them an overall content zoom feature should be IMO good enough.

So, my question is: why an overall zoom feature of the HTML rendering widget (so replacing the font increase/decrease feature) would not be able to do the job?

**Comment by martin8032** [comment]
To me, font size and line height are two separate aspects of readability. And when I opened this issue almost 3 years ago, changing just the font size resulted in a quite ugly line spacing. But now it looks different, and it's not critically important anyway, so let's close this issue.
