### ISSUE TITLE
Open Link in Tab

### ISSUE THREAD

**Issue by DirkMausF** [kiwix/apple#517]
Is it hard to implement a "Open Link in New Tab"?

**Comment by kelson42** [comment]
@DirkMausF Inguess this has been fixed by #536. You can check with the latest nightly BMG http://download.kiwix.org/nightly/

**Comment by DirkMausF** [comment]
Yes, solved! Nice work, Thx! 

Maybe you could rename it to '"Open in new tab" instead of "Open in new Window", but that's only a cosmetic issue.

**Comment by kelson42** [comment]
@DirkMausF AFAIK there is a fondamental weakness in the SDK which is that this contextual menu is (almost) not customizable. I guess it will stay like this.
