### ISSUE TITLE
[Question] How to create  ZIM files without Service Worker, so we can use it on ios. Thank you.

### ISSUE THREAD

**Issue by mobilelifeful** [kiwix/apple#519]
How to create  ZIM files without Service Worker, so we can use it on ios. Thank you.

**Comment by mobilelifeful** [comment]
> Most of ZIM files don't rely on service workers. What do you want to scrape exactly?

would like to opt out service workers when youzim.it is used. I have try a site, can't open it on ios app, but ok on desktop.

**Comment by kelson42** [comment]
@mobilelifeful zimit based ZIM files should not be available for download, see https://github.com/kiwix/apple/issues/363.

Anyway version 2.0 of Zimit won't rely anymore on SW. Should be publish end of this year.

Closing this ticket and asking for a bit of patience.
