### ISSUE TITLE
Usability issues in the library

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#52]
To me interacting with the packages in the library is not very intuitive. I would expect that I can touch a package just anywhere to start a download (Cloud) or to open it (Local). Opening a dropdown and selecting a command from that dropdown is tedious, especially if you switch often between several packages.

In addition, the «info» icon is not adequate since the dropdown contains actions, not only information.

**Comment by automactic** [comment]
In commit 4698d52195dc946e72de62d1aa30d460ec3053f4

**Comment by automactic** [comment]
Hi, @martin8032. @kelson42 and I thinks solution 3 is the best. What do you think?

**Comment by kelson42** [comment]
@automactic My opinion too.

**Comment by martin8032** [comment]
@automactic I agree.

**Comment by automactic** [comment]
@martin8032 , @kelson42, in build 1.8.4112(86b8757219aa7dea450120433d7c34c87bdf099a)

**Comment by martin8032** [comment]
The solution for small screens is fine.

The solution for large screens is the same as before, so IMHO we still have an issue here.

I agree that in the cloud tab it's confusing when a package simply disappears after the user chooses it for download. But this behaviour is confusing anyway (no matter how you trigger the download) and should be changed as well: Leave the package where it was and simply show a loading bar or a circular loading icon (like in the app store).

I'm still convinced that tapping on a package should trigger an action on an iPad. I see two possibilities:

- Remove the info icon, make the whole cell trigger a dialogue box (centered on the screen) containing all the information and commands that we have in the dropdown now.
- Leave the info icon, make the cell trigger the default action (**download** in the _cloud_ tab, **open** in the _local_ tab), and add a confirmation dialogue in the cloud tab: "This package contains XX GB of data. Do you want to download it?" (We won't need a confirmation in the local tab because there's no riks in opening a package. This is my preferred solution.

**Comment by automactic** [comment]
The library is revamped in version 1.9, which addressed some of the issues talked above. Welcome joining us on TestFlight.
