### ISSUE TITLE
Cmd + click to open link in new tab

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#540]
Similarly to native safari browser, it would be nice to have cmd + click opening links in new window/tab on macOS.

**Comment by ishqDehlvi** [comment]
How can I reproduce this issue?

**Comment by kelson42** [comment]
@BPerlakiH Can you help here please? Was under the impression it was obvious... but seems its not!

**Comment by BPerlakiH** [comment]
This issue is about the fact that in the traditional macOS applications, (such as Safari browser) it is possible to use the combination of CMD + left mouse click on a link to open it in a new tab.
Currently in our application we do support to open links in a new tab, but in order to do this the user needs to right click on a link and select "open in a new window" which as a result will open the link in a new tab.
We would like to have the very same behaviour but with the shortcut of command + left mouse click.

**Comment by kelson42** [comment]
Fixed by https://github.com/kiwix/apple/pull/708
