### ISSUE TITLE
Search of patterns with diacritics broken (if zim has no fulltext index)

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#547]
See here:
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/b88b74ac-091b-48e4-885e-1823f901717a">

We get results only for Wiktionary and none for dwds…. But:
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/b286deca-80ff-4181-902b-823a7c9c1602">

… the only clear difference is that dwds zim has not fulltextindex whereas wiktionary has… I guess this is the reason of the problem.

This is a apple only bug, as such a problem does not happen with other versions of Kiwix.

**Comment by kelson42** [comment]
Surprisingly it seems to work with nightly macOS version…. So maybe this is already fix in git main head and only testflight version is impacted.

**Comment by kelson42** [comment]
I can not reproduce this problem with testflight of DWDS, I guess it has been fixed with the usage of libkiwix13.

**Comment by tvision251** [comment]
I tried to reproduce an issue, but it works well.

**Comment by kelson42** [comment]
@tvision251 tThank you! We should probably consider to upload a new testflight of Kiwix for iOS soon. That would avoid this kind of problem.
