### ISSUE TITLE
Improve first time install app launch (both iOS and macOS) for custom apps

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#551]
> on MacOS 12.7.1, works very well except that on first start the main page is not always displayed, I sometimes need to click on the “Home” button to display it. But this is “not always” the case

> when the main page is not displayed, the viewer part of the app just stay blank

> and title in the upper left is not set

**Comment by kelson42** [comment]
@BPerlakiH What is the status here? Which PR fixes this?

**Comment by BPerlakiH** [comment]
@kelson42 it has been merged to main within this PR: https://github.com/kiwix/apple/pull/576
It is also included in the TestFlight releases from build 125 (and above).
