### ISSUE TITLE
[Custom] Update / configure About page content

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#553]
On a custom app, we might need to have the About page content configurable. Currently it is Kiwix specific only.

<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/c9b0315a-94ec-4ad0-89aa-cd8ca0ee3a43">

**Comment by BPerlakiH** [comment]
Do we have an updated text for DWDS that I could use for here?

**Comment by kelson42** [comment]
@BPerlakiH Looks at https://github.com/openzim/dwds/issues/8#issuecomment-1841179479 please

**Comment by BPerlakiH** [comment]
I cannot see that link (404), can you check if it is the correct one please?

**Comment by kelson42** [comment]
@kelson42 Text for the About panel:

> Für Schreibende, Lernende, Lehrende und Sprachinteressierte: Das Digitale Wörterbuch der deutschen Sprache (DWDS) ist das große Bedeutungswörterbuch des Deutschen der Gegenwart. Es bietet umfassende und wissenschaftlich verlässliche lexikalische Informationen, kostenlos und werbefrei. 

Link should go to our main site: https://www.dwds.de/

**Comment by BPerlakiH** [comment]
Implemented in build 128.
Changes towards the main repo in this PR:
https://github.com/kiwix/apple/pull/584

DWDS custom PR reference was also updated with these changes:
https://github.com/kiwix/apple/pull/582
