### ISSUE TITLE
Custom DWDS apps bookmark marker seems broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#555]
In Kiwix, fi the current page is bookmarked, the bookmark “star” icon is yellow, to show that this page is already bookmarked.

But for an unknown reason, this seems to fail on the DWDS custom app, the bookmark “star” icon stay “like normal”. No differrence there wether the page is or is not bookmarked.

<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/891bda03-2731-48b8-a1f0-f87bd9d36832">
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/891f23e2-9264-4297-aa25-6664e47774d1">

**Comment by BPerlakiH** [comment]
It seems we have the same issue on the kiwix app, it is also not always working / updating, will have a look.
