### ISSUE TITLE
Change and hide “External link” in Custom DWDS app Setting

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#556]
The option makes sense in general for custom apps, and as such it should be kept like it is.

But for the DWDS, there is a special handling done in the pages themselves. Therefore we should:
* Set the setting to “Always load”
* Hide the settings

Therefore ultimatively this should be configurable for each custom app via the `info.json`.

<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/897a8c02-c79c-4a95-ad1c-30b681062be5">
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/e6580408-046b-49b6-a674-84305320e106">

**Comment by kelson42** [comment]
@BPerlakiH Status, which PR has fixes this?

**Comment by BPerlakiH** [comment]
@kelson42 it has been merged to main as part of the PR: https://github.com/kiwix/apple/pull/576
It is also included in TestFlight from builds 124 (and above).
