### ISSUE TITLE
Download of books in macOS is wicked!

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#557]
The download workflow is buggy at many levels IMO:
* Once you have chosen what to download, you click on download but nothing happens, the "download" button does not disappear, your are not moved to the "Downloads" tab. You might believe that nothing has happened.
* If you reclick on the "Download" button, same behaviour, but I actually believe it start a new download for the very same book in background
* If you go to the "Download" tab, you will actually see your download which seems to be done properly... but actually the progress bar is not update, there is no refresh at all of this page looks like. You have to leave the "Downloads" tab and come back to see progresses.
* So far, there is no way to cancel/pause the download... as the corresponding button are not displayed!

Tested with latest nightly on macOS 12.

On iOS things seem to work just fine.

**Comment by BPerlakiH** [comment]
It affects both iOS and macOS. Bug seems to be introduced just after the 3.2 app store release.
