### ISSUE TITLE
Custom apps versions should be time based

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#559]
Custom apps versions should be the same as the content. For example `2023-11`.

**Comment by BPerlakiH** [comment]
Maybe it's possible to do so.
According to Apple docs (taken from [create a new version docs](https://developer.apple.com/help/app-store-connect/update-your-app/create-a-new-version)):

> version number
> The version number ([CFBundleShortVersionString](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring)) is a user-visible string that represents the bundle version with a required format of three period-separated integers (0-9).
Each integer provides information about the release in the format [Major].[Minor].[Patch]. For example, in 10.14.1, 10 is the major revision number, 14 is the minor revision number, and 1 is the maintenance release number. This string is used throughout the system to identify the bundle version and should match the version number you enter in App Store Connect.

We can think about how to squeeze in the date into that format (eg. maybe using [Major].[Minor] to hold the date). 
Possible side effects: it would leave us with less space for updates in cases of:
- update not related to the content itself (eg. 2023.11.1 + a bug fix would be => 2023.11.2, even if it's released 6 months later)
- content updated more frequently than 1 month (eg 2023.11.1 + very same code but new content would also give => 2023.11.2)

**Comment by kelson42** [comment]
Agree with your proposal

**Comment by BPerlakiH** [comment]
It is address in the PR: https://github.com/kiwix/kiwix-apple-custom/pull/9
