### ISSUE TITLE
App crashes silently when it has 1 complete copy + 1 partial download of same ZIM file

### ISSUE THREAD

**Issue by practik** [kiwix/apple#56]
Steps to reproduce:

1. Begin direct download of ZIM file onto iPhone from Kiwix library interface.
2. Pause download and close Kiwix app.
3. Load complete copy of same ZIM file into Kiwix via file sharing from computer.
4. Open Kiwix app: it will silently crash within seconds – or at least it did for me, very consistently, and I tested it with a few different ZIM files.

How I encountered the problem:

I just installed Kiwix for the first time this week. I tried a few times to download `wikipedia_en_all_nopic_2017-01.zim` directly onto my phone, but the download always failed at some point. So I downloaded the file to my computer using BitTorrent and copied it onto the phone using iTunes – which crashed Kiwix.

Eventually I realized that I had never canceled my last direct download – but before I could discover that, I first had to remove the complete ZIM file from the phone so that I could get back into Kiwix. This situation seems easy for other new users to get into and hard for them to get out of.

**Comment by automactic** [comment]
Ahhh, good catch @practik!

**Comment by practik** [comment]
Cheers – and thanks to the team for Kiwix, I'm glad I found another way to contribute!

**Comment by kelson42** [comment]
@automactic What is the status on that bug?

**Comment by kelson42** [comment]
@automactic Any update?

**Comment by kelson42** [comment]
@practik @automactic Would be good to knpe if this bug still happens

**Comment by practik** [comment]
I'm now using an older phone that's not capable of running Kiwix, so unfortunately I'm not able to test this at the moment. I'll check back in when/if that changes.

**Comment by kelson42** [comment]
AFAIK this bug has been fixed.
