### ISSUE TITLE
Ability to download missing?

### ISSUE THREAD

**Issue by ronaldpetty** [kiwix/apple#562]
Hello,
I am a new user (thanks to Hacker News). When confronted with the first iOS screen to fetch categories, it worked. I picked one, it downloaded; I do not see any way to download anything else. I uninstalled and tried again, this time picking multiple categories and it seems to download one but then I see nothing else, nor can I get back to that screen where you pick and view downloading/cancel. I click all the ungreyed nav buttons and the only thing to do is view one that downloaded or add new tab but nothing else.

iPhone 14 pro max, iOS 17.1.1

I hope its user error!

**Comment by kelson42** [comment]
@ronaldpetty Hi, I'm not sure to get your righ, but you can not download a full category but only a book. Once you have picked one you should see the "Cancel" and the "Pause" buttons appearing and the download progress should be displayed. Do you achieve to get to that point?

**Comment by ronaldpetty** [comment]
Sorry if I am using the wrong term. I can't find any button to click to download more things is the core issue I think.

![image](https://github.com/kiwix/apple/assets/1390435/3e6a78cc-272b-4f67-a3d1-b5b49fe9dfc0)

**Comment by kelson42** [comment]
@ronaldpetty I see, I believe you are impacted bybthis usability problem reported here https://github.com/kiwix/apple/issues/532

**Comment by ronaldpetty** [comment]
@kelson42 that link helped. I had no idea it required a long press; now I see other menus. Here is the comment that stated that could be it. I learned something new today (long press). Thank you, look forward to trying it out.

https://github.com/kiwix/apple/issues/532#issuecomment-1806839181
