### ISSUE TITLE
Add iOS App Development cert to CI

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#566]
It's quite frequent that CI fails trying to communicate with Apple to retrieve certs for building iOS.
We should add an `iOS App Development` certificate to the CI instead so it doesn't need Apple servers to sign in the CI.

**Comment by kelson42** [comment]
@rgaudin @BPerlakiH is this ticket not already implemented?

**Comment by kelson42** [comment]
@rgaudin What is the status here?

**Comment by rgaudin** [comment]
This is now obsolete I think. We don't have an `iOS App Development` in use in CI but we do have an `Apple Development` one. CI hasn't failed in a very very long time. We must have worked around the issue somehow. Closing.
