### ISSUE TITLE
On Wikivoyage clicking on a phone link should make a call

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#57]
Currently nothing happens at all.

**Comment by automactic** [comment]
On my iPhone and iPad, phone numbers are detected correctly. 
![img_0029](https://cloud.githubusercontent.com/assets/8294252/25090723/f0056fa0-2352-11e7-98e5-1a9d88db39c0.PNG)

**Comment by kelson42** [comment]
This will be checked this summer, 1.8.1 descoped.

**Comment by kelson42** [comment]
After investigation with @automactic, the most probable explanation is that without a SIM card in the iOS device, iOS just "block" this feature.

**Comment by kelson42** [comment]
@automactic Fell free to close this ticket if you feel there is nothing more you can do about it.
