### ISSUE TITLE
Fix "lego" messages download_service.complete.description and file_import.alert.no_open.message

### ISSUE THREAD

**Issue by amire80** [kiwix/apple#585]
The translatable messages download_service.complete.description and file_import.alert.no_open.message appear to work by getting concatenated. This is an antipattern in localization, and should be avoided (in the translatewiki.net jargon, it's called "lego messages").

The right way to do it is to pass the missing things as parameters, and embed them using `$1`, `%1`, or whatever is the right parameter format to use in iOS.

Thanks! :)

**Comment by kelson42** [comment]
@BPerlakiH Do you agree? Can younplease fix it?

**Comment by BPerlakiH** [comment]
addressed in PR: https://github.com/kiwix/apple/pull/598
