### ISSUE TITLE
Unable to view catalog again after downloading a wiki.

### ISSUE THREAD

**Issue by chaoticryptidz** [kiwix/apple#593]
There doesn't seem to be any way to delete or browse for more wikis once one has been added. Is this a regression in the iOS app or has it always been broken?
on iPhone 15 Pro Max on iOS 15.2 and latest version on store as of time writing.
![IMG_2632](https://github.com/kiwix/apple/assets/29613512/58963f38-b14e-49a6-8f1c-ac0dfc337aa6)

**Comment by kelson42** [comment]
@chaoticryptidz Thank you, not the same bug as reported in #532?

**Comment by chaoticryptidz** [comment]
Yes this appears to be a duplicate of #532, the workaround in that works for now but isn't very intuitive compared to most iOS apps menu design. VoiceOver doesn't even announce the tabs button has a hold action.
Feel free to close this issue if don't want duplicate.
