### ISSUE TITLE
Proper handling of UI languages

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#603]
Kiwix is now able to handle many languages and the syncrhonisation with Translatewiki has been achieved. But it is still important that the "correct" language is chosen to display the UI:
* Custom apps
  * `enforced_lang` lang is specified in the `info.json`
    * UI language should not be customizable (in the OS - but app related - settings)
    * UI language should be the one specified in `info.json`
  * Otherwise works like the Kiwix app
* Kiwix app
  * UI languages should be configurable (in the OS - but app related - settings) on iOS (but nothing for the moment on macOS, see #604)
  * Default language should be the one of the OS

This is valid for iOS and macOS.

**Comment by kelson42** [comment]
@BPerlakiH Do you confirm this is clear? This makes sense? Does it already works like this?

**Comment by rgaudin** [comment]
there is no such thing as app préf in OS for macOS. It's only iOS

**Comment by kelson42** [comment]
> there is no such thing as app préf in OS for macOS. It's only iOS

Then, no way to configure the UI language for the moment. I have open [an other ticket](https://github.com/kiwix/apple/issues/604) for this enhancement (not a priority for the moment).

**Comment by BPerlakiH** [comment]
Thank you @kelson42 it makes sense. 
This really means we can should include only the enforced language in the custom app.
I will reflect these changes in the latest release.

**Comment by BPerlakiH** [comment]
I've created the releases for DWDS app 2023.12.3 (build 133) to reflect these changes, and created a PR to revert the unnecessary changes in the main repo: https://github.com/kiwix/apple/pull/605

The project level (automatic) handling of the enforced language will be included on the kiwix-apple-custom repo side.
