### ISSUE TITLE
CD is broken since two days!

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#624]
https://github.com/kiwix/apple/actions/workflows/cd.yml

**Comment by rgaudin** [comment]
It seems we overlooked https://github.com/kiwix/apple/pull/618 as the retry exit code for the DMG was ensuring we wait until the notarization is complete. This must be restored

**Comment by BPerlakiH** [comment]
The fix is here: https://github.com/kiwix/apple/pull/625
