### ISSUE TITLE
Use Fastlane for app builds

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#638]
We would like to replace our current builds steps with Fastlane, and handle our CI and CD steps with it.

**Comment by kelson42** [comment]
Any PR in draft already?

**Comment by kelson42** [comment]
@BPerlakiH We decided to not go forward with Fastlane. Please but details about what you tried and stay behind the decision.

**Comment by BPerlakiH** [comment]
## Fastlane summary

### Code signing

Fastlane and code signing seemed promising for simplifying our automated build process, but in practice, it didn't meet our needs. Apple's cloud code signing eliminates the need for distribution certificates on developer machines. Additionally, integrating with GitHub and GitHub Actions had several issues:
  - github access token cannot be directly used on to access code-siging repository. Alternative that was found is that as a CI step [we can directly checkout the code-signing repository](https://github.com/kiwix/apple/tree/daec6565b69899fcb2c8c1ed7c0059155c682efe), and [point match to that  copy](https://github.com/kiwix/apple/blob/f1e043f7a49180d2f57561ac18dabeb457d694b0/fastlane/Fastfile#L52-L58).
  - Manual code signing failed on GitHub Actions but worked for me locally. This raises concerns about the benefits of externalising these steps to (yet another language) ruby, as ideally the same fastlane script should work both locally and on CI
  - match by default ignores the default branch of the code-signing repo, and uses "master" instead of our current default "main".
  - additionally for macOS code-signing only one Developer ID can be created per apple account, which we already have, and that was not included on the code-signing server, therfore it wasn't working, nor it could create a second one.
  - match is suppose to be working the best when it is applied on a fresh developer account with no certificates and profiles, or when all existing ones are `nuked`. This is not something we can risk to do, since we already have a working CI / CD flow.
  - match supports, and encourages "manual code signing", meaning we specify which profile to use, in theory that seems OK. Reality showed that match can include all developer certificates in a developer profile, however when creating a distribution profile it will automatically pick the first certificate it finds, which might not be ideal (eg. the working one is not even under the same developer account). The proposed solution by match is to have a dedicated apple developer account for match only (again, we don't want to start from scratch) or to visit developer.apple.com and edit the profile, and select the correct one (which might not be even under the same developer account). Since the profiles might be automatically re-created (eg. new devices / certificates added), this is defeating the automated purpose of match for us.
  - for automatic code signing, fastlane do not provide a built in parameter to use: `-allowProvisioningUpdate`, the work around was to use a "barely" documented: 
  `xcargs: "-allowProvisioningUpdates ..."`
  as it can be seen here:
https://github.com/kiwix/apple/blob/daec6565b69899fcb2c8c1ed7c0059155c682efe/fastlane/Fastfile#L30
  - what could be achieved so far was to use the current code-signing from Github secrets, add those to the key-chain, pass it down as params to fastlane, and build the iOS application, with a successful build here: https://github.com/kiwix/apple/actions/runs/7749133820/job/21133076727
  the related working state of the branch can be found here: https://github.com/kiwix/apple/tree/daec6565b69899fcb2c8c1ed7c0059155c682efe
  
  Overall experience with fastlane was that it comes with a lot of defaults, that sometimes documented, sometimes can only be found in the source code. Some of these defaults are out of date. At very end of the "lane" it outputs the `xcodebuild` commands it uses to build things, which was compared with the output of our existing working solution. The process was unecessaraly complicated and full of surprises.
