### ISSUE TITLE
Make ZIM file (cloud) backup configurable

### ISSUE THREAD

**Issue by practik** [kiwix/apple#64]
I see that Kiwix 1.8.1 was supposed to fix this, but for me, at least, it hasn't done so. I'm running iOS 10.3.1 on an iPhone 5. I've tried making backups with both iTunes 12.6.0 and iMazing 2.2.6, and neither one includes the ZIM file. I don't use iCloud.

**Comment by automactic** [comment]
This is by design. I have previously received complaints from user said that the zim file got backed up and making their iCloud backup failing. Maybe we could add a setting to keep everybody happy

**Comment by practik** [comment]
Ah, okay, good to know. Speaking only for myself, it's fine if the ZIM file is not included in the backup – I just thought it was supposed to be included because that's what the release note for 1.8.1 seems to be saying.  If it's not too late to edit that note, then maybe

> - Fix: zim files no longer got backed up to iCloud ot iTunes

should be changed to 

> - Fix: zim files no longer **get** backed up to iCloud **or** iTunes

By the way, and off-topic, I really like that Kiwix now remembers my scroll position when I come back to a page – great improvement!

**Comment by automactic** [comment]
@practik Thanks to your suggestions, kiwix keep getting better. Keep'em coming! 😊

**Comment by automactic** [comment]
@practik The release note is fixed, though it may take a while for the change to appear on all store fronts. Thanks again for the feedback!

**Comment by practik** [comment]
My pleasure! I'll leave it to you to decide when to close this issue since I'm not sure whether you want to add a setting as you mentioned above. Thanks for all your work!

**Comment by automactic** [comment]
@practik, a toggle will be added to the next release of the app (v1.9).

**Comment by kelson42** [comment]
@automactic Looks like we have a toggle in 1.9. I have fixed the wrong sentence in the changelog. Should we close the ticket?

**Comment by automactic** [comment]
I will rebase 1.9 dev branches onto master

**Comment by jberkel** [comment]
Just had a failed iCloud backup after installing a 4GB ZIM file, cloud backup is disabled in Kiwix settings. IOS 13. Looking at the code, the exclude flag only gets set after the file has been opened, and is set per file. I started the install and then put the app into the background, so it was installed but not excluded.

Perhaps it would be easier to create a separate directory for the `zim` and `idx` files and set `isExcludedFromBackupKey` globally for that directory?

**Comment by kelson42** [comment]
@jberkel Not 100% sure, but I think it might be better to open a new ticket here.
