### ISSUE TITLE
Search result titles are displaying HTML tags

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#640]
Within the Kiwix iOS application the returned search titles contain html tags, that are displayed without decoding.
These tags should be removed from the search result titles.
The initial attempt to do this via `NSAttributedString` is very slow. Around 500ms per 35 results, which is a visible delay for the user. It is multiple times longer than the actual search, which is not an acceptable solution.
Other devs also had issues with this naive attempt, see here: https://stackoverflow.com/questions/31852655/very-slow-html-rendering-in-nsattributedstring

The way it currently looks for certain search results:

![Image](https://github.com/kiwix/apple/assets/6784320/61dfeb67-6e5a-49cb-b389-79aacddce6d0)

**Comment by kelson42** [comment]
@BPerlakiH This is a problem which has nothing to do with this repo in my opinion.
