### ISSUE TITLE
Older version of iOS are not supported anymore

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#65]
Apple releases one time a year a new version of iOS with the corresponding SDK which brings each time new features and improvements for both Kiwix developers and users. We tend to use this improvements as we keep our app up-to-date.

The problem is that iTunes does not (or almost not) provide older version of Kiwix to older version of iOS. Because certain hardware simply are not able to upgrade to ios10 (first ipads for example) the users do not have access anymore to Kiwix.

**Comment by kelson42** [comment]
Idea, re-publish older version of Kiwix.

**Comment by okkebal** [comment]
That would be great, please repubish them. I just wanted to install Kiwix on an ipad2. No luck.

**Comment by automactic** [comment]
As per our discussion in the [halkathon](http://off.network), we will support both the latest and previous major release in the future. So starting when iOS 11 is released, we will support both iOS 10 & 11. Although, if time permits, we might find a way to support older versions.
