### ISSUE TITLE
Fix default language for Feed filtering

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#651]
Our feeds when returning the list of zim files, that can be downloaded, we filter those by the current language set in the app.
Since the app is setting the language as a 2 char language code, it cannot filter the zim files properly.

Ideally we should use 3 char language code as a default in our app, it is possible out of the box for iOS 16 and above, and requires a bit of a workaround for iOS 15.

**Comment by kelson42** [comment]
So you have no straight primitive to convert between the two ISO norms? Libicu is not made available by Xcode?

**Comment by kelson42** [comment]
I think we should think a bit about this problem first:
* I‘m not in favour to apply a filter differently to what is specified in app settings
* If language filter is empty then we should display all books
* We should do our best to setup language filter settings per default (so as long as user as not decided differently)
* Your approach seems OK, considering iOS 15 will be deprecated soon, but should apply to settings default conf

**Comment by rgaudin** [comment]
https://cocoapods.org/pods/ISO639

**Comment by rgaudin** [comment]
> https://cocoapods.org/pods/ISO639

Sorry it's not maintained. I suppose there are other options. Should there not be any swift-ready packages, a C/C++ one could be used… but it might not be worth the effort given iOS15 is very old and only iPhone up to iPhone7 are locked on it (released between 2016 and 2017)

**Comment by BPerlakiH** [comment]
## Settings

In the settings we list the languages the user can filter on.
At the moment, it is done in a way that the list of languages comes from the list of zim files, we have, and it is counting how many times a specific language appears (using the <language> property of each <entry>.)
Which is in-line with our requirements that we should base the list of languages in the settings on zim files and not the system languages.

Side effect is, that on a fresh install, withouth fetching the catalog, the list of languages is empty (since we do not have a source list yet).

This must be the reason why the default language is set at "fetch time".

## Assumptions

One approach discussed was to display all content, if no language is selected. 
When trying this, the content became very bloated with lots of duplicates. It is not a user friendly solution.

## Proposed solution
The bug we had was that default language set, was filtering out everything (an invalid code).

What we really want is:
- we always display some content (no hidden default filtering to zero items)
- we adopt the user's preference - if that's possible

If no content is fetched yet, there's no language set. This is fine, we leave it as it is.
Once we have content, we pick the device language (if possible) if that is on the list of languages dictated by the content. In all other cases we fall back to English (where we have the most content).

## Corner case
There's one corner case, as the current language picked by Apple `Locale.current` is filtered down by the localisations we provide with the app (see translatewiki). This somewhat makes sense, but produces the side effect, that although the user's phone is set to eg. Polish, and we have wiki content in Polish, it will fallback (by default) to English, because the application is not yet translated to Polish.
We can put some reasoning behind this, as we might want the app to be either fully localised or not.
Again, we are talking about the defaults here, the user can always set a different language in settings, and get the relavant content filtered.

## Follow up
The other improvement we could do is to filter the displayed categories automatically, so we do not display empty ones. Eg. for a language with less content, some of the categories will become empty. We want the user to find content in an easy way.

**Comment by kelson42** [comment]
@BPerlakiH Thank you for the explanation. All of this makes sense. Ideally the list of supported languages shoudl comes from API https://kiwix-tools.readthedocs.io/en/latest/kiwix-serve.html#catalog-v2-languages. Once we will stop to download the whole catalog, then the support of this end-point will have to be done (this would also allow to decouple fetch of books and fetch of languages).
