### ISSUE TITLE
Add "Support Kiwix" item to menu

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#660]
Our Android App has a `Support Kiwix` element in its hamburger menu. Android-related donations constitute about a quarter of all the support we receive from individual users. 

Can we please add a similar link to https://support.kiwix.org to the iOS app?

![supportus (1)](https://github.com/kiwix/apple/assets/21675885/81caf877-7c62-4a5f-be2e-51866325f5d3)

**Comment by kelson42** [comment]
This also has to be customisable for custom apps. Need to find corresponding issue for Android because we have to do the same.

**Comment by DobleV55** [comment]
Hi there,

I've begun working on this project, and I want to make sure we're aligned on the button design. Could you please clarify your preference for the button style? I've attached an image with two options, but feel free to suggest any other alternatives that you might prefer.

Looking forward to your feedback!
![frame](https://github.com/kiwix/apple/assets/24664579/add96ba7-3291-4525-84bb-5b46fd6c09bc)

**Comment by Popolechien** [comment]
I'd favour option 2 but the wording should probably be "Donate to Kiwix" or "Support Kiwix". I would suggest looking at other free apps (Signal?) that have similar donation prompts and see how they word it.

This might warrant a ticket of its own, but could we have the donation CTA rotate between 2-3 wordings (and links) so we can A/B test the most efficient ones?

**Comment by kelson42** [comment]
> I'd favour option 2 but the wording should probably be "Support Kiwix" I guess.

Wording and way it works should be exactly like on android. Don't reinvent anything.

**Comment by DobleV55** [comment]
Thank you for all your replies and feedback. Based on your input, I'll be replicating the 'Support Kiwix' button flow from Android.

**Comment by DobleV55** [comment]
Hi 👋🏻 ,

While creating the button, I encountered the following issue: When clicking on a link or button with an external link, it works correctly the first time. However, upon clicking it a second time, it no longer functions unless you click on another link or button that directs to an external link.

Should I create an issue to address this?


https://github.com/kiwix/apple/assets/24664579/2e74cc07-6f1d-46c1-ac10-b429ae97e557

**Comment by Popolechien** [comment]
yep, thanks for the video. Looks like a separate issue to me, so yes please open a new one (unless you have reasons to assume that your fix created the issue).

**Comment by kelson42** [comment]
@BPerlakiH Can you please guide/help @DobleV55 ?

**Comment by DobleV55** [comment]
Hi, apologies for the delayed response. 😅 I'm in the UTC-3 timezone. I'll create the issue now and upload the PR with the completed "Support Kiwix" button.

**Comment by DobleV55** [comment]
Apologies, this is my first time contributing to an open-source project. How do I upload the changes? I forked the project and created a [branch](https://github.com/DobleV55/apple/tree/660-add-supp%E2%80%A6item-to-menu), then pushed the changes there. However, I'm unsure if this is the correct procedure.

**Comment by BPerlakiH** [comment]
Hi @DobleV55,
Thank you for the changes.
You can create a Pull Request here:
https://github.com/kiwix/apple/compare/main...DobleV55:apple:660-add-supp…item-to-menu

From the changes, I can see that you can remove the "Brewfile.lock", those changes are not needed.
I will look into that, maybe we should add that file to .gitignore, to avoid confusions.

**Comment by BPerlakiH** [comment]
Please do not hard code these colours as of your PR, the image should work without any modifier, while the text should work in both "Dark Mode" and "not Dark mode" as well (where the white text is not visible enough).

**Comment by DobleV55** [comment]
Hi @BPerlakiH ,
Thank you for the feedback. I've updated the PR #705  to remove the hardcoding of colors. Now, the text should be visible in both "Dark Mode" and "Light Mode". Please feel free to let me know if there are any further adjustments required 🤗

**Comment by DobleV55** [comment]
Hi,
Do you think this approach works well for the app?

![supportios](https://github.com/kiwix/apple/assets/24664579/80acee7c-637c-4d02-bfb2-4592cc731934)

**Comment by DobleV55** [comment]
The code for the mobile version of the "Support Kiwix" button has been uploaded. Please let me know if you think any modifications or additions are necessary, or if it is already somewhat finalized. Thank you very much ❤️
