### ISSUE TITLE
Feed fix for language changes

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#663]
I did test the following scenario:
- clean up everything, download the AppStore version
- update it via TestFlight to our latest release candidate

We have the following problem, the user's default / selected language will get updated properly, once the catalog is fetched, yet
the user will still face an empty list of categories.
The reason is the following:
- the feed now returns 3 char language codes, the default / selected language is also in this format. So far so good.
- the listing of the categories are based on what is stored in the local DB
- the DB won't get updated with the new language values coming from the feed, it is only comparing if the DB has entry for the given ZIM file
- the DB entry remains with the old language values: eg: "en",
- while trying to list the categories, we will search for eg: "eng"
- result: nothing is displayed for the user

**Comment by kelson42** [comment]
> the listing of the categories are based on what is stored in the local DB

It's hardcoded? Where does the information comes from as this DB has to be filled at dome point?

**Comment by BPerlakiH** [comment]
It is not hardcoded.
We are talking about a user that upgrades the app.
Yes, the DB is filled in with the entries in the current AppStore version of the app.
The problem is that we only check for the ZIM file ID if exists or not.

**Comment by BPerlakiH** [comment]
We have the full meta data of each ZIM file in the DB.
The interesting part for this ticket is the ID and the language.
The user already has this eg:

|quote(ZFILEID)	|ZNAME	|ZCATEGORY	|ZFLAVOR	|ZLANGUAGECODE|
|----|----|----|----|----|
|X'746C75B67DAC87D962DBAB5542F6FE7B'	|Wikivoyage	|wikivoyage	|nopic	|en|

now the feed has the same file, with the same ID, but the language is: "eng":
```
<entry>
    <id>urn:uuid:746c75b6-7dac-87d9-62db-ab5542f6fe7b</id>
    <title>Wikivoyage</title>
    <updated>2024-02-13T00:00:00Z</updated>
    <summary>The collaborative travel guide</summary>
    <language>eng</language>
    <name>wikivoyage_en_all</name>
    <flavour>nopic</flavour>
    <category>wikivoyage</category>
    <tags>wikivoyage;_category:wikivoyage;_pictures:no;_videos:no;_details:yes;_ftindex:yes</tags>
    <articleCount>32417</articleCount>
    <mediaCount>34</mediaCount>
    <link rel="http://opds-spec.org/image/thumbnail"
          href="/catalog/v2/illustration/746c75b6-7dac-87d9-62db-ab5542f6fe7b/?size=48"
          type="image/png;width=48;height=48;scale=1"/>
    <link type="text/html" href="/content/wikivoyage_en_all_nopic_2024-02" />
    <author>
      <name>Wikivoyage</name>
    </author>
    <publisher>
      <name>openZIM</name>
    </publisher>
    <dc:issued>2024-02-13T00:00:00Z</dc:issued>
    <link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim" href="https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_nopic_2024-02.zim.meta4" length="254736384" />
  </entry>
```
The problem is that after downloading and parsing the feed, it finds the entry by ID, and skips it, since we already have that in the DB,
and the language field won't get updated.

When we want to display the categories, it searches by the current language using a query more or less:
```
SELECT ... WHERE  ZLANGUAGECODE IN  ["eng"]
```
and nothing is found.

**Comment by kelson42** [comment]
So this is the category listing applying to the local library?

In general, the problem is worse than it looks like. The underlying question is: Once we have downloaded a ZIM, should we display the metadata linked to the ZIM coming from the feed, or the one saved at the time the book has been introduced in the local library?

But I guess ultimatively, this is more a question for the libkiwix. @mgautierfr How does the libkiwix behaves on this?

@BPerlakiH For the monent, I recommend to introduce a temporary fix which update the lang in local library when necessary. This fix to be removed (put a comment on code and create dedicated issue) in a few releases.

**Comment by BPerlakiH** [comment]
I have done a fix for this, which works for both new users = fresh installing the latest version of the app,
and for updating users = those who have the AppStore version already

So the problem also occurred, because the application was relying on the fact that the ZIM fileID will ultimately identify the file,
whereas the feed content changed at some point, and now the feed is using alpha-3 language codes.
The other question is do we know why/when the feed was updated? We need to be more cautious about similar changes, as they can break the apps that are already in the AppStore.
Another thing is: if we change the feed in a similar fashion for the other fields, we might bump into a similar problem again...
One posible solution for avoiding these cases is a versioned API eg.: `...content/v1/feed` and `...content/v2/feed`, but that also comes with additional maintenance overhead on the back-end side.

**Comment by BPerlakiH** [comment]
We have about 25 fields for each ZIM file in the DB eg:

| Z_PK | Z_ENT | Z_OPT | ZARTICLECOUNT | ZHASDETAILS | ZHASPICTURES | ZHASVIDEOS | ZINCLUDEDINSEARCH | ZISMISSING | ZMEDIACOUNT | ZREQUIRESSERVICEWORKERS | ZSIZE | ZDOWNLOADTASK | ZCREATED | ZCATEGORY | ZFILEDESCRIPTION | ZFLAVOR | ZLANGUAGECODE | ZNAME | ZPERSISTENTID | ZDOWNLOADURL | ZFAVICONURL | ZFILEID | ZFAVICONDATA | ZFILEURLBOOKMARK |
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
1 | 4 | 1 | 8 | 1 | 1 | 1 | 1 | 0 | 24 | 0 | 313540608 | 0 | 2021-01-19 00:00:00 +0000 | ted | Designer Isaac Mizrahi dashed off these stylish, breezy notes on why these 6 TEDTalks are a source of inspiration for him. |  | eng | Isaac Mizrahi: Talks that are in fashion | ted_en_playlist-isaac-mizrahi-talks-that-are | https://download.kiwix.org/zim/ted/ted_en_playlist-isaac-mizrahi-talks-that-are_2021-01.zim.meta4 | https://library.kiwix.org/catalog/v2/illustration/80c9f981-09ea-69a9-a87e-10aa8283ba05/?size=48 |

**Comment by kelson42** [comment]
After disscussion, the solution should be here to run once (only after update) a special function to remove old online (not local) entries of the DB, so at next sync, then everything will be repopulated. Of course once the DB is cleared from online entries, something should be done to redownload the online feed ASAP.

**Comment by mgautierfr** [comment]
> In general, the problem is worse than it looks like. The underlying question is: Once we have downloaded a ZIM, should we display the metadata linked to the ZIM coming from the feed, or the one saved at the time the book has been introduced in the local library?
>
> But I guess ultimatively, this is more a question for the libkiwix. @mgautierfr How does the libkiwix behaves on this?

I would say that libkiwix doesn't behaves at all on this.
The `kiwix::Library` is either feed with opds stream or `library.xml`[*] (saved library). So metadata come from the input.
And on an existing (potentially empty) `Library` you can also add a book (and so metadata come from the book).

At the end, libkiwix doesn't choose. It is an application decision.

---

[*] When loading a `library.xml`, we have a boolean `trustLibrary` (true by default).
When it is true, we trust the library metadata. If false, we open the books to get the metadata from them. (This can be pretty low, so it is false by default to allow quick startup of kiwix-serve (and not open hundreds  of zim files for "nothing")

**Comment by BPerlakiH** [comment]
Fix is included in: https://github.com/kiwix/apple/issues/668
