### ISSUE TITLE
Incoherency in Settings (and empty list of books to download)

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#664]
After updating to latest testflight.

My online list of books was empty.

My settings show „French“
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/d1dfa618-0740-4841-88b0-7150c358dbf2">

But once I display the list, french is not selected anymore
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/ed76fca2-b134-4751-b07e-e5d857cb8240">

I should see french books and settings should be coherent

**Comment by BPerlakiH** [comment]
Fix is included in: https://github.com/kiwix/apple/issues/668
