### ISSUE TITLE
Update 2 letters language code settings to 3 letters

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#667]
Should applied just right after the new update (run once):
* on iOS15: based on an ad-hoc hardcoded mapping list of X importances languages codes, apply the update. If no matching is found, then remove the language code. If at the end, list of preferend languages is empty, will default to `eng`.
* on iOS16+: use native primitives to convert to 3 letters language code.

This piece code should be removed after a few additional releases:
* Create a dedicated issue for that
* Put clear comment in the code that this is temporary code

**Comment by BPerlakiH** [comment]
Fix is done as of: https://github.com/kiwix/apple/issues/668

**Comment by BPerlakiH** [comment]
Fix is included in: https://github.com/kiwix/apple/issues/668
