### ISSUE TITLE
Fix root cause of language problems

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#668]
After throughout analysis, why the AppStore version is working as it is, what were the changes in the meantime.
I did found the following:
- it all started with: https://github.com/kiwix/apple/issues/588
- I removed the deprecated function in https://github.com/kiwix/apple/pull/629/files
- The former function was returning a single string, whereas the new one might return a comma separated list of strings.
- The mapping from a list of strings to a list of Locales, was done a "level higher" not in the objective-c function but in swift.
- The result is that the objective-c function was in fact converting the language codes from the feed to a 2 letter language code (across all iOS versions), and that is what we were storing in the database, which is accidentally or purposefully but in an undocumented way is working
- When adding the swift function I was checking against the feed values, and from [that PR](https://github.com/kiwix/apple/pull/629/files) on the DB was using 3 letter codes.
- Unfortunately the unit-tests were not run by me on that PR, the CI is currently not running them
- The tests were updated at a later point in time here: https://github.com/kiwix/apple/pull/652/files#diff-edd62679239139566e8891207312793f6afaf35c590661caebec8c72f81bbfc3

## Proposition
The simplest, and most straightforward solution at this point is, use the existing working solution and store the language codes as 2 letter codes, apply the same for user settings. This solves the issue with iOS 15 and below, without having to manually map codes, as suggested in: https://github.com/kiwix/apple/issues/667

**This purposeful workaround has to be clearly documented in code.**

To avoid similar problems in the future, we need to make sure [unit tests are run during CI builds](https://github.com/kiwix/apple/issues/669) (issue created)

**Comment by BPerlakiH** [comment]
@rgaudin I put the ISO-3 migration into a PR on top of this, see: https://github.com/kiwix/apple/pull/672
I discovered even more things, and implemented in a more consistent way.

**Comment by rgaudin** [comment]
So maybe close this one?
