### ISSUE TITLE
Building MacOS failed

### ISSUE THREAD

**Issue by conky2** [kiwix/apple#69]
Hi, I get the following error when trying to build for MacOS

![screen shot 2017-09-08 at 6 58 51 pm](https://user-images.githubusercontent.com/25021281/30234044-d46692ce-94c7-11e7-8c33-baed77496a23.png)

**Comment by automactic** [comment]
In swift4 branch, I use `let isBold = font.fontDescriptor.symbolicTraits.contains(.bold)`, which should solve this problem.
