### ISSUE TITLE
Incorrect tab selection after tab deletion

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/apple#692]
## Deleting the currently selected tab, should always select another tab if that's possible.
The issue is that it is not always working.
The current solution is attempting to select the tab that was "historically" created before the one deleted.
This works in the following tabs scenario:
```
Tab 1 (created @ 09:00)
Tab 2 (created @ 10:00) - selected and now marked to be deleted
```
Correctly, Tab 1 is selected.

The same approach won't work here:
```
Tab 1 (created @ 09:00) - selected and now marked to be deleted
Tab 2 (created @ 10:00) 
```
There are no tabs "created before 09:00" therefore the result is:
Tab 1 is deleted, but nothing is selected.

## Solution
Do not rely on the timestamp of the tabs, they are already ordered by that anyways, instead select the Tab before, if there's such, or select the Tab after if there's such.

**Comment by kelson42** [comment]
@BPerlakiH I strongly suspect the way it works now (based on timestamp) is related to an Apple way of doing. Do you have any clue why it has been done that way?

**Comment by BPerlakiH** [comment]
@kelson42 I double checked it with Safari tabs. They behave the same way as in this PR.
If the oldest tab is deleted, it will select the next one.

To clarify things a bit: **The order of the tabs remained untouched.**
This PR only changes what happens with the selection (which tab is selected) after deleting the selected item from the (already) sorted list of tabs.

It is a minor change for this edge case:
if we delete the oldest tab (which was selected), it is not possible to find an "older than that" tab.
