### ISSUE TITLE
Display of UTF-8 chars in text/plain ZIM entry is not correct

### ISSUE THREAD

**Issue by benoit74** [kiwix/apple#698]
This has been discovered in https://github.com/openzim/libzim/issues/865#issuecomment-2003154791

We have a test ZIM at https://tmp.kiwix.org/ci/zim_characters_encoding/characters_encoding.zim

The last link (the one with all emojis) is leading to a "text/plain" document with UTF-8 encoded characters. These characters are not displayed properly.

Link to open:

![image](https://github.com/kiwix/apple/assets/7102089/e8e9490c-7b43-4826-aca7-fba1c5c28904)

Result in application:

![image](https://github.com/kiwix/apple/assets/7102089/631a4044-6961-4baa-b346-c8a534ab27ef)

Expected result (at least as displayed by browser with kiwix-serve):

![image](https://github.com/kiwix/apple/assets/7102089/11dcd259-3eb9-4603-ac17-541a6ae3985d)

Tested on 3.3.0 build 144 (testflight version)

I would assume this is a (very) low priority bug (not something we encounter in ZIMs usually), but might be easy to fix maybe (or just a nightmare because rendering component has to be swapped to something else).

**Comment by rgaudin** [comment]
OK so ZIM entries with mimetype of `text/plain` should be decoded as UTF-8, as per [the spec](https://wiki.openzim.org/wiki/ZIM_file_format#Character_Encoding)

**Comment by BPerlakiH** [comment]
So far it seems that the mime type comes from the file itself:
```
@"mime": [NSString stringWithUTF8String:item.getMimetype().c_str()],
```
which comes from:
```
  class LIBZIM_API Item : private Entry
  {
    public: // types
      typedef std::pair<std::string, offset_type> DirectAccessInfo;

    public: // functions
      std::string getTitle() const { return Entry::getTitle(); }
      std::string getPath() const  { return Entry::getPath(); }
      std::string getMimetype() const;
```
