### ISSUE TITLE
Double-clicking a ZIM opens multiple windows

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#699]
When double-clicking a ZIM in the Finder (ZIM was not in catalog), the Kiwix app opens with multiple windows:
- one with the homepage of said ZIM ; that's what I expect
- Another on the Reading part, listing my local collection

**Comment by rgaudin** [comment]
Happens regardless of ZIM being part of the collection or not

**Comment by benoit74** [comment]
If Kiwix application is already opened,  it opens 3 windows, two with the homepage of said ZIM, one with the Reading pane.

If Kiwix application is already opened on the ZIM which is double-clicked, it opens 4 new windows, three with the homepage of said ZIM, one with the Reading pane.

**Comment by kelson42** [comment]
Kiwix Desktop window for Linux Windows works as a "singleton". I think here, this is actually what this ticket requests... or do I get it wrong?

**Comment by rgaudin** [comment]
@kelson42 I believe Apple Guidelines strongly discourages _singleton_ app.

This ticket is not about this. There's a bug opening multiple windows on that actions and the more you have open, the more it opens.

**Comment by kelson42** [comment]
@BPerlakiH What is the solution envisioned?
