### ISSUE TITLE
MacOS full text search

### ISSUE THREAD

**Issue by conky2** [kiwix/apple#70]
Is full text search in MacOS no longer available?

**Comment by automactic** [comment]
Why do you need that?

**Comment by kelson42** [comment]
@conky2 Which version of Kiwix are you exactly talking about?

**Comment by conky2** [comment]
The latest build.

In the early version (v0.9, I think), I was able to build an index and do full text search.  That was a great feature.

**Comment by kelson42** [comment]
@conky2 The ability to index ZIM files won't be provided anymore in Kiwix for MacOS 2.0. That said the FTS should work if the fulltext is available in the ZIM file itself.

Older ZIM files had (and still have) an additional "*.idx" directory as a fulltext index. This is going to be deprecated and Kiwix for MacOS 2.0 won't support this.

For now we provide only a few ZIM files with this embedded FT index, but soon (in the next months) they will become more and more until summer 2018 when all of them will then have this format.

Hope this answer your question.

**Comment by conky2** [comment]
One follow-up: can I just pre-index a ZIM file myself and use it on 2.0?

**Comment by conky2** [comment]
@automactic Is there a way to get in touch with you (email. private message)?  Cornell alum here (A&S '08) looking to build a custom Kiwix app.
