### ISSUE TITLE
Functionality Issue with External Links

### ISSUE THREAD

**Issue by DobleV55** [kiwix/apple#701]
Hello 👋🏻 ,

I've come across an issue while working on #660. When clicking on a link or button that directs to an external URL, everything seems to work fine initially. However, upon attempting to click the same link or button again, it fails to function. The expected behavior should allow repeated clicks on the same link or button, even if it directs to an external URL.

To reproduce the issue:

1. Click on a link or button directing to an external URL.
2. Observe that it functions correctly for the first click.
3. Try clicking the same link or button again.

Notice that it fails to respond unless another link or button directing to an external URL is clicked in between.

**Comment by kelson42** [comment]
@BPerlakiH I guess some kind of bug related to the external link management. Such links should be handled I guess like content external links

**Comment by BPerlakiH** [comment]
Please see the fix here:
https://github.com/kiwix/apple/pull/706

**Comment by DobleV55** [comment]
Hi @BPerlakiH, just to clarify, the donation link doesn't utilize loadURL, so it doesn't trigger an interruption when clicked. The "Support Kiwik" button uses [Link()](https://developer.apple.com/documentation/swiftui/link) and opens directly.
