### ISSUE TITLE
Wikivoyage de not rendering correctly

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#71]
From the OTRS ticket queue - can someone check (@automactic or @kelson42 ) if it is an iOS or mwoffliner issue?

"The latest zim file for WikiVoyage (wikivoyage_en_all_2017-09.zim) does not render
correctly on Kiwix for iOS, not loading the CSS and showing in plain-text. I have not
tried different versions of the zim or software on other platforms."

**Comment by kelson42** [comment]
It's a bug/regression in mwoffliner. This has been fixed and I'm currently regenerating the ZIM files (for october).
