### ISSUE TITLE
Embed in another app

### ISSUE THREAD

**Issue by abhibeckert** [kiwix/apple#72]
Would this project be suitable for embedding in a macOS app as a documentation system?

I'm thinking an additional target could be added to the project to build a `.framework` that provides a controller class with `openMainPageInNewWindow(zimFile: URL)` and `openSearchPage(zimFile: URL, searchTerm: String?)` methods.

Our app, [Sequel Pro](https://github.com/sequelpro/sequelpro), has a simple MySQL reference embedded in it, and we also have a few basic help pages our website. I'm considering replacing these with a wiki on the website which the community can help maintain and the latest wiki state would be embedded in our app as a ZIM file.

Thoughts?

**Comment by kelson42** [comment]
@abhibeckert Like you can see our new native app for macOS is still pretty much in beta. That said, your plan seems perfectly valid. This is what we already do on Android and iOS with our embedded apps. Check carefully that you can export your wiki in ZIM properly (if the wiki engine is Mediawiki, this is probably a no brainer with mwoffliner).

**Comment by automactic** [comment]
Hi @abhibeckert, this project only contains code for Kiwix apps (iOS and macOS) and bridging code. You might want to start from [kiwix-build](https://github.com/kiwix/kiwix-build) to try to compile libkiwix.dylib and all its dependencies. After that, you could use some of my code in this project for reading data and integrate with UI/WKWebView

**Comment by automactic** [comment]
@abhibeckert were you able to successfully use libkiwix in your project?
