### ISSUE TITLE
On iOS and WikMed apps, we need to be more transparent if an external link is open

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#74]
With concerns about cost of data, they might not know that this opens an external page and will cost them MBs. It might be good if there was a popup that indicated that they would be opening a browser and that this 1) will not work if they're offline and 2) will cost them data if they are online. Could be 2 different popups, and you could include a "dismiss forever" option for those that don't share this concern.

Same request for Android https://github.com/kiwix/kiwix-android/issues/281

**Comment by automactic** [comment]
Fixed in 1.9(9), please test

**Comment by kelson42** [comment]
@automactic Thx, I can not test this as I do not have an ios device with mobile network. Maybe @martin8032 can?

**Comment by martin8032** [comment]
Looks good with Kiwix 1.9 (9) on iPhone (iOS 11.2.5):

![2018-02-24 19 48 21](https://user-images.githubusercontent.com/7620141/36633829-0316c860-199c-11e8-9128-903018585c8f.png)
![2018-02-24 19 47 33](https://user-images.githubusercontent.com/7620141/36633830-03431082-199c-11e8-9a8c-83bbb4784b40.png)

**Comment by kelson42** [comment]
Thank you @martin8032 for your quick feedback.
