### ISSUE TITLE
Add tab feature

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#75]
In Android Wikimed you can open multiple articles in separate tabs and switch quickly between them (hamburger icon in the top left corner).
(Wikimed beta tester feedback)

**Comment by kelson42** [comment]
@automactic Please keep one ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects. Rule about how to deal with tickets are give at https://github.com/kiwix/overview/blob/master/REPORT_BUG.md

**Comment by kelson42** [comment]
@Popolechien This has been implemented for iOS in 3.2. I shoukd check how it behaves on macOS.
