### ISSUE TITLE
Add search history

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#76]
Search terms from earlier searches could be stored and displayed when you perform a new search.
(that's a user request).
Funny enough, I had another user write to us asking specifically that we do not store article history from one session to the next. I guess we could add a tick box to get that feature on/off

(Wikimed beta tester feedback)

**Comment by automactic** [comment]
The iOS app already does exactly that. Search terms are preserved and you can also clear them in settings.

**Comment by kelson42** [comment]
@automactic The search history is not only about having the data in the app, the search history is having a way to visualize the history and go back directly to an item in it. Do you still confirm we provide that?

**Comment by automactic** [comment]
> having a way to visualize the history and go back directly to an item in it
Can you elaborate? The iOS app so store recent search text, not enough?

**Comment by automactic** [comment]
![image](https://user-images.githubusercontent.com/8294252/63098816-be6b6700-bf41-11e9-8e7c-6967cc5072d6.png)
The app already provide a search history
