### ISSUE TITLE
Add "random article" button

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#78]
On android it's hidden in the menu. But isn't there a dice as well in the top bar? (tbc and close if correct)

(Wikimed beta tester feedback)

**Comment by kelson42** [comment]
@automactic Please keep one ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects. Rule about how to deal with tickets are give at https://github.com/kiwix/overview/blob/master/REPORT_BUG.md

**Comment by automactic** [comment]
Random article feature is implemented in version 1.14 of the app

<img width="528" alt="PNG image" src="https://user-images.githubusercontent.com/8294252/104520907-e42eec80-55c9-11eb-8007-175ad9df212c.png">

**Comment by kelson42** [comment]
@automactic Great, thanl you!
