### ISSUE TITLE
Indexed Search with ä, ö,ü,ß doesn't work

### ISSUE THREAD

**Issue by Kontor23** [kiwix/apple#8]
Tested on 1.5.

Steps:
make an indexed search (in my case in the german wikipedia) containing letters like ä, ö,ü, or ß letters 

I get:
no results

**Comment by kelson42** [comment]
@Kontor23 You made the index by yourself? The indexes of Kiwix should be used. This have a normalized content, that means all words are lowercase and without diacritics.

**Comment by Kontor23** [comment]
No, I used the preindexed files provided with the download. And the diacritics search works well with the windows version, but not with the iOS version.

**Comment by automactic** [comment]
@kelson42 I checked my code. Have no idea why it didn't work...
I converted Obj-C string to c string using NSUTF8Enciding, do you think it could be a encoding problem?
Continuing investigating...

**Comment by Kontor23** [comment]
Hi,
Version 1.6 doesn't solve the problem unfortunately. When I search for a word containing for example an ä, only non indexed search results will shown up. Thank you for your investigation.

**Comment by automactic** [comment]
@Kontor23 Thanks for trying version 1.6. As of now, I have no idea why this happen. I will notify you once this issue has been resolved. Thanks!

**Comment by automactic** [comment]
using printf("%lu", searchTermC.length());
I found that ä, ö,ü,ß will each have length 2, whereas normal chars have length 1

**Comment by kelson42** [comment]
@automactic strange, might be a problem with the string internal representation. In UTF8, we have two ways to represent a character like "ü", see https://www.objc.io/issues/9-strings/unicode/#combining-character-sequences

**Comment by automactic** [comment]
Search is not handled by [kiwix/kiwix-lib](https://github.com/kiwix/kiwix-lib)
