### ISSUE TITLE
Enable Copy / Paste on Kiwix OS X

### ISSUE THREAD

**Issue by conky2** [kiwix/apple#84]
Enabling copy / paste on Kiwix OS X (similar to Kiwix for Linux)

**Comment by automactic** [comment]
You can already copy text in the macOS version of Kiwix. I am not sure what do you mean by paste? 

<img width="978" alt="Screen Shot 2020-08-16 at 12 05 10 PM" src="https://user-images.githubusercontent.com/8294252/90338594-bf056600-dfb8-11ea-9ab1-adb39aca5e73.png">

**Comment by kelson42** [comment]
@conky2 I believe it works, please reopen the ticket if we have misunderstood what you meant.
