### ISSUE TITLE
index ios

### ISSUE THREAD

**Issue by hcarrega** [kiwix/apple#86]
a friend of mine create a .zim and on kiwix on windows after index i can search everything, putting the same .zim and the .idx dir on iphone via itunes  i cant search

**Comment by kelson42** [comment]
@hcarrega you should put the ...zim file and the ....zim.idx directory in the same directory (so forget about "data" and "index" directories). Have you do that?

**Comment by hcarrega** [comment]
@kelson42 just open itunes file sharing select kiwix and drop it there

**Comment by kelson42** [comment]
@automactic any clue?

**Comment by hcarrega** [comment]
running ios 11.2 last dev beta

**Comment by automactic** [comment]
@hcarrega, the zim and idx need to have same name. So for example, if you have `abc.zim`, the index dir need to be named `abc.idx`.

**Comment by kelson42** [comment]
@automactic I propose to close that ticket with "won't fix"... we are producing now only ZIM files with indexes and they will soon be all replaced will newer version. It does not make therefore sense to invest much time on this IMO.
