### ISSUE TITLE
iOS11.2 insufficient storage in download section

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#87]
_From @Seevo on December 12, 2017 12:7_

(as postet in sourceforge)

On an iPhone6sPlus 128GB with 81GB free space and iOS 11.2 (no beta), it is impossible to download any of the 15GB library-packages. They are greyed out leaving me with the message:
“You cannot start downloading, because your device does not have enough free space for this book.”
This is obviously wrong: on the iPhone under settings->info it is stated that there are 81,17GB of free space.

_Copied from original issue: kiwix/overview#2_

**Comment by automactic** [comment]
@kelson42, Could you please confirm this issue is fixed on your iPhone on kiwix for iOS 1.9 beta?

**Comment by automactic** [comment]
This issue should be fixed, so I am closing it.

**Comment by kelson42** [comment]
@automactic As far as I can see it works properly... but I do not have so much free space anyway.
