### ISSUE TITLE
Library: No packages under CATEGORIES available

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#91]
Kiwix iOS v1.9 (2): I can open the packages under ON DEVICE (which I had downloaded with an earlier version of Kiwix) as expected. But I don't see any packages when I select an entry from CATEGORIES (i.e. "Wikivoyage"). And when I open the language filter, I can only see my own language (SHOWING > "Deutsch"), but not the other language preferences I had set (English, French), and there are no languages displayed under HIDING at all. 

Note: When I first tried to download new packages, the app asked wether I want to remove the existing language filter or not. I declined. Then the app crashed immediately. I was able to reproduce this problem on another device. The first one is running iOS 11.2.5, the second one iOS 11.2.1.

**Comment by kelson42** [comment]
I confirm a similar behaviour, I even have had one crash at that place (one time).

**Comment by automactic** [comment]
@martin8032 and @kelson42, looks like there might be some problem with app upgrade. If you were using the App Store version of kiwix (1.8.1 release), this ought not to have happened. Please perform a fresh reinstall of 1.9 beta while I investigate.

**Comment by kelson42** [comment]
@automactic Uninstalling and reinstalling fixes the problem... But we can not ask all our users to do that of course.

**Comment by automactic** [comment]
@martin8032, from what you have described, this is definitely a problem related to database schema migration. Remember the migration is only handled between two releases. In this case 1.8.1 release and 1.9 beta. This means the upgrade from a beta of 1.8.1 to 1.9 beta is likely not gonna work. And if the app does not know how to handle such cases, it is simply gonna blast the old database away and create a new one, hence empty everywhere. 

Could you please confirm you were using 1.8.1 release?

**Comment by automactic** [comment]
@kelson42, the upgrade from 1.8.1 release to 1.9 beta should work fine. Could you please confirm you were using 1.8.1 release? 

If you don't know, you can install kiwix from the App Store, use it for a bit, then upgrade to 1.9 from test flight.

**Comment by kelson42** [comment]
@automactic I do not know, I was using current iTunes store version I guess.

**Comment by martin8032** [comment]
@automactic I can't tell for sure, but since I am updating my apps regularly, I most likely had v1.8.1 installed before.

I have now deleted v1.9 and reinstalled v1.8.1 from the app store, downloaded some packages, set my language preferences to EN, FR and DE.

Then I have installed v1.9 through Testflight. Again, when I opened the library and tried to download another package, I was asked about keeping my language filter settings, which I confirmed. This time, the app did NOT crash, and I could see the available packages as expected.

**Comment by automactic** [comment]
I think the app should not re-ask if you want to keep your language filter, this need to be fixed.

**Comment by martin8032** [comment]
I agree, there is no reason why you need to confirm your language preferences.

**Comment by automactic** [comment]
The redundant language preference alert is fixed in 1.9 build 3.

**Comment by martin8032** [comment]
The language alert is still present in v1.9 (4).

**Comment by automactic** [comment]
Really? Note you need to test it by:

1. install kiwix for iOS 1.8.1 from App Store, refresh the library at least once
2. install 1.9 from TestFlight

Please let me know if 1.9 still ask you for language preference.

**Comment by martin8032** [comment]
Sorry – false alarm.
