### ISSUE TITLE
Suggestion: After deleting a package, jump back to the library overview

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#92]
Kiwix iOS 1.9 (2): When I delete a package from my device, I remain on the detail view of that package. This does not make sense, because the package is no longer present, and clicking on "Open Main Page" doesn't work anymore.

Suggestion: Jump back to the library overview.

**Comment by automactic** [comment]
Agree, will be fixed

**Comment by automactic** [comment]
@martin8032 hang on, sometimes it makes sense to remain on the package detail view. For example, if a book is downloaded from the internet, you still want to remain in the same place. Only the delete book and open main page button will be replaced with download buttons. 

In other words, I think only when the book disappears from the list on the previous screen will we jump user back to the previous screen.

**Comment by martin8032** [comment]
As far as I can see you changed the behaviour in v1.9 (3): When I delete a package, the «Delete File» and «Open Main Page» buttons disappear and are replaced by the two «Download…» buttons. That's much better.

Just to make the discussion complete: Why don't you switch back to the list? Why would someone delete a package and download it again immediately? To update the package? Then it would be much nicer to have an «Update File» button for this use case.

**Comment by automactic** [comment]
OK, what this issue suggested does make sense. 

The new behavior is going to be: when a file is deleted, going back to the previous view.

**Comment by kelson42** [comment]
@automactic I think this has been fixed with https://github.com/kiwix/apple/pull/163. You can just put the ticket number (with the #) to the PR description, and then Github will automatically close the issue by merging the PR.

**Comment by automactic** [comment]
in #163, if the app is in compact model horizontally (running like on a iPhone), when a file is deleted I it is going back to whatever view it was before
