### ISSUE TITLE
Suggestion: Loading bar when dowloading packages

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#97]
When I download a package, I have no indication how I have to wait before I can use it.

Suggestions: Display a progress bar.

**Comment by automactic** [comment]
This is a planned feature. However, I want to push it to the next version.

**Comment by garyking** [comment]
This would be especially useful when downloading a huge 20+ GB database.

**Comment by garyking** [comment]
Speaking of which, do packages resume downloading if the app is closed and re-opened later? Would be nice to see how much has been downloaded so far, at least as a number, like 10 GB of 20 GB has been downloaded so far.

**Comment by garyking** [comment]
Nevermind, just seems like for some reason, downloads are stuck at Queued.

**Comment by rgaudin** [comment]
there's now a progress text with percentage.
